### ISSUE TITLE
k8s通过polaris controller注册的服务如何与k8s外注册的服务实现互通

### ISSUE THREAD

**Issue by karl-chanel** [Tencent/spring-cloud-tencent#1002]

**Comment by chuntaojun** [comment]
k8s 内的 POD，如果走 dns 的话，可以通过注入 polaris-sidecar 实现。或者引入北极星相关治理SDK：https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/k8s%E5%92%8C%E7%BD%91%E6%A0%BC%E4%BB%A3%E7%90%86/

**Comment by karl-chanel** [comment]
我的意思是外部的vm注册的服务的ip地址(eg.192.168.0.6)，与k8s内pod的ip地址(eg.10.43.0.5)不在一个网段,那这两个服务可以互相调用吗，还是说要手动改路由表？pod内注入sidecar后就行了吗还是怎样？![cc9a6f656d70f4d9.png](https://github.com/Tencent/spring-cloud-tencent/assets/78248702/eefc0ce7-b464-417e-a1d6-c0965a3b027d)

**Comment by chuntaojun** [comment]
网络的可通性这个不在polaris的职责范围，k8s集群外的调用到k8s集群内的POD的话，需要自行将二者的网络进行打通

**Comment by karl-chanel** [comment]
就是说尽量不让这种情况发生，服务全部跑在vm上，或者全部在k8上，或者用namespace进行隔离，同一个业务全跑在同一个namespace中(此时可以选择运行在k8或是vm上)，不让其发生跨ns的调用，还有一个问题就是针对spring cloud场景，我们可以选择sidecar模式，也可以选择引入sct的模式，sidecar性能损耗会不会比引入sct高很多，还是说在这个场景下直接引入sct是最优选择

**Comment by chuntaojun** [comment]
1、这种是可以的，只是说这种情况下在网络打通层面需要花一些时间和操作
2、引入 sct 肯定是最佳选择，从性能、运维层面来说，比 sidecar 肯定是来的好的，另外就是 spring cloud 的设计体系中是无法引入 sidecar 的

**Comment by karl-chanel** [comment]
如果发生了跨k8集群的服务调用，也是要自己规划网络，手动改机器的路由表吧

**Comment by chuntaojun** [comment]
> 如果发生了跨k8集群的服务调用，也是要自己规划网络，手动改机器的路由表吧

嗯，如果网络规划存在一些问题的话，也可以通过网关的方式进行调用

**Comment by chuntaojun** [comment]
> 如果发生了跨k8集群的服务调用，也是要自己规划网络，手动改机器的路由表吧

这里 k8s 场景下多个不同网络的集群间相互访问的解决问题，这个可以在 polaris 提一个issue，应该是可以借助网关以及 Gateway 的能力进行解决
