### ISSUE TITLE
add metadata transfer for http header via  spring.cloud.tencent.metadata.content.header

### ISSUE THREAD

**Issue by karl-chanel** [Tencent/spring-cloud-tencent#1009]

**Comment by karl-chanel** [comment]
在这个[issue](https://github.com/Tencent/spring-cloud-tencent/issues/563)中，sct支持了通过环境变量添加需要透传的 http header,然而并没有添加通过配置文件的方式配置，类似于spring.cloud.tencent.metadata.content. transitive和 spring.cloud.tencent.metadata.content.disposable ,这三种属性应该都支持环境变量和配置文件的方式设置，但在配置文件中现在只支持 transitive 和disposable 两种，header的透传只能通过环境变量方式设置，应该在配置文件中也可以设置header，使其使用逻辑一致

**Comment by SkyeBeFreeman** [comment]
感谢反馈！如果感兴趣，您可以直接提交代码参与开源共建。
