### ISSUE TITLE
RouterLabelFeignInterceptor 的order顺序问题

### ISSUE THREAD

**Issue by beretaa** [Tencent/spring-cloud-tencent#1033]
RouterLabelFeignInterceptor 目前order为0, 会导致以下问题:
例如,我们需要使用header.XXX做动态路由,  为XXX这个值的透传专门在所有微服务做了一个XXXRequestInterceptor, 上游服务从header获取XXX并存入自定义context, 发起feign请求时XXXRequestInterceptor从context取出XXX并添加到RequestTemplate header中
**如果XXXRequestInterceptor的order大于0**(即晚于RouterLabelFeignInterceptor 执行),  则RouterLabelFeignInterceptor 在添加internal-router-label时将获取不到XXX的值, 最终导致动态路由判断失效

建议:
1.可否调整RouterLabelFeignInterceptor 的order为LOWEST_PRECEDENCE,使其在整个过滤器链最后执行
2.在文档动态路由部分,针对该问题做特别说明.....   **这个排查起来真的搞死人了**

**Comment by SkyeBeFreeman** [comment]
了解，我们看一下如何优化这一块。

**Comment by SkyeBeFreeman** [comment]
解决方案：
1. RouterLabelFeignInterceptor的Order置为最低优先级
2. 所有Order相关常量，统一存放在spring-cloud-tencent-common包内

**Comment by SkyeBeFreeman** [comment]
https://github.com/Tencent/spring-cloud-tencent/blob/2021.0/spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/constant/OrderConstant.java
