### ISSUE TITLE
北极星服务端关闭心跳后sct抛异常

### ISSUE THREAD

**Issue by minsonma** [Tencent/spring-cloud-tencent#1045]
**Describe the bug**
北极星服务端关闭心跳后sct抛异常  |ERROR||[grpc-default-executor-2]||Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed@36d6c092

**To Reproduce**
Steps to reproduce the behavior.
sct版本1.14.x-2020.0.6

**Expected behavior**
期望不抛异常

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
后续修复跟进：https://github.com/polarismesh/polaris/issues/1176
