### ISSUE TITLE
你好 我们是使用springcloudalibaba架构 rpc使用的是dubbo 用来替换掉feign 请问如何改为咱们sct呢

### ISSUE THREAD

**Issue by JavaLionLi** [Tencent/spring-cloud-tencent#1047]
你好 我们是使用springcloudalibaba架构 rpc使用的是dubbo 用来替换掉feign 请问如何改为咱们sct呢
按照北极星的文档 需要写注册中心地址后 手动编写注册代码
但原先用sca的时候 dubbo接口是可以自动注册到nacos上的
想用北极星达到同样的效果 但是并没有找到相关的文档说明 不知道是否可以实现这样的效果

**Comment by JavaLionLi** [comment]
另外还有另一个项目 是用 springcloudalibaba 架构 rpc用的grpc替换的feign 请问如何改为咱们sct呢
按照北极星的文档 需要写注册中心地址后 手动编写注册代码 也是跟上面一个情况 是否可以自动注册到北极星呢

**Comment by JavaLionLi** [comment]
北极星真的很强大 希望可以低成本的迁移过来

**Comment by SkyeBeFreeman** [comment]
可以参考一下这个文档：https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/java%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91/dubbo/%E6%9C%8D%E5%8A%A1%E6%B3%A8%E5%86%8C/

**Comment by JavaLionLi** [comment]
> 可以参考一下这个文档：https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/java%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91/dubbo/%E6%9C%8D%E5%8A%A1%E6%B3%A8%E5%86%8C/

这个都看过了 我上面已经说了 麻烦仔细阅读一下好吧
我的目的是希望可以自动注册 而不是像这个文档里写的手动编码注册 那样就无意义了

**Comment by chuntaojun** [comment]
> > 可以参考一下这个文档：https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/java%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91/dubbo/%E6%9C%8D%E5%8A%A1%E6%B3%A8%E5%86%8C/
> 
> 这个都看过了 我上面已经说了 麻烦仔细阅读一下好吧 我的目的是希望可以自动注册 而不是像这个文档里写的手动编码注册 那样就无意义了

dubbo 的原生接入方式是支持的，这里我们把文档调整下，其实只需要引入对应的 POM 即可，然后 nacos:// 换成 polaris:// 即可
