### ISSUE TITLE
项目中使用了sleuth，在feign调用的时候指定被调用服务的url就会导致请求失败

### ISSUE THREAD

**Issue by T13489145349** [Tencent/spring-cloud-tencent#1051]
**Describe the bug**
项目中使用了sleuth，feign调用的时候指定被调用服务的url就会导致请求失败，报错信息：com.netflix.client.ClientException: Load balancer does not have available server for client

**To Reproduce**
@FeignClient(value = "test",url = "http://127.0.0.1:9000/")

**Expected behavior**

**Environment**
- Version: 1.11.7-Hoxton.SR12

**Additional context**

**Comment by SkyeBeFreeman** [comment]
经排查，系sleuth的TraceFeignClient系列与SCT的EnhancedFeignClient冲突，在下个版本解决这个问题。感谢反馈~
