### ISSUE TITLE
如果同一个配置本地跟远端都配置了这个时候我想使用本地的不想强制覆盖这个时候需要怎么配置呢？

### ISSUE THREAD

**Issue by imaxun** [Tencent/spring-cloud-tencent#1052]
<img width="626" alt="image" src="https://github.com/Tencent/spring-cloud-tencent/assets/29112991/b8803afc-8a15-4a80-9132-7d75a4d320ef">

**Comment by SkyeBeFreeman** [comment]
Spring Cloud 本身的机制规定远端配置覆盖本地配置，因此无法保留本地配置。

不过，由于北极星支持远端配置和本地配置两种数据源，因此您可以使用`spring.cloud.polaris.config.data-source=local`的配置，然后在`polaris/backup/config/`目录下对应配置文件中修改本地配置，即可使用本地配置数据源的方式。

<img width="591" alt="image" src="https://github.com/Tencent/spring-cloud-tencent/assets/24446200/399d5dfb-c220-4710-9cb5-086041f5fcb2">
