### ISSUE TITLE
熔断修改规则中的服务名，项目运行的时候还是按照修改之前的规则熔断

### ISSUE THREAD

**Issue by minsonma** [Tencent/spring-cloud-tencent#1081]
**Describe the bug**
熔断修改规则中的服务名，项目运行的时候还是按照修改之前的规则熔断，具体步骤如下：
1.在相同命名空间下有主调A，被调B两个服务
2.规则 A->B，配置熔断降级body aaaaa 然后启用规则 rule 服务级熔断
3.多次请求之后熔断打开
4.修改规则 rule 的服务名 A->A1,B->B2,修改熔断降级body bbbbb
5.多次请求之后熔断打开，返回服务降级 aaaaa
6.查看backup中的熔断规则文件 rule的 source中service为A destination中service为B

**To Reproduce**
Steps to reproduce the behavior.
sct版本 1.11.8-2020.0.6

**Expected behavior**
期望修改服务名之后，项目运行时不再使用修改之前的规则

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by chuntaojun** [comment]
transfer to https://github.com/polarismesh/polaris/issues/1197
