### ISSUE TITLE
本地缓存路由配置失败

### ISSUE THREAD

**Issue by beretaa** [Tencent/spring-cloud-tencent#1082]
**Describe the bug**
![image](https://github.com/Tencent/spring-cloud-tencent/assets/130036897/935a7492-82c6-4be5-b418-d5865b42116d)

**Environment**
- Version: SCT 1.11.2-2020.0.6

**Additional context**
1.另外, 当内网网络不稳,导致nacos或polaris断开连接, 重连后, spring cloud gateway的所有转发会报404.  发现不到下游服务,该问题如何处理?
2.路由的内存缓存是否有过期时间.. 是通过 spring.cloud.polaris.discovery.service-list-refresh-interval来设置吗? 我看默认是60s,  如果60s后polaris还是连接失败, 是否意味着该服务缓存的路由表失效?   如果把该值调成无限大可以吗

**Comment by SkyeBeFreeman** [comment]
这个bug是如何出现的呢？

Additional context
1. 这个我回头复现一下。
2. 这个设置是服务列表拉取间隔，而非路由表失效时间。

**Comment by beretaa** [comment]
@SkyeBeFreeman  
服务正常运行中就会报该错误, 不影响业务正常处理, 但错误日志会不断产生. 看错误堆栈,一般就是配置文件/路由表/其他配置发生变更时候, 自动缓存到文件时异常

再请问一下,路由表失效时间默认多少,   哪个配置项可以修复?

**Comment by SkyeBeFreeman** [comment]
@beretaa 
1. 我运行demo正常运行时，没有发现这个错误。你可以试一下运行咱们的demo（https://github.com/Tencent/spring-cloud-tencent/tree/2021.0/spring-cloud-tencent-examples/polaris-router-example），看是否复现这个异常报错。
2. 路由表由Spring Cloud Gateway管理，我们的SDK对路由表本身是没有操作的，后面尝试复现一下，看看可能是什么原因导致的。

**Comment by chuntaojun** [comment]
服务端版本使用最新版本即可

**Comment by beretaa** [comment]
@chuntaojun  我这边尝试一下最新版本
