### ISSUE TITLE
2022版本不是跟cloud保持一致的版本嘛？感觉落后了好几个版本了

### ISSUE THREAD

**Issue by imaxun** [Tencent/spring-cloud-tencent#1083]
![image](https://github.com/Tencent/spring-cloud-tencent/assets/29112991/bf93f0ad-9316-431c-8d21-84c0b43d17c2)
![image](https://github.com/Tencent/spring-cloud-tencent/assets/29112991/6528cfae-85d0-40ce-8734-31ae532bc2e8)

**Comment by SkyeBeFreeman** [comment]
方便的话，您可以直接提交PR进行更新，参与共建~

**Comment by misselvexu** [comment]
Thank you, we will upgrade the base version as soon as possible to adapt, you can also join us to build together !
