### ISSUE TITLE
除了注解，有没有不用注解但是可以获取刷新的配置的方法？

### ISSUE THREAD

**Issue by Ive4** [Tencent/spring-cloud-tencent#1088]
如下通过Environment.getProperty(xxx)获取获取的配置不包含刷新配置，那么有没有单独某个方法来获取刷新配置？虽然有通过namespace等来直接获取配置文件，但是有没有一种通过Environment.getProperty(xxx) 这种来获取刷新后的配置，这样获取的配置和刷新的配置可以保持一致，避免直接获取单个配置文件从而导致的重启后的配置和刷新的配置可能会存在不一致的情况。

**Comment by SkyeBeFreeman** [comment]
@Ive4 我这边使用Environment.getProperty(xxx)是可以获取动态配置，会随着北极星控制台更新的。
