### ISSUE TITLE
主动探测时延时间错误上报，导致主动探测为正常，使得熔断器关闭

### ISSUE THREAD

**Issue by minsonma** [Tencent/spring-cloud-tencent#1091]
**Describe the bug**
主动探测时延时间错误上报，导致主动探测为正常，使得熔断器关闭

**To Reproduce**
Steps to reproduce the behavior.
sct版本 1.11.8-2020.0.6

**Expected behavior**
期望主动探测时延时间能够正确上报

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
fixed https://github.com/Tencent/spring-cloud-tencent/commit/42845f6d00aab58a31ee09aca65341a64d3b9ee0
