### ISSUE TITLE
如何实现如SCG RequestRateLimiter的key-resolver方式限流？

### ISSUE THREAD

**Issue by beretaa** [Tencent/spring-cloud-tencent#1092]
RT
一些场景想要根据参数, header 的值分别进行限流计数
例如: /xxx/abc?userId=123
对userId的每个值单独限流,要怎样配置

**Comment by chuntaojun** [comment]
<img width="737" alt="Screenshot 2023-08-18 at 00 08 50" src="https://github.com/Tencent/spring-cloud-tencent/assets/23445172/129608dc-90a6-47bf-80be-e7793800363d">

限流规则的匹配选择正则表达式，然后这里合并计算阈值的勾选要去掉

**Comment by beretaa** [comment]
好的 谢谢
