### ISSUE TITLE
spring.cloud.polaris.discovery.enabled设置为 false 时，服务依旧被发现。

### ISSUE THREAD

**Issue by zev-223** [Tencent/spring-cloud-tencent#1098]
Version:  1.11.9-2022.0.1

spring.cloud.polaris.discovery.enabled 设置为 false 时，服务依旧被发现

**Comment by SkyeBeFreeman** [comment]
你这个配置是控制是否发现其他服务。spring.cloud.polaris.discovery.register是控制是否被其他服务发现（是否注册到北极星注册中心）。

**Comment by zev-223** [comment]
> 你这个配置是控制是否发现其他服务。spring.cloud.polaris.discovery.register是控制是否被其他服务发现（是否注册到北极星注册中心）。

哦哦，好的。我理解错误，不过我尝试把spring.cloud.polaris.discovery.registe设置false，启动我的springboot项目的过程中有一个空指针异常（java.lang.NullPointerException: Cannot invoke "com.tencent.polaris.api.plugin.server.CommonProviderResponse.getInstanceID()" because "response" is null）从而导致项目启动失败，这个是什么原因啊？

**Comment by SkyeBeFreeman** [comment]
方便给一下完整的错误日志吗？我这边使用example运行是正常的
