### ISSUE TITLE
LogbackPolarisLogging 中使用的 API，在最新版本中已被删除

### ISSUE THREAD

**Issue by tucke** [Tencent/spring-cloud-tencent#1099]
**Describe the bug**
最新版的Springboot升级了logback日志框架，最新的logback删除了 configureByResource 方法，导致 LogbackPolarisLogging 加载配置失败

**To Reproduce**
项目运行时出现 fail to load logback configuration: 'void ch.gos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL) 
警告日志

**Expected behavior**
适配最新版本的Logback

**Environment**
- Version: [spring-cloud-tencent：1.11.9-2022.0.1，Springboot： 3.0.10，Logback：1.4.11]
- OS: [all]

**Additional context**
Logback 源码中的 configureByResource 方法的注释上写了该方法目前没有替换方法

**Comment by SkyeBeFreeman** [comment]
最新版本Logback需参考该文档更新日志配置方式，https://logback.qos.ch/manual/configuration.html#auto_configuration
