### ISSUE TITLE
1.12.0-2022.0.4 没有同步至中央库

### ISSUE THREAD

**Issue by herodotus-ecosystem** [Tencent/spring-cloud-tencent#1107]
期待已久的 1.12.0 终于发布了，感谢团队的辛苦付出！

看到 1.12.0 发布，第一时间就想来感受一下。但是 发现 1.12.0-2022.0.4 没有同步至中央库。

![image](https://github.com/Tencent/spring-cloud-tencent/assets/11025512/a647bfa1-6dee-407a-a68c-0ba99f506d49)

**Comment by SkyeBeFreeman** [comment]
还在走发布流程，请稍等。

**Comment by SkyeBeFreeman** [comment]
已同步至中央仓库。

**Comment by SkyeBeFreeman** [comment]
github页面上打tag只是发布的一个步骤，最终发布情况会在交流群中同步。

**Comment by herodotus-ecosystem** [comment]
> github页面上打tag只是发布的一个步骤，最终发布情况会在交流群中同步。

明白了，是我太着急了，感谢！

**Comment by imaxun** [comment]
> 已同步至中央仓库。

貌似还没有

**Comment by SkyeBeFreeman** [comment]
> > 已同步至中央仓库。
> 
> 貌似还没有

https://repo1.maven.org/maven2/com/tencent/cloud/spring-cloud-tencent-dependencies/1.12.0-2022.0.4/

**Comment by SkyeBeFreeman** [comment]
> > github页面上打tag只是发布的一个步骤，最终发布情况会在交流群中同步。
> 
> 明白了，是我太着急了，感谢！

感谢关注！稍后会在交流群提供发布信息。

**Comment by herodotus-ecosystem** [comment]
> > github页面上打tag只是发布的一个步骤，最终发布情况会在交流群中同步。
> 
> 明白了，是我太着急了，感谢！

我还以为是 nexus 发布组件的问题，nexus 发布组件在 jdk 17 下会失效，只能手动发布
