### ISSUE TITLE
No version 1.12.0-2022.0.4 in maven

### ISSUE THREAD

**Issue by lzysuqianqiu** [Tencent/spring-cloud-tencent#1108]

**Comment by SkyeBeFreeman** [comment]
中央仓库可以查询到，更换maven源尝试一下？https://repo1.maven.org/maven2/com/tencent/cloud/spring-cloud-tencent-dependencies/1.12.0-2022.0.4/

**Comment by lzysuqianqiu** [comment]
现在可以了，用的就是中央仓库
