### ISSUE TITLE
1.12.0-2022.0.4版本指定本地配置出现错误

### ISSUE THREAD

**Issue by imaxun** [Tencent/spring-cloud-tencent#1109]
<img width="1794" alt="408cf953bf5178ba8c45f118cf772ab" src="https://github.com/Tencent/spring-cloud-tencent/assets/29112991/1ec7438b-dbc1-447d-8e78-fb81ec62534e">

**Comment by SkyeBeFreeman** [comment]
收到，已安排修复。

**Comment by SkyeBeFreeman** [comment]
fixed in https://github.com/polarismesh/polaris-java/commit/879edeaa96363a05b3034695383097af5a79cddd.
