### ISSUE TITLE
spring boot中使用北极星限流不生效

### ISSUE THREAD

**Issue by kyh16000771** [Tencent/spring-cloud-tencent#1113]
![image](https://github.com/Tencent/spring-cloud-tencent/assets/21186864/582d5317-4574-4c61-813e-e35a65f428d4)

url： localhost:8080/api/hdInvite/pulsInviteUserAccount?userName=111  这个是我的请求地址，我在配置之后接口还是可以无限制的请求

![image](https://github.com/Tencent/spring-cloud-tencent/assets/21186864/cceb64e4-cfb6-4b99-8b84-3e7533732b08)
这个是北极星服务相关的版本

![image](https://github.com/Tencent/spring-cloud-tencent/assets/21186864/dd65ed24-8e26-4b3f-92e0-734e2dec8c05)
应用代码版本

**Comment by SkyeBeFreeman** [comment]
看了一下提交记录，主调ip限流规则是从1.11版本开始支持的，1.10版本不支持。这一块我补充到文档里面，感谢反馈！
