### ISSUE TITLE
服务发现自动配置顺序

### ISSUE THREAD

**Issue by hligaty** [Tencent/spring-cloud-tencent#1114]
`com.tencent.cloud.polaris.discovery.PolarisDiscoveryAutoConfiguration` 使用 `@Import` 导入配置类 `PolarisDiscoveryClientConfiguration`，而不是在 `org.springframework.boot.autoconfigure.AutoConfiguration.imports` 文件中导入，这样 `PolarisDiscoveryClientConfiguration` 上的 `@AutoConfigureBefore` 注解应该是不生效的？

**Comment by SkyeBeFreeman** [comment]
这里的@AutoConfigureBefore应该是可以去掉，可以确认一下。

**Comment by hligaty** [comment]
> 这里的@AutoConfigureBefore应该是可以去掉，可以确认一下。

@SkyeBeFreeman 将 `@Import` 引入的类 `PolarisDiscoveryClientConfiguration` 和 `PolarisReactiveDiscoveryClientConfiguration` 上的 `@AutoConfigureBefore` 和 `@AutoConfigureAfter` 去掉后没有发现其他问题
