### ISSUE TITLE
接口级限流上报prometheus未过滤无关接口

### ISSUE THREAD

**Issue by Jackson-Yuan** [Tencent/spring-cloud-tencent#1161]
**Describe the bug**
在服务端打开限流开关，不管接口级限流中被请求的接口是否有规则，只要请求了就会上报给prometheus

**To Reproduce**
Steps to reproduce the behavior.
sct版本 1.12.1-2020.0.6

**Expected behavior**
期望过滤无关接口，只上报与规则相关的接口数据

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
可以贴一下现象的截图吗？
