### ISSUE TITLE
熔断规则删除或者关闭prometheus仍能拉取到熔断半开放状态信息

### ISSUE THREAD

**Issue by Jackson-Yuan** [Tencent/spring-cloud-tencent#1162]
**Describe the bug**
1.熔断过程中删除或者关闭规则，此时prometheus仍可以拉取到熔断个数。到达半熔断后，一直可以拉取到半熔断的信息
  2.达到熔断半开放的状态，此时删除或者关闭规则，prometheus一直可以拉取到半熔断的信息

**To Reproduce**
Steps to reproduce the behavior.
sct版本 1.12.1-2020.0.6

**Expected behavior**
删除或者关闭规则后能后请求缓存，prometheus拉取信息正常

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
可以贴一下现象的截图吗？并查看熔断器相关北极星日志是否有输出。

**Comment by SkyeBeFreeman** [comment]
fixed by https://github.com/polarismesh/polaris-java/pull/435
