### ISSUE TITLE
RestTemplate调用方式的实例级熔断以及主动探测不生效

### ISSUE THREAD

**Issue by Jackson-Yuan** [Tencent/spring-cloud-tencent#1163]
**Describe the bug**
(1):实例级熔断无法生效，被熔断的实例仍可访问 countersCache 里面其中有一个实例的node为服务名+80端口 而不是真正的IP+端口
(2):主动探测一直失败，debug发现主动探测发起请求时为http://serviceName:port/uri 服务名没有被解析成ip只是单纯的一个服务名字符串

**To Reproduce**
Steps to reproduce the behavior.
sct版本 1.12.1-2020.0.6

**Expected behavior**
期望RestTemplate调用方式的实例级熔断以及主动探测生效
**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by andrewshan** [comment]
主动探测规则可以发一下么

**Comment by SkyeBeFreeman** [comment]
2.0.0.0 版本修复。
