### ISSUE TITLE
什么时候能支持spring boot 3.2.x ,spring cloud 2023 ?

### ISSUE THREAD

**Issue by J-v-o-i-a-l** [Tencent/spring-cloud-tencent#1164]
什么时候能支持spring boot 3.2.x ,spring cloud 2023 ?

**Comment by SkyeBeFreeman** [comment]
目前暂未启动相关工作。如有兴趣，您可以参与新版本的开源支持与开发~

**Comment by SkyeBeFreeman** [comment]
可以参考https://github.com/Tencent/spring-cloud-tencent/tree/2023.0 ，开发测试版：1.13.0-2023.0.0-SNAPSHOT
