### ISSUE TITLE
SpringCloud gateway(version:3.0.2)使用北极星(version:v1.17.2)限流功能跨域

### ISSUE THREAD

**Issue by chuntaojun** [Tencent/spring-cloud-tencent#1173]
**Describe the bug**

https://github.com/polarismesh/polaris/issues/1266

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
please give steps to reproduce the behavior.

**Comment by justdoit-aaron** [comment]
> please give steps to reproduce the behavior.

already fix！CORS has been processed in nginx
