### ISSUE TITLE
元数据传递

### ISSUE THREAD

**Issue by karl-chanel** [Tencent/spring-cloud-tencent#1198]
你好，亲爱的开发者，我想问一个问题，元数据传递是怎么实现的呢？要传递的元数据是在上游调用下游的时候在某个地方塞进去的，还是说在不发生任何调用的情况下，下游就能够获得到全链路中的元数据配置信息呢，例如a服务配置了transitive元数据，b是a服务的下游，如果a服务和b服务都刚启动，没有任何调用发生，此时的b服务是可以获取到这个a服务配置的transitive元数据吗？

**Comment by SkyeBeFreeman** [comment]
元数据是通过调用传递的，因为如果不发起调用的话，b是不知道a是上游，a也不知道b是下游。
