### ISSUE TITLE
配置中心 点击发布前端报错无反应 可以给予提示

### ISSUE THREAD

**Issue by xuyuan-feiqi** [Tencent/spring-cloud-tencent#1207]
![image](https://github.com/Tencent/spring-cloud-tencent/assets/19216352/47e4b100-2d74-4d7d-b1cd-700c3c911ed9)

**Comment by SkyeBeFreeman** [comment]
@xuyuan-feiqi 北极星相关在这里提ISSUE跟进，https://github.com/polarismesh/polaris/issues
