### ISSUE TITLE
希望能适配springboot3.2.x和springcloud2023.0.x

### ISSUE THREAD

**Issue by ciot-plus** [Tencent/spring-cloud-tencent#1209]
**What is the feature you want to add?**
springboot3.2.0已经发布,可以支持虚拟线程
springcloud2023即将在11.28发布
https://github.com/spring-cloud/spring-cloud-release/milestone/132
**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by herodotus-ecosystem** [comment]
我自己做了一下尝试，问题不是很多，目测工作量比 Spring Boot 3.0 的适配会小很多。当然这仅是个人观点，具体情况如何以及是否要做适配还得大佬们决定。

## 尝试环境

我自己的尝试的环境：
- Spring Boot 3.2.0
- Spring Cloud 2023.0.0-RC1
- Spring Cloud Tencent 1.12.4-2022.0.4

## 主要问题

使用上面三个组件，目前我本地的环境已经可以运行起来。当然， 不是说直接使用就可以跑起来，还是有一些问题，但是问题不多。

目前主要的问题就是两个：

1. 基础组件版本变更，导致 Spring Cloud Tencent GRPC 出现无法连接服务端问题。

目前已知 Spring Boot 2.7.18、3.1.6 和 3.2.0 中，将基础依赖的 netty 组件的版本，从 4.1.100.Final 升级至 了 4.1.101.Final。这就导致 Spring Cloud Tencent GRPC 无法连接到服务端。参见问题 #1210 

2. Spring Cloud Tencent 部分组件无法使用

因为目前 Spring Cloud Tencent 采用的是 uber.jar 的方式。依赖jar 的代码都已经打入到包中。Spring 生态的一些组件代码发生变化之后，就会与 Spring Cloud Tencent 现有jar 产生冲突。导致无法运行。

目前已知在 Spring Boot 3.2.0 和 Spring Cloud 2023.0.0-RC1 环境下， spring-bean.jar 和 feign 的一些代码有变化，就与现有的 Spring Cloud Tencent 有冲突，会直接导致无法运行。主要涉及的模块有：
- spring-cloud-starter-tencent-all
- spring-cloud-starter-tencent-polaris-circuitbreaker

不使用这两个模块，现有环境就可以正常跑起来。

**Comment by SkyeBeFreeman** [comment]
@herodotus-cloud 如果要使用sc 2023的话，应该是需要在sct项目单独建立2023的分支，然后做适配开发，并引入2023版本的sdk，而非直接引入2022版本的sdk。

不知您是否有兴趣参与2023版本的建设呢？

**Comment by herodotus-ecosystem** [comment]
> @herodotus-cloud 如果要使用sc 2023的话，应该是需要在sct项目单独建立2023的分支，然后做适配开发，并引入2023版本的sdk，而非直接引入2022版本的sdk。
> 
> 不知您是否有兴趣参与2023版本的建设呢？

你说的是。我是急于尝鲜所以才这样做的 :)。我是有兴趣参与项目的建设，因为我本身也搞开源。只不过确实 Spring Cloud Tencent 体系完善和全面，上手还是需要点时间。还是得先学习学习，先从简单的入手。盲目的整，就是在给项目添乱。

**Comment by SkyeBeFreeman** [comment]
目前的计划是，等1.13版本发布后，会创建2023分支，届时可以关注参与下~

**Comment by herodotus-ecosystem** [comment]
> 目前的计划是，等1.13版本发布后，会创建2023分支，届时可以关注参与下~

好的，非常感谢。我也会实时关注的。

**Comment by SkyeBeFreeman** [comment]
可以参考https://github.com/Tencent/spring-cloud-tencent/tree/2023.0 ，开发测试版：1.13.0-2023.0.0-SNAPSHOT
