### ISSUE TITLE
应用重启了，没有删除老的ip，可能是De-registering未触发？

### ISSUE THREAD

**Issue by williamliu111** [Tencent/spring-cloud-tencent#1218]
应用重启了，没有删除老的ip，可能是De-registering未触发？没有找到反注册的日志，帮忙看看，需要怎么设置才会触发反注册？

**Comment by SkyeBeFreeman** [comment]
容器运行场景下，stop未能触发shutdownhook。参考：https://blog.51cto.com/u_16175500/6890111

**Comment by williamliu111** [comment]
问题已解决，进程没有收到kill信息，容器提前结束
