### ISSUE TITLE
org.springframework.boot.autoconfigure.AutoConfiguration.imports里面的类无法自动配置了吗？

### ISSUE THREAD

**Issue by wzkris** [Tencent/spring-cloud-tencent#1222]
使用的SCT版本：1.12.4-2022.0.4
原先使用SCA可以自动加载，但是切换到SCT就不行了，必须要加上@Configuration注解才可以。
例子：
```
public class RestTemplateConfig {

    @Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder.build();
    }

    @Bean
    public RestTemplateBuilder restTemplateBuilder() {
        RestTemplateBuilder builder = new RestTemplateBuilder();

        // 增强转换器
        MappingJackson2HttpMessageConverter jackson2HttpMessageConverter = new MappingJackson2HttpMessageConverter(JsonUtil.getMapper());
        jackson2HttpMessageConverter.setDefaultCharset(StandardCharsets.UTF_8);
        jackson2HttpMessageConverter.setSupportedMediaTypes(Arrays.asList(
                MediaType.TEXT_HTML,
                MediaType.TEXT_PLAIN,
                MediaType.APPLICATION_OCTET_STREAM,
                MediaType.APPLICATION_JSON,
                MediaType.MULTIPART_FORM_DATA,
                MediaType.APPLICATION_XML,
                MediaType.APPLICATION_FORM_URLENCODED,
                MediaType.MULTIPART_FORM_DATA));
        builder.setConnectTimeout(Duration.ofSeconds(5));
        builder.setBufferRequestBody(false);
        builder.setReadTimeout(Duration.ofSeconds(5));
        builder.additionalMessageConverters(
                new StringHttpMessageConverter(StandardCharsets.UTF_8),
                jackson2HttpMessageConverter);
        return builder;
    }

}
```
该类在SCA中配置在org.springframework.boot.autoconfigure.AutoConfiguration.imports下即可自动装配，SCT里必须要加上@Configuration注解才行，这里有什么变化吗？

**Comment by SkyeBeFreeman** [comment]
你的org.springframework.boot.autoconfigure.AutoConfiguration.imports文件路径截图发一下。

**Comment by wzkris** [comment]
> 你的org.springframework.boot.autoconfigure.AutoConfiguration.imports文件路径截图发一下。

![image](https://github.com/Tencent/spring-cloud-tencent/assets/90759163/5300d2b1-4235-472c-b8e4-463604e67f07)

**Comment by SkyeBeFreeman** [comment]
我这里没有复现你的场景。我是这么操作的，看下有没有差异。
1. 创建一个resttemplate的config，
<img width="1359" alt="image" src="https://github.com/Tencent/spring-cloud-tencent/assets/24446200/ccad3f42-3199-437e-9df5-80d39068c0ab">

2. 引入这个依赖
<img width="764" alt="image" src="https://github.com/Tencent/spring-cloud-tencent/assets/24446200/b8e9df43-0e22-4c15-b4f9-a8abdff505ad">

3. 启动触发断点
<img width="1130" alt="image" src="https://github.com/Tencent/spring-cloud-tencent/assets/24446200/88d94d77-a2e7-4d60-8d39-85d23b3086d6">

**Comment by wzkris** [comment]
> 我这里没有复现你的场景。我是这么操作的，看下有没有差异。
> 
> 1. 创建一个resttemplate的config，
> 
> <img alt="image" width="1359" src="https://private-user-images.githubusercontent.com/24446200/297730175-ccad3f42-3199-437e-9df5-80d39068c0ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODcxMDEsIm5iZiI6MTcwNTU4NjgwMSwicGF0aCI6Ii8yNDQ0NjIwMC8yOTc3MzAxNzUtY2NhZDNmNDItMzE5OS00MzdlLTlkZjUtODBkMzkwNjhjMGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE0MDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZTI2YWM3ZTNhY2Q4YjdlYmI1YTZkNmFmNjFlNWZmZjI3MGY0ZDhlNWQwY2VjZGVjNGQwNTgxNTI5ZTc2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TDm1-MdGVDiXE_AWLlwOf_et2xFrw3sOOlhGPsTK6Yk">
> 2. 引入这个依赖
> 
> <img alt="image" width="764" src="https://private-user-images.githubusercontent.com/24446200/297730260-b8e9df43-0e22-4c15-b4f9-a8abdff505ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODcxMDEsIm5iZiI6MTcwNTU4NjgwMSwicGF0aCI6Ii8yNDQ0NjIwMC8yOTc3MzAyNjAtYjhlOWRmNDMtMGUyMi00YzE1LWI0ZjktYThhYmRmZjUwNWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE0MDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOWRhODQyZmYxMzYxMTMxMGFiZGYyMGYwZTFhMGNkZjU3ZTA2NWVhN2YyMDgzNjU2MzYyNTcyZjNhNzIxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ouXT6GGT_qAHpzIAQFd0axazzefM-cVjPZyuWeZhTGU">
> 3. 启动触发断点
> 
> <img alt="image" width="1130" src="https://private-user-images.githubusercontent.com/24446200/297730330-88d94d77-a2e7-4d60-8d39-85d23b3086d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODcxMDEsIm5iZiI6MTcwNTU4NjgwMSwicGF0aCI6Ii8yNDQ0NjIwMC8yOTc3MzAzMzAtODhkOTRkNzctYTJlNy00ZDYwLThkMzktODVkMjNiMzA4NmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE0MDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMTU2MmE4YzBiOTJiNmNmNjhlOGY4NTBkNTMxYzI2OTQ4YmZjODdjZGM3YzA3MzRjYThkNzkzZjJiNmVjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IRnFOSUbAdhiIakXobVPXk6kyCgbrss8YtiWisDfjI4">

一致但是我的config不会触发断点，唯一的差别就是我没有引入tencent-all依赖，我引入的是bom依赖

**Comment by wzkris** [comment]
经过排查，引入tencent-all依然无法自动配置，jdk版本17

**Comment by wzkris** [comment]
我自己重新搭了一个demo，发现确实可以正常加载，原项目不知道触发了什么导致不会自动加载
