### ISSUE TITLE
服务上线下时，心跳检查抛出异常

### ISSUE THREAD

**Issue by justdoit-aaron** [Tencent/spring-cloud-tencent#1226]
SCT版本：1.12.2-2022.0.4
描述：在服务上下线时，心跳检测会抛异常

<img width="1291" alt="image" src="https://github.com/Tencent/spring-cloud-tencent/assets/76949120/6d5f7d8e-cdc4-4ef2-ae4e-80607cc84965">

**Comment by SkyeBeFreeman** [comment]
@justdoit-aaron 
1. 这个异常会一直抛出吗？
2. 这里的逻辑是心跳之前会用http请求检查你配置的spring.cloud.polaris.discovery.health-check-url是否连通，连通了才会上报心跳。所以需要确保这个url能够正确调通。

**Comment by justdoit-aaron** [comment]
> @justdoit-aaron
> 
> 1. 这个异常会一直抛出吗？
> 2. 这里的逻辑是心跳之前会用http请求检查你配置的spring.cloud.polaris.discovery.health-check-url是否连通，连通了才会上报心跳。所以需要确保这个url能够正确调通。

不会一直报，只会在服务上下线的时候会抛出，不影响业务。健康检查地址是正确的

**Comment by SkyeBeFreeman** [comment]
这个报错是心跳上报之前调用您自身业务的健康检查接口报错，而非sct框架本身的报错，建议确保业务启动时健康检查接口是可调用的。如果确实是不可调用状态也可以忽略异常。
