### ISSUE TITLE
北极星自定义规则顺序不生效

### ISSUE THREAD

**Issue by itfsw** [Tencent/spring-cloud-tencent#1247]
**Describe the bug**
1. 在北极星中新增了两条规则，设置优先级；
2. gateway项目中，类RuleBasedRouter的getRuleFilteredInstances方法过滤规则时，```for (RoutingProto.Route route : routes) {```中的routes没有按照优先级排序；
3. 在北极星中调整优先级后重新进入断点顺序不变；
导致顺序需要忽略的规则没有过滤掉，这个顺序好像一直是创建规则的时间来排的。

SCT版本：1.13.1-2022.0.4
polaris-server: v1.18.0
polaris-console: v1.15.0

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
目前是服务端排好序后下发规则。因此SDK没有再去排序。可以通过HTTP接口查看服务端获取到的路由规则，是否按照优先级排序。

**Comment by itfsw** [comment]
polaris-server: v1.18.1 目前这个版本没有发现问题
