### ISSUE TITLE
polaris-java 1.15.0 版本有重大bug，会导致监听服务实例变化不生效

### ISSUE THREAD

**Issue by chuntaojun** [Tencent/spring-cloud-tencent#1284]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by chuntaojun** [comment]
看了下影响 spring cloud tencent 的 1.13.x 所有版本

**Comment by SkyeBeFreeman** [comment]
sct目前没有使用到com.tencent.polaris.discovery.client.flow.DefaultDiscoveryFlow#watchInstances，暂无影响。
