### ISSUE TITLE
对于 swagger OpenAPI 的配置是否可以扩展让用户自定义在配置文件中

### ISSUE THREAD

**Issue by imaxun** [Tencent/spring-cloud-tencent#1286]
![image](https://github.com/Tencent/spring-cloud-tencent/assets/29112991/b5d5265e-6df7-44f2-ab05-2f768a647b9c)

**Comment by imaxun** [comment]
同时建议增加@ConditionalOnMissingBean 避免用户若定义会出现冲突

**Comment by SkyeBeFreeman** [comment]
@imaxun #1330 允许用户自定义OpenAPI。
