### ISSUE TITLE
使用cloud-tencent,服务间grpc无法通讯问题

### ISSUE THREAD

**Issue by fwdragon** [Tencent/spring-cloud-tencent#1287]
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  cloud:
    polaris:
      address: grpc://192.168.11.156:8091
      config:
        groups:
          - name: TABR_IOT
            files: [ "datasource.yml","jetcache.yml","common.yml","forest.yml"]

配置文件如上,服务正常在注册中心展示,但是grpc间调用返回"UNAVAILABLE: Unable to resolve host dc3-center-auth"
![image](https://github.com/Tencent/spring-cloud-tencent/assets/104338536/c9398f28-f2c2-441f-b90d-30d9b35e0b15)

依赖版本如下:
spring-cloud-starter-tencent-all:1.12.4-2021.0.8
spring.boot:2.7.11
spring.cloud:2021.0.7
grpc-spring-boot-starter:2.14.0.RELEASE

**Comment by SkyeBeFreeman** [comment]
sct暂不支持grpc使用。grpc目前有单独的接入方式，https://github.com/polarismesh/grpc-java-polaris

**Comment by fwdragon** [comment]
> sct暂不支持grpc使用。grpc目前有单独的接入方式，https://github.com/polarismesh/grpc-java-polaris

好的 了解了
