### ISSUE TITLE
spring-cloud-tencent 是否有计划能接入dubbo实现自动注册

### ISSUE THREAD

**Issue by imaxun** [Tencent/spring-cloud-tencent#1289]

**Comment by SkyeBeFreeman** [comment]
dubbo接入目前使用这个项目，https://github.com/polarismesh/dubbo-java-polaris

**Comment by imaxun** [comment]
感觉用dubbo-java-polaris接入没有cloud那一套方便。这个未来不会整合到cloud里面去嘛。类似我引入一个starter的包开箱即用

**Comment by SkyeBeFreeman** [comment]
@imaxun 可以详细说一下dubbo的接入哪里会比较复杂吗？我这边收集一下，看能否优化一下流程。

**Comment by imaxun** [comment]
我看文档上面提供的注入方式需要开发中自己去实现服务的注册
![image](https://github.com/Tencent/spring-cloud-tencent/assets/29112991/b7ffc232-c74e-434d-b2cd-bc0efac43a71)

**Comment by SkyeBeFreeman** [comment]
@imaxun 这个文档好像比较旧了，可以在 https://github.com/polarismesh/dubbo-java-polaris 提个issue咨询下，因为我看到有实现一个PolarisRegistry，因此不需要手动注册接口才对。
