### ISSUE TITLE
用polaris替换奈飞的过程中gateway无法启动

### ISSUE THREAD

**Issue by wchappygood** [Tencent/spring-cloud-tencent#1290]
版本：
org.springframework.cloud:spring-cloud-starter-gateway:3.1.8
com.tencent.cloud:spring-cloud-starter-tencent-polaris-discovery:1.12.4-2021.0.8

原有配置：
spring.cloud.gateway.discovery.locator.enabled=true是开启的

无法启动，报错
![20240510103035](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/5067ee22-c7fa-45e9-99da-90827dc7d357)

把spring.cloud.gateway.discovery.locator.enabled=false关闭这个功能 就能启动

**Comment by SkyeBeFreeman** [comment]
@wchappygood 使用最新版本sct，1.13.1-2021.0.9，同时把完整的启动日志发一下。

**Comment by wchappygood** [comment]
![20240512104216](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/ad5a220b-22cc-427d-89ce-c1f42102e997)
有一个globalfilter，调用了上游服务
[Uploading 日志.txt…]()

**Comment by wchappygood** [comment]
> @wchappygood 使用最新版本sct，1.13.1-2021.0.9，同时把完整的启动日志发一下。

![20240512104216](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/ccd88afc-2be2-4506-839a-aad0d912273e)
使用了一个globalfilter 调用了上游服务
[日志.txt](https://github.com/Tencent/spring-cloud-tencent/files/15284914/default.txt)
这个是启动日志

**Comment by SkyeBeFreeman** [comment]
@wchappygood 看日志，这个userclient是在bean加载时期就去拉取了服务实例列表。但是bean加载时期北极星内部的相关bean不一定加载完成，所以会有报错。看下能否调整拉取服务实例列表的时机呢？

**Comment by wchappygood** [comment]
> @wchappygood 看日志，这个userclient是在bean加载时期就去拉取了服务实例列表。但是bean加载时期北极星内部的相关bean不一定加载完成，所以会有报错。看下能否调整拉取服务实例列表的时机呢？

现在就是考虑懒加载依赖，或者不使用spring.cloud.gateway.discovery.locator.enabled=false这个功能。是可以成功启动的

**Comment by SkyeBeFreeman** [comment]
这里有一个优化的点 #1293 ，可能和您的场景有关。后续发布snapshot版本，会提醒您尝试是否还有类似问题。

**Comment by SkyeBeFreeman** [comment]
使用1.14.0-2021.0.9-SNAPSHOT看下是否能够复现呢？

**Comment by wchappygood** [comment]
> 使用1.14.0-2021.0.9-SNAPSHOT看下是否能够复现呢？

这个版本拉不下来呢

**Comment by SkyeBeFreeman** [comment]
> > 使用1.14.0-2021.0.9-SNAPSHOT看下是否能够复现呢？
> 
> 这个版本拉不下来呢

需要添加一下snapshot的仓库。

```xml
<repository>
          <id>nexus-snapshots</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases>
            <enabled>false</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </snapshots>
        </repository>
```
