### ISSUE TITLE
自定义Prometheus拉取客户端的端口号失效

### ISSUE THREAD

**Issue by wchappygood** [Tencent/spring-cloud-tencent#1303]
版本：
1.12.4-2021.0.8

spring.cloud.polaris.stat.port设置成28085

![image](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/9e22a363-a143-4ccf-94ea-d11ff9e5c579)

```[tasklist]
### Tasks
```

**Comment by wchappygood** [comment]
![image](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/4cbc1c72-044f-4935-b5ae-6bd9be97956e)
这个对象初始化的时候，
![image](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/b1256aab-e30d-40a8-af72-0474d3dc3027)
这个对象还没初始化导致，配置没有修改到

**Comment by wchappygood** [comment]
![image](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/4cbc1c72-044f-4935-b5ae-6bd9be97956e)
这个对象初始化的时候，
![image](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/b1256aab-e30d-40a8-af72-0474d3dc3027)
这个对象还没初始化导致，配置没有修改到

**Comment by wchappygood** [comment]
找到原因了
![image](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/e0571e82-c4ba-4f91-b18c-d609e21d3053)

**Comment by SkyeBeFreeman** [comment]
如果使用bootstrap.yml做配置，需指定spring.cloud.polaris.enabled为true。

**Comment by wchappygood** [comment]
> 如果使用bootstrap.yml做配置，需指定spring.cloud.polaris.enabled为true。

> 我说下我的理解不知道对不对:
配置PolarisConfigBootstrapAutoConfiguration在bootstrap阶段就会创建PolarisContext，并把PolarisConfigModifier处理了，
而StatConfigModifier并非是bootstrap阶段，所以就无法修改配置了。

> 所以现在有没什么其他方法方法可以用配置中心的配置去修改配置，达到自定义端口的效果

**Comment by SkyeBeFreeman** [comment]
有PolarisStatPropertiesBootstrapConfiguration，那么bootstrap阶段，StatConfigModifier应该会生效才对

**Comment by SkyeBeFreeman** [comment]
在你的bootstrap.yml下加一个这个配置试试呢？
```yml
spring:
  config:
    import: optional:polaris
```

**Comment by wchappygood** [comment]
> PolarisStatPropertiesBootstrapConfiguration

![image](https://github.com/Tencent/spring-cloud-tencent/assets/26278879/18727234-12c7-4781-b709-e069209c8171)
需要手动设置这个值才能生效
但是还是不能读取配置中心的配置来设置端口

**Comment by wchappygood** [comment]
> 在你的bootstrap.yml下加一个这个配置试试呢？
> 
> ```yaml
> spring:
>   config:
>     import: optional:polaris
> ```

> 不得行，还是无法读取配置中心的配置设置端口

**Comment by SkyeBeFreeman** [comment]
@wchappygood 如下配置无法设置远端配置的端口吗？我这里尝试是可以的。
```yml
spring:
  config:
    import: optional:polaris
  cloud:
    polaris:
      enbaled: true
```

**Comment by wchappygood** [comment]
> @wchappygood 如下配置无法设置远端配置的端口吗？我这里尝试是可以的。
> 
> ```yaml
> spring:
>   config:
>     import: optional:polaris
>   cloud:
>     polaris:
>       enbaled: true
> ```
> 可以改变。但是只能通过配置在bootstrap.yml才能生效。

**Comment by SkyeBeFreeman** [comment]
@wchappygood 你的诉求是，这个配置也只通过远程配置吗？
```
spring:
  cloud:
    polaris:
      enbaled: true
```
bootstrap.yml只留？
```
spring:
  config:
    import: optional:polaris
```

**Comment by wchappygood** [comment]
> @wchappygood 你的诉求是，这个配置也只通过远程配置吗？
> 
> ```
> spring:
>   cloud:
>     polaris:
>       enbaled: true
> ```
> 
> bootstrap.yml只留？
> 
> ```
> spring:
>   config:
>     import: optional:polaris
> ```

> 我们的诉求是spring.cloud.polaris.stat.port这个可以配置在配置中心，我们用bootstrap.yml启动的

**Comment by SkyeBeFreeman** [comment]
@wchappygood 我用这个配置，是可以支持你的需求的。
应用内bootstrap.yml：
```
spring:
  config:
    import: optional:polaris
  cloud:
    polaris:
      enbaled: true
```
配置中心：
<img width="392" alt="image" src="https://github.com/Tencent/spring-cloud-tencent/assets/24446200/4cbd80ed-ca34-41ff-8318-4c753b3b5770">

**Comment by wchappygood** [comment]
> spring.cloud.polaris.stat.port

>谢谢成功了
