### ISSUE TITLE
配置中心，动态刷新能力只有在第一次修改配置时触发

### ISSUE THREAD

**Issue by itfsw** [Tencent/spring-cloud-tencent#1305]
**Describe the bug**
配置中心，动态刷新能力只有在第一次修改配置时触发

**To Reproduce**
为了防止是自己项目配置问题，clone项目`spring-cloud-tencent`使用了`polaris-config-data-example`进行了复现；

1. 启动项目，修改`teacher.name`，观察到日志中正确触发了刷新，同时使用`/person`接口验证正确更新了bean；
2. 再次修改`teacher.name`，无法触发刷新；

**Expected behavior**
每次修改能正确触发动态刷新能力；

**Environment**
- SCT: 1.13.1-2022.0.4和1.14.0-2023.0.0-SNAPSHOT
- OS: Win11

**Comment by SkyeBeFreeman** [comment]
@itfsw 使用quickstart-examples试一下呢？https://github.com/Tencent/spring-cloud-tencent/tree/2022.0/spring-cloud-tencent-examples/quickstart-example

**Comment by SkyeBeFreeman** [comment]
或者（选一）：
1、Person类添加@RefreshScope注解；
2、ConfigController类删除@RefreshScope注解。

**Comment by chuntaojun** [comment]
如果服务端使用时 1.18.0 的话，会存在这个 bug，可以把 server 换成这个：https://github.com/polarismesh/polaris/releases/tag/v1.18.1-alpha.0
