### ISSUE TITLE
限流模块对象未回收导致服务假死

### ISSUE THREAD

**Issue by Gordon-Gan-Jiang** [Tencent/spring-cloud-tencent#1326]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]
<dependency>
        <groupId>com.tencent.cloud</groupId>
        <artifactId>spring-cloud-starter-tencent-polaris-ratelimit</artifactId>
        <version>1.13.2-Hoxton.SR12</version>
      </dependency>
**Additional context**
详情可以查看dump 分析图

![image](https://github.com/Tencent/spring-cloud-tencent/assets/62733672/6e938409-7793-499b-84c7-6e167bb0d72a)

**Comment by chuntaojun** [comment]
好的，我们尽快定位看下这个问题

**Comment by andrewshan** [comment]
可以分享一下dump里面的数据么？

**Comment by Gordon-Gan-Jiang** [comment]
这dump 文件有点大，我私发廖春涛大佬了

**Comment by chuntaojun** [comment]
@Gordon-Gan-Jiang 问题已修复，可以升级试试
