### ISSUE TITLE
最新版本的cloud：1.13.2-2023.0.0 不支持 polaris v1_18_1

### ISSUE THREAD

**Issue by imaxun** [Tencent/spring-cloud-tencent#1360]
最新版本的cloud：1.13.2-2023.0.0 不支持 polaris v1_18_1：
<img width="1866" alt="image" src="https://github.com/user-attachments/assets/d996b326-4bde-4ef7-a365-63d3d274231b">

<img width="957" alt="image" src="https://github.com/user-attachments/assets/92e16d05-469f-41dc-9858-4b351801be69">

**Comment by fuyuwei01** [comment]
hi，方便提供客户端的相关代码和日志吗？

**Comment by chuntaojun** [comment]
这个问题转到 polarismesh/polaris 吧

**Comment by imaxun** [comment]
> 您好，方便提供客户端的相关代码和日志吗？
就是正常的demo上报就会报错，原因是因为polaris v1_18_1的表结构中的Namespace是非空

**Comment by SkyeBeFreeman** [comment]
@imaxun 这个问题移步 https://github.com/polarismesh/polaris/issues 讨论。麻烦在 polarismesh/polaris 项目提一个新的ISSUE 。

**Comment by imaxun** [comment]
> @imaxun这个问题移步https://github.com/polarismesh/polaris/issues讨论。麻烦在polarismesh/polaris项目提一个新的ISSUE。

好的
