### ISSUE TITLE
验证北极星服务可见性

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#1364]

**Comment by fuyuwei01** [comment]
对polaris-server-1.18.2-SNAPSHOT 测试了命名空间服务可见性功能。验证客户端调用远程服务时，拉取的服务实例namespace为该实例本身的namespace。
<img width="1622" alt="验证polaris可见性更新" src="https://github.com/user-attachments/assets/364f97df-0ecf-4f16-8477-8086b26d36a3">
