### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by yancong303** [Tencent/spring-cloud-tencent#1434]
I'm a java programmer, and I get really sick when I use Polaris. As a novice, just started to use, the official demo is too omitted, such as pom dependency introduction, need to introduce all. We are doing a project, if the introduction of all will cause jar conflicts, this risk is very big. However, the official does not give each function needs to be introduced separately jar examples, a simple brush, the document to find many times, there is no this description, the entry is very difficult, let alone use.

**Comment by SkyeBeFreeman** [comment]
You can find how to import individual functions in the documentation, https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Discovery-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
