### ISSUE TITLE
服务启动后 后台修改配置，服务中的配置并不会更新

### ISSUE THREAD

**Issue by junex233** [Tencent/spring-cloud-tencent#1437]
**Describe the bug**
服务启动后 后台更新配置，服务中的配置并不会更新。再次修改，服务中的配置会更新。也就是说，只有第一次修改会出现后台更新、服务不更新的问题。

**Expected behavior**
服务启动后，后台第一次更新配置，服务中的配置会随之更新

**Environment**
artifactId=spring-cloud-starter-tencent-polaris-config
groupId=com.tencent.cloud
version=1.11.7-2021.0.6

**Additional context**
示例代码：
@Slf4j
@Component
@Getter
public class PolarisDynamicConfig {
    @Value("${testName}")
    private String name;
}

**Comment by itfsw** [comment]
建议升级Polaris版本到v1.18.1，SCT 版本到2.0.0.0-2022.0.5-RC1，当然你cloud版本是2021，这个看官方什么时候出2.0.0.0的版本，我用的2022版本也遇到同样的问题，直到这个最新版本就完全没有问题了。

**Comment by junex233** [comment]
> 建议升级Polaris版本到v1.18.1，SCT 版本到2.0.0.0-2022.0.5-RC1，当然你cloud版本是2021，这个看官方什么时候出2.0.0.0的版本，我用的2022版本也遇到同样的问题，直到这个最新版本就完全没有问题了。

很难想象开源代码会有这么显而易见的错误

**Comment by itfsw** [comment]
当时我也遇到这个问题[issue#1305](https://github.com/Tencent/spring-cloud-tencent/issues/1305)，官方回复的是升级Polaris版本到v1.18.1，升级后官方demo能正常跑了，但是实际项目里刷新还是有问题，直到2.0.0.0-2022.0.5-RC1才稳定。你也可以试下升级v1.18.1，有可能是我实际项目某些配置正好和官方冲突了。

**Comment by junex233** [comment]
> 当时我也遇到这个问题[issue#1305](https://github.com/Tencent/spring-cloud-tencent/issues/1305)，官方回复的是升级Polaris版本到v1.18.1，升级后官方demo能正常跑了，但是实际项目里刷新还是有问题，直到2.0.0.0-2022.0.5-RC1才稳定。你也可以试下升级v1.18.1，有可能是我实际项目某些配置正好和官方冲突了。

咱俩的问题不一样。我是第一次修改不会更新，后面的修改会更新 😂

**Comment by SkyeBeFreeman** [comment]
2.0.0.0 版本修复。
