### ISSUE TITLE
什么时候发布spring-cloud 2024的适配版本

### ISSUE THREAD

**Issue by Kerbores** [Tencent/spring-cloud-tencent#1475]
有没有规划支持spring-cloud 2024版本?如有发布计划是什么样的?大概在什么时候发布?

**Comment by herodotus-ecosystem** [comment]
个人项目已经升级完。目前看，Spring Cloud 2024 只是绑定了 Spring Boot 3.4。除了已有功能的改进和提升，没有什么太大的破坏性变化。升级应该比较简单，升级一下依赖改一下版本号。当然，具体的还要看具体的软件，难说哪个实现会用到较大的变化。

**Comment by SkyeBeFreeman** [comment]
等 SCT 2.0 的 2023 版本发布后，开 2024 的分支。

**Comment by SkyeBeFreeman** [comment]
https://github.com/Tencent/spring-cloud-tencent/tree/2024

**Comment by SkyeBeFreeman** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/tencent/cloud/spring-cloud-tencent-dependencies/2.0.0.0-2024.0.0-SNAPSHOT/
