### ISSUE TITLE
support for springboot 2.6.x

### ISSUE THREAD

**Issue by wuqingfeng234** [Tencent/spring-cloud-tencent#172]
**What is the feature you want to add?**
support for spring boot 2.6.x
**Why do you want to add this feature?**
我们正在使用springboot 2.6.x，同时也有引入spring cloud tencent的打算，所以希望spring cloud tencent能够兼容springboot 2.6.x
**How to implement this feature?**
测试spring cloud tencent与springboot2.6.x兼容性，如果不兼容，调整代码使之兼容。
**Additional context**
No

**Comment by SkyeBeFreeman** [comment]
Will release in version of 1.5.0.

**Comment by misselvexu** [comment]
So ~ We need to upgrade `spring-cloud-commons` version with `3.1.x` ?

**Comment by SkyeBeFreeman** [comment]
> So ~ We need to upgrade `spring-cloud-commons` version with `3.1.x` ?

Yes. Do you want to contribute to support Spring Cloud 2021.x?

**Comment by misselvexu** [comment]
> > So ~ We need to upgrade `spring-cloud-commons` version with `3.1.x` ?
> 
> @misselvexu Yes. Do you want to contribute to support Spring Cloud 2021.x?

A little question, does the component support like zuul and Netflix ribbon need to be replaced or removed?

**Comment by SkyeBeFreeman** [comment]
> > > So ~ We need to upgrade `spring-cloud-commons` version with `3.1.x` ?
> > 
> > 
> > @misselvexu Yes. Do you want to contribute to support Spring Cloud 2021.x?
> 
> A little question, does the component support like zuul and Netflix ribbon need to be replaced or removed?

You can see branch [2020.0](https://github.com/Tencent/spring-cloud-tencent/tree/2020.0).

**Comment by misselvexu** [comment]
> > > > So ~ We need to upgrade `spring-cloud-commons` version with `3.1.x` ?
> > > 
> > > 
> > > @misselvexu Yes. Do you want to contribute to support Spring Cloud 2021.x?
> > 
> > 
> > A little question, does the component support like zuul and Netflix ribbon need to be replaced or removed?
> 
> You can see branch [2020.0](https://github.com/Tencent/spring-cloud-tencent/tree/2020.0).

Spring Cloud Tencent Adaptation 2021.x version number rules ?

**Comment by misselvexu** [comment]
@SkyeBeFreeman  
I have completed the compatibility of spring boot `2.6.x` and spring cloud `3.1.x`. Need to add a new branch (eg: `2021.x`)
 or do I just apply to merge to the `2020.0` branch?

**Comment by SkyeBeFreeman** [comment]
> @SkyeBeFreeman I have completed the compatibility of spring boot `2.6.x` and spring cloud `3.1.x`. Need to add a new branch (eg: `2021.x`) or do I just apply to merge to the `2020.0` branch?

I will create branch 2021.0 from branch 2020.0.

**Comment by SkyeBeFreeman** [comment]
@misselvexu You can commit as 1.4.4-2021.0.2-SNAPSHOT and will release immediately.

**Comment by SkyeBeFreeman** [comment]
1.4.3-2021.0.2 is released.
