### ISSUE TITLE
[Code Formatting] Is it necessary to add a unified code formatting plugin .

### ISSUE THREAD

**Issue by misselvexu** [Tencent/spring-cloud-tencent#185]
**What is the feature you want to add?**
Add formatting plugins as required by the Spring Cloud community for code formatting .

**Why do you want to add this feature?**
Add maven plugin `spring-javaformat-maven-plugin`

```xml
<plugin>
    <groupId>io.spring.javaformat</groupId>
    <artifactId>spring-javaformat-maven-plugin</artifactId>
</plugin>
```

**How to implement this feature?**
Add `spring-javaformat-maven-plugin` in parent `pom.xml` file .

**Additional context**
none .

**Comment by SkyeBeFreeman** [comment]
I tried to add this plugin before, but the effect was not satisfactory, so I decided not to add it for the time being.

**Comment by SkyeBeFreeman** [comment]
I tried to add this plugin before, but the effect was not satisfactory, so I decided not to add it for the time being.

**Comment by misselvexu** [comment]
> I tried to add this plugin before, but the effect was not satisfactory, so I decided not to add it for the time being.

Got it .
