### ISSUE TITLE
服务注册和发现客户端依赖guava版本较低，会造成启动失败

### ISSUE THREAD

**Issue by vinartis** [Tencent/spring-cloud-tencent#231]
服务注册和发现客户端依赖guava版本较低，会造成启动失败
![8085938ddd7b31da240ea33f1365e1e](https://user-images.githubusercontent.com/4651907/173515631-21b1e21e-d904-4359-9807-df65fd936a54.png)
`at com.codemes.tencent.discovery.DiscoveryClientApp.main(DiscoveryClientApp.java:13) ~[classes/:na]
Caused by: java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, char, java.lang.Object)'
 at io.grpc.Metadata$Key.validateName(Metadata.java:742) ~[grpc-api-1.33.0.jar:1.33.0]
 at io.grpc.Metadata$Key.<init>(Metadata.java:750) ~[grpc-api-1.33.0.jar:1.33.0]
 at io.grpc.Metadata$Key.<init>(Metadata.java:668) ~[grpc-api-1.33.0.jar:1.33.0]
 at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:959) ~[grpc-api-1.33.0.jar:1.33.0]
 at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:954) ~[grpc-api-1.33.0.jar:1.33.0]`

pom配置如下
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.9.RELEASE</version>
    </parent>

    <groupId>com.codemes.tencent</groupId>
    <artifactId>tencent-discovery-client</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>

        <dependency>
            <groupId>com.tencent.cloud</groupId>
            <artifactId>spring-cloud-starter-tencent-polaris-discovery</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>tencent-discovery-client</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.tencent.cloud</groupId>
                <artifactId>spring-cloud-tencent-dependencies</artifactId>
                <version>1.5.0-Hoxton.SR9</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>`

**Comment by lepdou** [comment]
@vinartis 
Thanks for report a bug. 
We have reproduced the bug and will fix it in the next release.
