### ISSUE TITLE
ERR-1006(SERVER_USER_ERROR), server error 400141: heartbeat on disabled instance

### ISSUE THREAD

**Issue by vinartis** [Tencent/spring-cloud-tencent#233]
Describe the bug
写了一个简单的服务注册的示例，启动后报如下错误，大约报了6次后，停止报错
`2022-06-14 20:59:55.744 ERROR 1636 --- [oud-heartbeat-1] c.t.c.p.registry.PolarisServiceRegistry  : polaris heartbeat[SERVER_USER_ERROR]

com.tencent.polaris.api.exception.PolarisException: ERR-1006(SERVER_USER_ERROR), server error 400141: heartbeat on disabled instance
        at com.tencent.polaris.plugins.connector.grpc.GrpcUtil.checkResponse(GrpcUtil.java:141) ~[connector-polaris-grpc-1.6.0.jar!/:na]
        at com.tencent.polaris.plugins.connector.grpc.GrpcConnector.heartbeat(GrpcConnector.java:397) ~[connector-polaris-grpc-1.6.0.jar!/:na]
        at com.tencent.polaris.discovery.client.api.DefaultProviderAPI.heartbeat(DefaultProviderAPI.java:136) ~[polaris-discovery-client-1.6.0.jar!/:na]
        at com.tencent.cloud.polaris.registry.PolarisServiceRegistry.lambda$heartbeat$0(PolarisServiceRegistry.java:233) ~[spring-cloud-starter-tencent-polaris-discovery-1.5.0-Hoxton.SR9.jar!/:1.5.0-Hoxton.SR9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_332]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_332]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_332]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_332]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_332]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_332]
        at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_332]
`

**To Reproduce**

polaris 启动
![image](https://user-images.githubusercontent.com/4651907/173716317-9d132a23-0174-4a2a-b2c4-1751d40e30ba.png)

大约30秒后，启动应用
java -jar tencent-discovery-client.jar

应用代码如下

**main 方法**
`@EnableDiscoveryClient
@SpringBootApplication
public class DiscoveryClientApp {

    public static void main(String[] args) {
        SpringApplication.run(DiscoveryClientApp.class,args);
    }
}
`

**bootstrap.yml**
`server:
  port: 8789

spring:
  application:
    name: tencent-discovery-client
  cloud:
    polaris:
      address: grpc://localhost:8091
      namespace: default`

**pom.xml**

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.9.RELEASE</version>
    </parent>

    <groupId>com.codemes.tencent</groupId>
    <artifactId>tencent-discovery-client</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>

        <dependency>
            <groupId>com.tencent.cloud</groupId>
            <artifactId>spring-cloud-starter-tencent-polaris-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>20.0</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>tencent-discovery-client</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.tencent.cloud</groupId>
                <artifactId>spring-cloud-tencent-dependencies</artifactId>
                <version>1.5.0-Hoxton.SR9</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>`

### **Environment**
- openjdk version "1.8.0_332"
- OS: CentOs7.6
- polaris version: polaris-standalone-release_v1.9.0.linux.amd64.zip

**Comment by SkyeBeFreeman** [comment]
到polaris-server目录找到日志，看下里面的报错信息

**Comment by vinartis** [comment]
> 

看哪个文件？没发现奇怪的错误，
![image](https://user-images.githubusercontent.com/4651907/173720053-e80523c2-a511-48f9-844c-34ab8b3ae60b.png)

**Comment by SkyeBeFreeman** [comment]
这里是polaris-server的心跳缓存导致的问题，我这边联系北极星的开发者看下

**Comment by vinartis** [comment]
[polaris-naming.log](https://github.com/Tencent/spring-cloud-tencent/files/8905177/polaris-naming.log)
[polaris-cache.log](https://github.com/Tencent/spring-cloud-tencent/files/8905179/polaris-cache.log)
补充两个日志文件

**Comment by SkyeBeFreeman** [comment]
> [polaris-naming.log](https://github.com/Tencent/spring-cloud-tencent/files/8905177/polaris-naming.log) [polaris-cache.log](https://github.com/Tencent/spring-cloud-tencent/files/8905179/polaris-cache.log) 补充两个日志文件

@chuntaojun cc

**Comment by SkyeBeFreeman** [comment]
后续在 polarismesh/polaris#438 同步。
