### ISSUE TITLE
提升spring-cloud-starter-tencent-metadata-transfer模块的单元测试覆盖率

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#238]
- 目标提升到80%以上
<img width="554" alt="image" src="https://user-images.githubusercontent.com/24446200/173997562-7be9408b-e60a-4517-bbfd-730832cd285f.png">

- 如何获取单侧覆盖率：
1. 项目根目录下运行`mvn test`
2. 项目根目录下用浏览器打开`target/site/jacoco/index.html`即可查看单侧覆盖率，点进去即可查看详细覆盖情况以作出补充

**Comment by shouyuwang** [comment]
Please assign this issue to me

**Comment by SkyeBeFreeman** [comment]
@shouyuwang 本issue已纳入腾源会主办的开源摘星计划，如果有兴趣领取奖品，可以[查看此处](https://github.com/weopenprojects/WeOpen-Star/issues/17)了解详细参与方式。
