### ISSUE TITLE
提升spring-cloud-tencent-polaris-loadbalancer模块的单元测试覆盖率

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#239]
- 目标提升到80%以上
<img width="551" alt="image" src="https://user-images.githubusercontent.com/24446200/173997684-f20e48c8-b8b3-42d8-9814-9ef585537f17.png">

- 如何获取单侧覆盖率：
1. 项目根目录下运行`mvn test`
2. 项目根目录下用浏览器打开`target/site/jacoco/index.html`即可查看单侧覆盖率，点进去即可查看详细覆盖情况以作出补充

**Comment by lapple06** [comment]
Please assign this issue to me
