### ISSUE TITLE
Support circuitbreaker in RestTemplate

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#241]
**What is the feature you want to add?**

RestTemplate支持熔断功能。

**Why do you want to add this feature?**

使用RestTemplate也能接入北极星熔断。

**How to implement this feature?**

针对RestTemplate进行包装，在调用结束后上报调用结果，参考Feign的实现：
`https://github.com/Tencent/spring-cloud-tencent/blob/main/spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/feign/PolarisFeignClient.java`。

**Additional context**
No.

**Comment by weihubeats** [comment]
can i try this issues

**Comment by SkyeBeFreeman** [comment]
> can i try this issues

OK. Plz give your plan before trying this issue. ^ ^

**Comment by weihubeats** [comment]
Can I directly customize ResponseErrorHandler and report the request result

**Comment by SkyeBeFreeman** [comment]
@weihubeats It looks good, commit the code and add an example to try.

**Comment by SkyeBeFreeman** [comment]
@weihubeats 本issue已纳入腾源会主办的开源摘星计划，如果有兴趣领取奖品，可以[查看此处](https://github.com/weopenprojects/WeOpen-Star/issues/17)了解详细参与方式。
