### ISSUE TITLE
服务注册发现支持优雅上下线

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#242]
**What is the feature you want to add?**

服务注册发现支持优雅上下线。

**Why do you want to add this feature?**

最终实现参考：
- 服务上线时，待服务准备完成，再注册。
- 服务下线时，先解注册，再待所有请求执行完成后，结束进程。

**How to implement this feature?**

实现代码前，需要在issue内提出方案，待讨论后再进行开发。

**Additional context**
No.

**Comment by weihubeats** [comment]
是否可以这样实现: 服务上线可以提供一个延迟发布配置，这个延迟发布时间配置交给用户去定义。服务下线可以去监听ContextClosedEvent事件完成服务下线。

**Comment by cheese8** [comment]
Assign me if it is convient.

**Comment by weihubeats** [comment]
那将这个任务给我试试？

**Comment by mathcad** [comment]
1.服务上线时，待服务准备完成，再注册
如何定义服务准备完成？目前并没有标准，延迟注册，延迟多久？也很难有统一的说法。所以默认策略采用在spring context初始化完成后再注册可能比较合适，同时开放一个扩展点，对有自定义需求(比如用户项目有其他组件需要初始化，与spring 的周期不完全一致时）的用户，在自己项目需要的时机去注册(例如通过注解开启手动注册，然后自行在某处通过提供的api触发实例注册行为)

2.优雅停机
spring已经注册了shutdown hoot，无论是外部kill还是主动close, context的close会首先发布ContextCloseEvent给事件监听器，所以是否可以考虑注册一个最高优先级的ApplicationListener来处理停机事件，解注册？

**Comment by SkyeBeFreeman** [comment]
这一块会在 #266 committer周会详细讨论，大家的想法都会纳入考虑

**Comment by 1004789224** [comment]
> 1.服务上线时，待服务准备完成，再注册 如何定义服务准备完成？目前并没有标准，延迟注册，延迟多久？也很难有统一的说法。所以默认策略采用在spring context初始化完成后再注册可能比较合适，同时开放一个扩展点，对有自定义需求(比如用户项目有其他组件需要初始化，与spring 的周期不完全一致时）的用户，在自己项目需要的时机去注册(例如通过注解开启手动注册，然后自行在某处通过提供的api发布一个特殊类型的event触发实例注册)
> 
> 2.优雅停机 spring已经注册了shutdown hoot，无论是外部kill还是主动close, context的close会首先发布ContextCloseEvent给事件监听器，所以是否可以考虑注册一个最高优先级的ApplicationListener来处理停机事件，解注册？

spring boot 有自己的就绪检测，https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes。

**Comment by lepdou** [comment]
@cheese8 @1004789224 @mathcad @weihubeats 
感谢各位的讨论。

我尝试总结一下：

### 服务优雅上线

#### 1. 整体机制

首先整体的原则是尽量复用 Spring Cloud/Spring Boot 已有的机制，在此基础上做扩展。所以 @1004789224 提到的 /actuator/health/readiness 和 ApplicationReadyEvent 事件非常重要。SCT 在决定是否注册到注册中心时，统一判断 ApplicationReadyEvent 或者 /actuator/health/readiness 是否ok，如果 ok 就发起注册。

但是这种方式的前提是：
1. /actuator/health/readiness 和 ApplicationReadyEvent 是否已经覆盖所有场景
3. 如果没有覆盖所有场景，是否留出足够的扩展方便用户自定义行为
4. 如果没有留出足够的扩展，那是不是在 sct 层面留出 SPI 用于用户的自定义 ready 能力

#### 2. SPI 扩展能力
我们是否可以定义 SPI，例如 `RegistryReadiness#isReady`，然后提供一些默认实现，例如 

1. DelayRegistryReadiness 。@weihubeats 所说，大部分情况下，可能延迟个一段时间就能满足需求了。那我们提供一个 DelayRegistryReadiness 实现类，用户如果使用这种机制，那就实例化一个bean，然后搞个配置项，定义延迟时间。
2. 用户自定义的 RegistryReadiness
3. ...

当用户注入所有的 RegistryReadiness 都 ready 之后，再向注册中心发起情况。

#### 3. 兜底保护机制

是否提供兜底机制，因为用户扩展的 SPI 由于某些可能导致永远注册不上去，这时候如果应用全量发布了，会导致整体服务不可用，这个很危险。所以比如可以定义一个时间，比如1分钟，如果还没有全部ready，也会注册上去。当前这个行为可以让用户选择。但是框架层面，也得提供这种兜底机制。

### 服务优雅下线

服务下线思路应该是跟服务上线基本上差不多。就像 @cheese8 说的。
> 服务治理中心提供DeRegistration接口
服务提供者addJvmShutdownHook/ContextCloseEvent事件，先解注册服务注册中心，后根据自身执行情况，做一定的延时后下线。
服务提供者根据自身情况，实现DeRegistration接口，在该接口实现中，先解注册服务注册中心，后根据自身执行情况，做一定的延时后下线。

我们可以定义一个 SPI，然后提供一些默认实现以及用户自定义实现。
1. 像延迟这种场景，我们内置 DelayXXX 实现，方便用户快速使用。
2. 针对流量这一块，是不是可以搞一个 TrafficXXX 实现，实现原理是在 Filter里搞一个极速器，统计进来的请求以及响应的请求。如果请求都响应完了，就认为已经ok了。

SPI 是核心，当所有SPI实现类都 ok 了才下线。当前也需要提供兜底保护机制，例如1分钟内还没ok，就强制 shutdown。

@cheese8 @weihubeats 有空一起看一下呢？方案定了咱就开搞~

**Comment by 1004789224** [comment]
> @cheese8 @1004789224 @mathcad @weihubeats 感谢各位的讨论。
> 
> 我尝试总结一下：
> 
> ### 服务优雅上线
> #### 1. 整体机制
> 首先整体的原则是尽量复用 Spring Cloud/Spring Boot 已有的机制，在此基础上做扩展。所以 @1004789224 提到的 /actuator/health/readiness 和 ApplicationReadyEvent 事件非常重要。SCT 在决定是否注册到注册中心时，统一判断 ApplicationReadyEvent 或者 /actuator/health/readiness 是否ok，如果 ok 就发起注册。
> 
> 但是这种方式的前提是：
> 
> 1. /actuator/health/readiness 和 ApplicationReadyEvent 是否已经覆盖所有场景
> 2. 如果没有覆盖所有场景，是否留出足够的扩展方便用户自定义行为
> 3. 如果没有留出足够的扩展，那是不是在 sct 层面留出 SPI 用于用户的自定义 ready 能力
> 
> #### 2. SPI 扩展能力
> 我们是否可以定义 SPI，例如 `RegistryReadiness#isReady`，然后提供一些默认实现，例如
> 
> 1. DelayRegistryReadiness 。@weihubeats 所说，大部分情况下，可能延迟个一段时间就能满足需求了。那我们提供一个 DelayRegistryReadiness 实现类，用户如果使用这种机制，那就实例化一个bean，然后搞个配置项，定义延迟时间。
> 2. 用户自定义的 RegistryReadiness
> 3. ...
> 
> 当用户注入所有的 RegistryReadiness 都 ready 之后，再向注册中心发起情况。
> 
> #### 3. 兜底保护机制
> 是否提供兜底机制，因为用户扩展的 SPI 由于某些可能导致永远注册不上去，这时候如果应用全量发布了，会导致整体服务不可用，这个很危险。所以是否可以定义一个时间，比如1分钟，如果还没有全部ready，也会注册上去。当然这个行为可以让用户选择，例如 SPI 提供一个#是否可选#的一个接口，如果可选的话在 deadline 到了之后，可以忽略。如果是强制的话，则即使到了 deadline 也不注册。
> 
> ### 服务优雅下线
> 服务下线思路应该是跟服务上线基本上差不多。就像 @cheese8 说的。
> 
> > 服务治理中心提供DeRegistration接口
> > 服务提供者addJvmShutdownHook/ContextCloseEvent事件，先解注册服务注册中心，后根据自身执行情况，做一定的延时后下线。
> > 服务提供者根据自身情况，实现DeRegistration接口，在该接口实现中，先解注册服务注册中心，后根据自身执行情况，做一定的延时后下线。
> 
> 我们可以定义一个 SPI，然后提供一些默认实现以及用户自定义实现。
> 
> 1. 像延迟这种场景，我们内置 DelayXXX 实现，方便用户快速使用。
> 2. 针对流量这一块，是不是可以搞一个 TrafficXXX 实现，实现原理是在 Filter里搞一个计数器，统计进来的请求以及响应的请求。如果请求都响应完了，就认为已经ok了。
> 
> SPI 是核心，当所有SPI实现类都 ok 了才下线。当前也需要提供兜底保护机制，例如1分钟内还没ok，就强制 shutdown。
> 
> ### 优先实现 Spring Cloud
> @cheese8 提到了非 Spring Cloud 的实现。我在想，我们是不是可以先实现 Spring Cloud 的场景。把这个路跑通了之后，再实现其它的场景，聚焦一点。
> 
> @cheese8 @weihubeats 有空一起看一下呢？方案定了咱就开搞~
我觉得可以参考下k8s的探针，来做优雅上线
在k8s中，存在启动、就绪、存活探测
启动-> 了解容器何时才完成启动，后续才可以进行就绪和存活探测
就绪-> 容器就绪才可以接受流量
存活-> 检查应用是否可以正常提供服务,允许容器已不健康的形式存活，通过自动重启，保证服务的可用性
。[https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#%E5%87%86%E5%A4%87%E5%BC%80%E5%A7%8B](url)

**Comment by weihubeats** [comment]
readiness 事件主要还是spring boot针对k8s准备的就绪事件。我们容器不在k8s中需要手动去开启这个事件，使用这个事件是否合理呢

**Comment by 1004789224** [comment]
> readiness 事件主要还是spring boot针对k8s准备的就绪事件。我们容器不在k8s中需要手动去开启这个事件，使用这个事件是否合理呢

spring 只保证了容器完成refresh，但是对于接口是否可用并不保证，理论上refresh完成，接口都应该是可用的

**Comment by cheese8** [comment]
> @cheese8 @1004789224 @mathcad @weihubeats 感谢各位的讨论。
> 
> 我尝试总结一下：
> 
> ### 服务优雅上线
> #### 1. 整体机制
> 首先整体的原则是尽量复用 Spring Cloud/Spring Boot 已有的机制，在此基础上做扩展。所以 @1004789224 提到的 /actuator/health/readiness 和 ApplicationReadyEvent 事件非常重要。SCT 在决定是否注册到注册中心时，统一判断 ApplicationReadyEvent 或者 /actuator/health/readiness 是否ok，如果 ok 就发起注册。
> 
> 但是这种方式的前提是：
> 
> 1. /actuator/health/readiness 和 ApplicationReadyEvent 是否已经覆盖所有场景
> 2. 如果没有覆盖所有场景，是否留出足够的扩展方便用户自定义行为
> 3. 如果没有留出足够的扩展，那是不是在 sct 层面留出 SPI 用于用户的自定义 ready 能力
> 
> #### 2. SPI 扩展能力
> 我们是否可以定义 SPI，例如 `RegistryReadiness#isReady`，然后提供一些默认实现，例如
> 
> 1. DelayRegistryReadiness 。@weihubeats 所说，大部分情况下，可能延迟个一段时间就能满足需求了。那我们提供一个 DelayRegistryReadiness 实现类，用户如果使用这种机制，那就实例化一个bean，然后搞个配置项，定义延迟时间。
> 2. 用户自定义的 RegistryReadiness
> 3. ...
> 
> 当用户注入所有的 RegistryReadiness 都 ready 之后，再向注册中心发起情况。
> 
> #### 3. 兜底保护机制
> 是否提供兜底机制，因为用户扩展的 SPI 由于某些可能导致永远注册不上去，这时候如果应用全量发布了，会导致整体服务不可用，这个很危险。所以是否可以定义一个时间，比如1分钟，如果还没有全部ready，也会注册上去。当然这个行为可以让用户选择，例如 SPI 提供一个#是否可选#的一个接口，如果可选的话在 deadline 到了之后，可以忽略。如果是强制的话，则即使到了 deadline 也不注册。
> 
> ### 服务优雅下线
> 服务下线思路应该是跟服务上线基本上差不多。就像 @cheese8 说的。
> 
> > 服务治理中心提供DeRegistration接口
> > 服务提供者addJvmShutdownHook/ContextCloseEvent事件，先解注册服务注册中心，后根据自身执行情况，做一定的延时后下线。
> > 服务提供者根据自身情况，实现DeRegistration接口，在该接口实现中，先解注册服务注册中心，后根据自身执行情况，做一定的延时后下线。
> 
> 我们可以定义一个 SPI，然后提供一些默认实现以及用户自定义实现。
> 
> 1. 像延迟这种场景，我们内置 DelayXXX 实现，方便用户快速使用。
> 2. 针对流量这一块，是不是可以搞一个 TrafficXXX 实现，实现原理是在 Filter里搞一个计数器，统计进来的请求以及响应的请求。如果请求都响应完了，就认为已经ok了。
> 
> SPI 是核心，当所有SPI实现类都 ok 了才下线。当前也需要提供兜底保护机制，例如1分钟内还没ok，就强制 shutdown。
> 
> ### 优先实现 Spring Cloud
> @cheese8 提到了非 Spring Cloud 的实现。我在想，我们是不是可以先实现 Spring Cloud 的场景。把这个路跑通了之后，再实现其它的场景，聚焦一点。
> 
> @cheese8 @weihubeats 有空一起看一下呢？方案定了咱就开搞~

好的，抱歉才看到，晚点整理一下。

**Comment by misselvexu** [comment]
@cheese8  

How's the mission going ?

**Comment by cheese8** [comment]
抱歉，上周略忙，下周可以PR。

优雅上线方案，帮忙review一下，多谢。 @misselvexu 

1. GracefulStartUpListener implements ApplicationListener<ApplicationReadyEvent>, Ordered
override the onApplicationEvent method, and call GracefulStartupReadinessChecker.check
感觉ApplicationStartedEvent应该也可以，但它since 2.0.0, ApplicationReadyEvent since 1.3.0适用更广。

2. GracefulStartupReadinessChecker with check method and default implementation
3. PolarisStartupReadinessChecker implement GracefulStartupReadinessChecker in the polaris way

**Comment by cheese8** [comment]
PolarisAutoServiceRegistration extends AbstractAutoServiceRegistration and register instance while WebServerInitializedEvent for now, we need to change it to ApplicationReadyEvent.
