### ISSUE TITLE
配置在nacos中的“spring.cloud.polaris.ratelimit.maxQueuingTime”未生效

### ISSUE THREAD

**Issue by yekaka** [Tencent/spring-cloud-tencent#246]
前提：springboot：2.3.4.RELEASE、 spring-cloud-starter-alibaba-nacos-config ：2.2.5.RELEASE
nacos配置的信息：spring.cloud.polaris.ratelimit.maxQueuingTime = 60000

RemoteAwareLeakyBucket(InitCriteria initCriteria, Configuration configuration) ..
这里没有拿到该配置数据；
配置在代码中“bootstrap.properties” 路径下可以。
nacos 的data Id: “application.properties”

**Comment by TomShiDi** [comment]
也许这个问题要去alibaba那边提

**Comment by SkyeBeFreeman** [comment]
ratelimit模块在`application.properties`内配置的场景没有支持，在1.6.0版本进行修复。
