### ISSUE TITLE
服务治理模块有做agent的想法吗

### ISSUE THREAD

**Issue by Qsir-Q** [Tencent/spring-cloud-tencent#248]
SpringCloud的动态路由，灰度发布，标签路由，限流熔断等功能腾讯的大佬们有开发agent的计划吗，有的话可以带带我，我给各位大佬打下手

**Comment by chuntaojun** [comment]
可以看下 polaris-java-agent：https://github.com/polarismesh/polaris-java-agent

**Comment by andrewshan** [comment]
欢迎参与polaris-java-agent的建设，polaris-java-agent可以集成sct的能力，给用户无侵入的服务治理体验

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris-java-agent/tree/spring-cloud-2021

目前的开发分支
