### ISSUE TITLE
感觉会火

### ISSUE THREAD

**Issue by Jack9610** [Tencent/spring-cloud-tencent#249]
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by SkyeBeFreeman** [comment]
感谢支持~希望能看到您的使用或贡献哦^ ^

**Comment by lepdou** [comment]
@Jack9610 
感谢您的支持~

**Comment by ryanxys** [comment]
火钳刘明

**Comment by wetsion** [comment]
火钳留名

**Comment by ziven-ng** [comment]
大致看了一眼，比某baba 整洁干净，如果更新的快，准备换java 17的时候切过来。

**Comment by misselvexu** [comment]
> 大致看了一眼，比某baba 整洁干净，如果更新的快，准备换java 17的时候切过来。

We will keep pace with the release progress of spring boot and cloud communities in the future，welcome attention～

**Comment by misselvexu** [comment]
> > > 大致看了一眼，比某baba 整洁干净，如果更新的快，准备换java 17的时候切过来。
> > 
> > We will keep pace with the release progress of spring boot and cloud communities in the future，welcome attention～
> 
> 我给某baba贡献过代码，其实某baba源码还算是可以的了，因为它们代码规范插件要求很严格，比如说你导包多个空行，顺序没按要求等等它都不会给你通过的。你感觉它们不太好的原因可能是他们的代码贡献者比较多，然后水平也层次不齐，编码思维逻辑多样，这些确实是没有办法的，开源项目参与的人多了，就很难做到代码风格统一了

Learn from excellent people and projects，just do what you like to do！

Join us～

**Comment by DCloudCoder** [comment]
支持一波 火钳刘明

**Comment by zxy1994** [comment]
支持一波 火钳刘明

**Comment by lngg057** [comment]
BAT还差一个B了~
期待
<br /><br /><br /><br /><br /><br />
~~spring-cloud-bilibili(并不)~~

**Comment by lepdou** [comment]
> > > 大致看了一眼，比某baba 整洁干净，如果更新的快，准备换java 17的时候切过来。
> > 
> > 
> > We will keep pace with the release progress of spring boot and cloud communities in the future，welcome attention～
> 
> 我给某baba贡献过代码，其实某baba源码还算是可以的了，因为它们代码规范插件要求很严格，比如说你导包多个空行，顺序没按要求等等它都不会给你通过的。你感觉它们不太好的原因可能是他们的代码贡献者比较多，然后水平也层次不齐，编码思维逻辑多样，这些确实是没有办法的，开源项目参与的人多了，就很难做到代码风格统一了

@Jack9610 
我个人觉得你说的非常客观。

我之前也做过 Apollo，确实如你所说，当一个开源项目用的人多了，外部贡献者足够多了的情况下，很容易会导致这种情况。其实公司内部的项目也是如此，很难避免。如果 PR 卡的特别严，也会导致 PR 效率低，降低贡献者积极性等问题。做到一个好的权衡还是挺难的，需要有人能够持续投入精力把控质量。

**Comment by mroccyen** [comment]
默默支持一波

**Comment by youngledo** [comment]
Java生态就是有意思，各自不服各种造轮子。。

接下来欢迎“Spring Cloud XXX”来造轮子

**Comment by wave-gbt** [comment]
> Java生态就是有意思，各自不服各种造轮子。。
> 
> 接下来欢迎“Spring Cloud XXX”来造轮子

@youngledo 
确实是这样，基于老外的东西，自己改改就能冠名，顺便提高社区影响力。
一遍说不要重复造轮子，一遍大家都爱用各自的轮子

**Comment by tnessn** [comment]
有意思 可以跟spring cloud alibaba一较高下了

**Comment by pengzexuan2001** [comment]
围观
（PS：不过Tencent入场还是略微有些晚的，相较于Alibaba没有先发优势了😂）

**Comment by misselvexu** [comment]
> 围观
> （PS：不过Tencent入场还是略微有些晚的，相较于Alibaba没有先发优势了😂）

A good meal is never too late.🤨

**Comment by zhaozw** [comment]
> BAT还差一个B了~ 期待 ~spring-cloud-bilibili(并不)~

可以是HAT，spring cloud huaxxx，lol

**Comment by tnessn** [comment]
其实spring cloud alibaba 那套还很不完善，有些功能还不给开源，非得用他们的云产品。spring cloud tencent机会很大

**Comment by parzulpan** [comment]
火钳刘明~持续关注中

**Comment by Jansora** [comment]
> We will keep pace with the release progress of spring boot and cloud communities in the future，welcome attention～



> > Java生态就是有意思，各自不服各种造轮子。。
> > 接下来欢迎“Spring Cloud XXX”来造轮子
> 
> @youngledo 确实是这样，基于老外的东西，自己改改就能冠名，顺便提高社区影响力。 一遍说不要重复造轮子，一遍大家都爱用各自的轮子

虽然你说的是事实, 但在 spring 生态估计外先发优势的情况下, 落后只能先追赶, 目前最高效的做法就是先模仿, 提高自己的社区影响力之后, 再能发布新的技术标准, 才会有更多人愿意追随, 只有更多人追随了, 技术标准才能真正变成事实标准, google, facebook, airbnb 都是这样

**Comment by zhaojiaiqing** [comment]
点个start支持一波儿～
