### ISSUE TITLE
[Discuss] How about suppress the ImportOrder check?

### ISSUE THREAD

**Issue by cheese8** [Tencent/spring-cloud-tencent#252]
**Describe the discuss** 
1、Checkstyle checks the `ImportOrder` for now.
2、Not found the community  document which shows the correct import order should be.
3、Is it too strict or not to check the import order?

@SkyeBeFreeman

**Comment by SkyeBeFreeman** [comment]
You can check the code style standard created by Spring Cloud Team here [参与共建](https://github.com/Tencent/spring-cloud-tencent/wiki/参与共建#代码规范).
