### ISSUE TITLE
配置数据读取顺序问题

### ISSUE THREAD

**Issue by Paul101432** [Tencent/spring-cloud-tencent#260]
**Describe the bug**
只配置自定义文件  加载异常

**Expected behavior**
这里没有忽悠默认配置,导致一直加载不存在的文件 

**Environment**
- Version: [1.5.2-2020.0.5] 

![image](https://user-images.githubusercontent.com/12791233/174560439-b4893749-927a-41a3-9a4f-499e35c2afda.png)

**Comment by lepdou** [comment]
@Paul101432 
非常感谢给我们提 bug。我尝试理解一下你描述的 bug：
你的意思是配置了自定义文件之后，会去加载 application.yml 之类的内置配置文件。但是由于在北极星服务端没有添加 application.yml 导致一直加载不存在的配置文件？
--------
如果是上面我理解的话，这个是符合预期的。

因为客户端侧不管服务端有没有配置内置配置文件，都会去获取 application.yml 这些配置文件。如果没有加载到的话，也会向服务端订阅这些内置配置文件。这样的话，当动态的在北极星服务端添加了 application.yml 之后，客户端不用重启就能动态的获取到 application.yml 里面的配置。

-------
或者你这边有没有更好的方案可以参考一下？

**Comment by lepdou** [comment]
@Paul101432 

这段代码确实有一个bug，那就是如果不配置自定义的配置文件的话，就不会加载 application.yml 内置的配置文件。这部分已经在 1.6.0 版本里修复了，还没有发布。

````java
@Override
	public PropertySource<?> locate(Environment environment) {
		CompositePropertySource compositePropertySource = new CompositePropertySource(
				POLARIS_CONFIG_PROPERTY_SOURCE_NAME);

		// load spring boot default config files
		initInternalConfigFiles(compositePropertySource);

		// load custom config files
		List<ConfigFileGroup> configFileGroups = polarisConfigProperties.getGroups();
		if (CollectionUtils.isEmpty(configFileGroups)) {
			return compositePropertySource;
		}
		initCustomPolarisConfigFiles(compositePropertySource, configFileGroups);

		return compositePropertySource;
	}
````
