### ISSUE TITLE
熔断示例文档引入包名错误

### ISSUE THREAD

**Issue by vinartis** [Tencent/spring-cloud-tencent#267]
如下图所示
![image](https://user-images.githubusercontent.com/4651907/174708676-d24e1f0d-7d41-40cb-bdd1-0e39f9db702e.png)

正确的包名是
`    
<dependency>
<groupId>com.tencent.cloud</groupId>
 <artifactId>spring-cloud-starter-tencent-polaris-circuitbreaker</artifactId>
</dependency>
`

**Comment by SkyeBeFreeman** [comment]
已修复，感谢反馈。
