### ISSUE TITLE
咱们腾讯的这套框架有什么特色呢

### ISSUE THREAD

**Issue by zhuzhuxiaSoft** [Tencent/spring-cloud-tencent#274]
相比其他公司的方案具体有什么优劣势呢

PS：快卷不起了，估计又是一阵血雨腥风

**Comment by cheese8** [comment]
最好既能支持自己tencent cloud产品外，也能相对中立，支持下其他产品接入。

**Comment by lepdou** [comment]
> 最好既能支持自己tencent cloud产品外，也能相对中立，支持下其他产品接入。

嗯，这个我们是有计划的。
因为 Spring Boot 、Spring Cloud 最大的优势就在于 starter 组件化，各个功能独立。所以我们有考虑过混用的场景，比如注册中心用 Zookeeper、Nacos、路由用 SCT这种混用的场景。给用户最大的自由度去选择组件，而不是把用户就绑定死在 SCT 整个套件上，这也背离了 Spring Cloud 的理念。

**Comment by zhuzhuxiaSoft** [comment]
thank u for all replies

**Comment by zhuzhuxiaSoft** [comment]
thank u for all replies
