### ISSUE TITLE
spring.cloud.polaris.ratelimit.rejectRequestTips 不支持中文

### ISSUE THREAD

**Issue by liuyd-cc** [Tencent/spring-cloud-tencent#278]
QuotaCheckServletFilter：
```
	if (quotaResponse.getCode() == QuotaResultCode.QuotaResultLimited) {
		response.setStatus(polarisRateLimitProperties.getRejectHttpCode());
		response.getWriter().write(rejectTips);
		return;
	}
```

此时如果 rejectTips 是中文，直接返回给浏览器是乱码，不知道官方是否考虑支持中文正确返回？

**Comment by shouyuwang** [comment]
> 这个场景确实需要支持，看您这边是否有精力一起贡献下呢？


Please assign this issue to me

**Comment by liuyd-cc** [comment]
昨天下班回家了，今天来公司一看已经解决了，代码拉下来之后，看了看使用的是

**Comment by SkyeBeFreeman** [comment]
> 昨天下班回家了，今天来公司一看已经解决了，代码拉下来之后，看了看使用的是 `response.setContentType("text/plain;charset=UTF-8");`
> 
> 想了下，限流是提供 rejectRequestTips 和 rejectRequestTipsFilePath 两种形式
> 
> 并且 **rejectRequestTipsFilePath常用于返回html**
> 
> 那使用 text/plain;charset=UTF-8 将会按照文本返回到浏览器，好像不太合适 如果换成 text/html;charset=UTF-8，rejectRequestTips 将也允许配置html，例如：`<h1>服务不可达</h1>`
> 
> 这个主要看官方如何考虑？ @SkyeBeFreeman

有道理，这里应该做一个判断，限流文案返回文字和HTML应该设置不同的ContentType。 同时，`QuotaCheckReactiveFilter`也需要实现。@cheese8 这边是否能继续实现呢？

**Comment by shouyuwang** [comment]
> > 昨天下班回家了，今天来公司一看已经解决了，代码拉下来之后，看了看使用的是 `response.setContentType("text/plain;charset=UTF-8");`
> > 想了下，限流是提供 rejectRequestTips 和 rejectRequestTipsFilePath 两种形式
> > 并且 **rejectRequestTipsFilePath常用于返回html**
> > 那使用 text/plain;charset=UTF-8 将会按照文本返回到浏览器，好像不太合适 如果换成 text/html;charset=UTF-8，rejectRequestTips 将也允许配置html，例如：`<h1>服务不可达</h1>`
> > 这个主要看官方如何考虑？ @SkyeBeFreeman
> 
> 有道理，这里应该做一个判断，限流文案返回文字和HTML应该设置不同的ContentType。 同时，`QuotaCheckReactiveFilter`也需要实现。@cheese8 这边是否能继续实现呢？

是不是可以考虑抛出异常，让用户自己去捕获异常，返回自定义错误消息。

**Comment by SkyeBeFreeman** [comment]
> > > 昨天下班回家了，今天来公司一看已经解决了，代码拉下来之后，看了看使用的是 `response.setContentType("text/plain;charset=UTF-8");`
> > > 想了下，限流是提供 rejectRequestTips 和 rejectRequestTipsFilePath 两种形式
> > > 并且 **rejectRequestTipsFilePath常用于返回html**
> > > 那使用 text/plain;charset=UTF-8 将会按照文本返回到浏览器，好像不太合适 如果换成 text/html;charset=UTF-8，rejectRequestTips 将也允许配置html，例如：`<h1>服务不可达</h1>`
> > > 这个主要看官方如何考虑？ @SkyeBeFreeman
> > 
> > 
> > 有道理，这里应该做一个判断，限流文案返回文字和HTML应该设置不同的ContentType。 同时，`QuotaCheckReactiveFilter`也需要实现。@cheese8 这边是否能继续实现呢？
> 
> 是不是可以考虑抛出异常，让用户自己去捕获异常，返回自定义错误消息。

限流这里给出了自定义限流信息，目前的想法是尽量在限流模块内闭环，而不是抛出去让开发者解决。

**Comment by cheese8** [comment]
> > 昨天下班回家了，今天来公司一看已经解决了，代码拉下来之后，看了看使用的是 `response.setContentType("text/plain;charset=UTF-8");`
> > 想了下，限流是提供 rejectRequestTips 和 rejectRequestTipsFilePath 两种形式
> > 并且 **rejectRequestTipsFilePath常用于返回html**
> > 那使用 text/plain;charset=UTF-8 将会按照文本返回到浏览器，好像不太合适 如果换成 text/html;charset=UTF-8，rejectRequestTips 将也允许配置html，例如：`<h1>服务不可达</h1>`
> > 这个主要看官方如何考虑？ @SkyeBeFreeman
> 
> 有道理，这里应该做一个判断，限流文案返回文字和HTML应该设置不同的ContentType。 同时，`QuotaCheckReactiveFilter`也需要实现。@cheese8 这边是否能继续实现呢？

有道理，好的

**Comment by dousp** [comment]
> > > > 昨天下班回家了，今天来公司一看已经解决了，代码拉下来之后，看了看使用的是 `response.setContentType("text/plain;charset=UTF-8");`
> > > > 想了下，限流是提供 rejectRequestTips 和 rejectRequestTipsFilePath 两种形式
> > > > 并且 **rejectRequestTipsFilePath常用于返回html**
> > > > 那使用 text/plain;charset=UTF-8 将会按照文本返回到浏览器，好像不太合适 如果换成 text/html;charset=UTF-8，rejectRequestTips 将也允许配置html，例如：`<h1>服务不可达</h1>`
> > > > 这个主要看官方如何考虑？ @SkyeBeFreeman
> > > 
> > > 
> > > 有道理，这里应该做一个判断，限流文案返回文字和HTML应该设置不同的ContentType。 同时，`QuotaCheckReactiveFilter`也需要实现。@cheese8 这边是否能继续实现呢？
> > 
> > 
> > 是不是可以考虑抛出异常，让用户自己去捕获异常，返回自定义错误消息。
> 
> 限流这里给出了自定义限流信息，目前的想法是尽量在限流模块内闭环，而不是抛出去让开发者解决。

我有个疑问哈，开发中系统统一封装了返回结果（包括异常），所以开发者还是需要自己处理下这个限流信息的吧，若是能设置成自己规定的数据结构，还是蛮省心的。

**Comment by SkyeBeFreeman** [comment]
> > > > > 昨天下班回家了，今天来公司一看已经解决了，代码拉下来之后，看了看使用的是 `response.setContentType("text/plain;charset=UTF-8");`
> > > > > 想了下，限流是提供 rejectRequestTips 和 rejectRequestTipsFilePath 两种形式
> > > > > 并且 **rejectRequestTipsFilePath常用于返回html**
> > > > > 那使用 text/plain;charset=UTF-8 将会按照文本返回到浏览器，好像不太合适 如果换成 text/html;charset=UTF-8，rejectRequestTips 将也允许配置html，例如：`<h1>服务不可达</h1>`
> > > > > 这个主要看官方如何考虑？ @SkyeBeFreeman
> > > > 
> > > > 
> > > > 有道理，这里应该做一个判断，限流文案返回文字和HTML应该设置不同的ContentType。 同时，`QuotaCheckReactiveFilter`也需要实现。@cheese8 这边是否能继续实现呢？
> > > 
> > > 
> > > 是不是可以考虑抛出异常，让用户自己去捕获异常，返回自定义错误消息。
> > 
> > 
> > 限流这里给出了自定义限流信息，目前的想法是尽量在限流模块内闭环，而不是抛出去让开发者解决。
> 
> 我有个疑问哈，开发中系统统一封装了返回结果（包括异常），所以开发者还是需要自己处理下这个限流信息的吧，若是能设置成自己规定的数据结构，还是蛮省心的。

目前主要是提供的静态限流提示，你这边提及的应该是需要一个可以动态渲染的限流提示？

**Comment by dousp** [comment]
大概就是提供一个fallback，然后返回开发者自定义要返回的信息吧
另外，北极星上的限流（熔断）监控界面数据怎么来的？需要做什么配置？我正在使用SCT版本是：1.6.0-2021.0.3

**Comment by SkyeBeFreeman** [comment]
> 大概就是提供一个fallback，然后返回开发者自定义要返回的信息吧

可以单独提一个Issue出来，看看是否有意愿贡献这里相关代码。

**Comment by SkyeBeFreeman** [comment]
> 另外，北极星上的限流（熔断）监控界面数据怎么来的？需要做什么配置？我正在使用SCT版本是：1.6.0-2021.0.3

配置好上传监控数据的相关配置即可，[配置文档](https://github.com/Tencent/spring-cloud-tencent/wiki/RPC%E5%A2%9E%E5%BC%BA#%E6%8C%87%E6%A0%87%E7%9B%91%E6%8E%A7%E6%8F%92%E4%BB%B6)。在触发限流或者熔断时，即可上报。

**Comment by dousp** [comment]
> 触发限流或者熔断时，即可上报。

1.6.0-2021.0.3   这个版本好像不支持这个插件呢，只能等1.7了。目前SCT没看到有1.7这个分支。。。

**Comment by SkyeBeFreeman** [comment]
> > 触发限流或者熔断时，即可上报。
> 
> 1.6.0-2021.0.3 这个版本好像不支持这个插件呢，只能等1.7了。目前SCT没看到有1.7这个分支。。。

是的，2020和2021版本还在开发中~
