### ISSUE TITLE
How to modify the default namespace of service using Polaris SDK

### ISSUE THREAD

**Issue by yangjuanying** [Tencent/spring-cloud-tencent#29]
I can use configuration with "spring.cloud.polaris.address=grpc://127.0.0.1:8091" to specify Polaris registry address And "spring.application.name=xxx" to specify registry service，but I don't know how to modify the default namespace of the service？

**Comment by SkyeBeFreeman** [comment]
Using `spring.cloud.polaris.discovery.namespace` in application.yml to set namespace. I will append this in the document later.
