### ISSUE TITLE
metadata-transfer中传递覆盖问题

### ISSUE THREAD

**Issue by shouyuwang** [Tencent/spring-cloud-tencent#293]
A服务和B服务中进行设置了参数`data`进行传递，A服务中`data`=10，B服务中`data`=100。当A服务调用B服务的时候，B服务的`data`是否要进行覆盖？

**Comment by shouyuwang** [comment]
> A服务的data会覆盖B服务的data。

那如果下游还有链路的话，不就会一直以第一个服务的传递为准了？这样的话，如果想通过上游传递的参数作为判断条件，在被覆盖的情况下是有可能判断错误的呢？

**Comment by SkyeBeFreeman** [comment]
> > > > A服务的data会覆盖B服务的data。
> > > 
> > > 
> > > 那如果下游还有链路的话，不就会一直以第一个服务的传递为准了？这样的话，如果想通过上游传递的参数作为判断条件，在被覆盖的情况下是有可能判断错误的呢？
> > 
> > 
> > 这里最开始的推荐使用方式是将某个参数在链路上一直传递下去。如果想依赖上一个服务的参数，设置不同键的键值对即可。你也可以给出一个实际场景，我们可以深入讨论下可能的实现。
> 
> 那我可以理解为transfer更适合做的场景是类似于TraceId的传递这种的？ 比如说A、B、C三个服务，B是代理服务，A可以直接调用C服务，也可以是A通过调用B去调用C，这样的话代理服务的头传递信息不就失效了么。

transfer目前仅做元数据传递，而调用链的场景相对复杂。比如traceid是需要一直往下游传递，这个不会变，而spanid则需要保存上游的并生成本spanid，然后再把本spanid传到下游。链路追踪的场景可以作为一个单独的场景考虑。

**Comment by SkyeBeFreeman** [comment]
我们将在 #296 讨论这个场景。

**Comment by SkyeBeFreeman** [comment]
@shouyuwang 这里会添加一个单跳传递的场景，即只传递到下游，而不传递到下下游之后。
