### ISSUE TITLE
MetadataTransferAutoConfiguration should not mark @ Configuration

### ISSUE THREAD

**Issue by tofdragon** [Tencent/spring-cloud-tencent#298]
https://github.com/Tencent/spring-cloud-tencent/blob/cbed6df22a14cb0f37294c4086fc0d9fca977dc7/spring-cloud-starter-tencent-metadata-transfer/src/main/java/com/tencent/cloud/metadata/config/MetadataTransferAutoConfiguration.java#L58

MetadataTransferAutoConfiguration has been added to spring.factories config file，so MetadataTransferAutoConfiguration should not mark @ Configuration

**Comment by lepdou** [comment]
@tofdragon 
Firstly thank you for your suggestion. We will optimzie it.

**Comment by SkyeBeFreeman** [comment]
@tofdragon Configuration defined in spring.factories should also be marked `@Configuration`. Or it will do not work.

**Comment by quicksandznzn** [comment]
Maybe Use @Configuration(proxyBeanMethods = false)  would  be better
