### ISSUE TITLE
Polaris is not flexible and extensible enough to set metadata，I hope it can be set metadata through code

### ISSUE THREAD

**Issue by yangjuanying** [Tencent/spring-cloud-tencent#31]
Polaris is not flexible and extensible enough to set metadata here. This only through configuration “spring cloud.tencent.metadata” to set metadata. It is impossible to set metadata through code.
<img width="1181" alt="wecom-temp-8c5546bddccf659393ced1df2725525c" src="https://user-images.githubusercontent.com/7542593/148729742-2c396a1d-15c8-4363-b64a-1dee943ccd52.png">

But Spring Cloud Consul and Nacos are flexible in this regard. For example, there is a customize method in the registration method of ConsulAutoRegistration
<img width="1342" alt="wecom-temp-25ae223f8f166e2367f90031e8b0dc6c" src="https://user-images.githubusercontent.com/7542593/148730194-4a36cca3-ff5e-4e2a-a9e8-8d098fcf1bc8.png">

The user can implement the interface ConsulRegistrationCustomizer and put the customized metadata in the implementation class through code
![image](https://user-images.githubusercontent.com/7542593/148731578-620597b0-9d7f-48bb-a2e0-c2c897ae26a8.png)

It is suggested that Polaris should be modified like this in Class PolarisServiceRegistry.

**Comment by chuntaojun** [comment]
Okay, let's think about it here, and welcome to participate in the co-construction together to provide support for this ability~

**Comment by chuntaojun** [comment]
@SkyeBeFreeman what do you think

**Comment by SkyeBeFreeman** [comment]
It is a good idea to customize the metadata with code. I will add this enhancement later.

**Comment by lepdou** [comment]
@yangjuanying 
I have add an SPI InstanceMetadataProvider in #244
