### ISSUE TITLE
能发布对应的Spring boot版本号关系么？

### ISSUE THREAD

**Issue by myNameZhulu** [Tencent/spring-cloud-tencent#310]
能发布对应的Spring boot版本号关系么？在尝试使用过程中无法确定使用哪个Spring boot版本与[spring-cloud-tencent](https://github.com/Tencent/spring-cloud-tencent)进行依赖

**Comment by SkyeBeFreeman** [comment]
@myNameZhulu 可以看看这篇文档，[版本管理](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-版本管理)。

**Comment by myNameZhulu** [comment]
谢谢 后来已经找到了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haotian ***@***.***&gt;; 
发送时间: 2022年7月5日(星期二) 中午11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/spring-cloud-tencent] 能发布对应的Spring boot版本号关系么？ (Issue #310)





 
已完成关闭#310。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
你收到这个是因为你被提到了。消息ID：<Tencent/spring-cloud-tencent/issue/310/issue_event/6931015063 @ github 。com&gt;
