### ISSUE TITLE
format constants UTF-8

### ISSUE THREAD

**Issue by weihubeats** [Tencent/spring-cloud-tencent#312]
**What is the feature you want to add?**
Use jdk constants instead of magic variables
**Why do you want to add this feature?**
Use jdk constants instead of magic variables
**How to implement this feature?**
Use jdk constants instead of magic variables
**Additional context**
![image](https://user-images.githubusercontent.com/42484192/175768750-7ff3ea4f-a0ae-4f46-af69-92491ac351b1.png)

**Comment by lepdou** [comment]
Resolved with #313 .

@weihubeats 
Thank you for you pr~
