### ISSUE TITLE
优化配置中心动态刷新的机制

### ISSUE THREAD

**Issue by lepdou** [Tencent/spring-cloud-tencent#314]
**What is the feature you want to add?**
Spring Cloud 官方实现是通过 @RefreshScope 实现动态刷新，在配置刷新时，会重建 Bean。
这种方式有两个弊端：
1. 开发阶段需要加 @RefreshScope
2. 刷新时会重建 Bean，影响面大。老版本会重建整个 Context

参考其它配置中心实现，Apollo 是通过反射的机制，动态更新 @Value 的属性值。这种方式能够比较好的解决优化两个问题。

**Why do you want to add this feature?**

**How to implement this feature?**

通过反射机制实现属性动态刷新

**Additional context**

**Comment by weihubeats** [comment]
can i try this issues

**Comment by lepdou** [comment]
@weihubeats 

Thank you~

You can reference to apollo-client implement. [apollo-client](https://github.com/apolloconfig/apollo/tree/master/apollo-client)

**Comment by SkyeBeFreeman** [comment]
@weihubeats you can reopen the PR.

**Comment by weihubeats** [comment]
ok

**Comment by liqi19950722** [comment]
Note that actual processing of the @Value annotation is performed by a BeanPostProcessor which in turn means that you cannot use @Value within BeanPostProcessor or BeanFactoryPostProcessor types. Please consult the javadoc for the AutowiredAnnotationBeanPostProcessor class (which, by default, checks for the presence of this annotation).
