### ISSUE TITLE
拉取Demo 提示Unresolved dependency: 'ch.qos.logback:logback-core:jar:1.2.11'

### ISSUE THREAD

**Issue by clstech** [Tencent/spring-cloud-tencent#323]
git最新master仓库，maven后提示 Unresolved dependency: 'ch.qos.logback:logback-core:jar:1.2.11'

**Comment by misselvexu** [comment]
Please check your maven `settings.xml` file first , maven mirrors repository address is recommended ,

**Comment by pandaapo** [comment]
> git最新master仓库，maven后提示 Unresolved dependency: 'ch.qos.logback:logback-core:jar:1.2.11'

这种个性问题，一般是网络问题导致依赖没下载完整（删除本地maven中下载的文件，重新下载），或者配置镜像地址有问题（检查下，我用的是aliyun镜像）。
