### ISSUE TITLE
有没有可能构建微服务集群内 TencentHashMap,TencentHashSet,TencentList对象

### ISSUE THREAD

**Issue by GuoRanYiMao** [Tencent/spring-cloud-tencent#339]
有没有可能构建微服务集群内 TencentHashMap,TencentHashSet,TencentList对象。
让研发像使用java容器一样通过简单创建静态成员变量直接使用。屏蔽集群共识复杂度，用起来会不会很爽。
首先要约束使用场景，明确线程是否安全，通过北极星找到找到当前服务集群。
集群内通过类似Jraft算法独立实现数据一致性。

最终期望的效果是
@Service
public class DemoService {
    //研发无感声明集群内同步缓存块
    public static TencentHashMap<String,Object> TEMP_MAP; 
}

**Comment by misselvexu** [comment]
@GuoRanYiMao 

Redis is perfectly suited to your scenario ，why not use Redis directly ?

Also ,
From a practical point of view, the Polaris registry belongs to the `AP`, which guarantees availability, distributed storage, and requires the consensus algorithm of the `CP` 。

**Comment by GuoRanYiMao** [comment]
> @GuoRanYiMao
> 
> Redis is perfectly suited to your scenario ，why not use Redis directly ?
> 
> Also , From a practical point of view, the Polaris registry belongs to the `AP`, which guarantees availability, distributed storage, and requires the consensus algorithm of the `CP` 。

只是讨论啊。 redis是可以这样，但终究是需要引入提高复杂度。研发还是有感知的。
我可能没有表述清楚，同步缓存模块不依赖北极星，只需要北极星告诉我当前servername 的集群都有哪些节点，同步这件事交给springcloudtencent框架自己来消化，也就是参与分布式共识算法的节点不包含北极星，只有业务集群自己讨论。

另外，如果真的可以实现，研发在特定场景下，public static TencentHashMap<String,Object> TEMP_MAP; 这方式会不会体验好一些。

**Comment by cheese8** [comment]
Could the Hazelcast distributed map suited to your scenario?

**Comment by GuoRanYiMao** [comment]
> Could the Hazelcast distributed map suited to your scenario?

看了一下 Hazelast 感觉完美覆盖了需求
