### ISSUE TITLE
容器关闭前未关闭线程池

### ISSUE THREAD

**Issue by DerekYRC** [Tencent/spring-cloud-tencent#352]
**Describe the bug**

Did not shutdown the thread pool before the spring container closes.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

Shutdown the thread pool before the spring container closes.

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**
![63d1fd6eea898fc202a55294bf56e3e](https://user-images.githubusercontent.com/44155264/176455953-4720b8b0-48ca-4461-8d68-52bbc853bd86.png)

**Comment by SkyeBeFreeman** [comment]
Thx for contributing~
