### ISSUE TITLE
Refator JacksonUtils and JacksonUtilsTest

### ISSUE THREAD

**Issue by cheese8** [Tencent/spring-cloud-tencent#364]
**Why do you want to add this feature?**
1. remove the redundant logic of LOG in JacksonUtils.
2. refactor using assertThrows instead of try catch fail.

@SkyeBeFreeman

**Comment by SkyeBeFreeman** [comment]
@cheese8 
1. Why do you want to remove the LOG output in `JacksonUtils`?
2. You should use `AssertJ` to implement Junit test.

**Comment by cheese8** [comment]
> @cheese8
> 
> 1. Why do you want to remove the LOG output in `JacksonUtils`?
> 2. You should use `AssertJ` to implement Junit test.

@SkyeBeFreeman 
That was already rethrown as runtime exception and with the almost  message, i think it's redundant. What do you think?

**Comment by SkyeBeFreeman** [comment]
> > @cheese8
> > 
> > 1. Why do you want to remove the LOG output in `JacksonUtils`?
> > 2. You should use `AssertJ` to implement Junit test.
> 
> @SkyeBeFreeman
> 
> 1. That was already rethrown as runtime exception and with the almost  message, i think it's redundant.
> 2. It's a utility class.
> 
> What do you think?

1. If runtime exception happened in a thread and is not catched by upper, it may lose the error log.
2. Your new modification is ok.

**Comment by cheese8** [comment]
> > > @cheese8
> > > 
> > > 1. Why do you want to remove the LOG output in `JacksonUtils`?
> > > 2. You should use `AssertJ` to implement Junit test.
> > 
> > 
> > @SkyeBeFreeman
> > 
> > 1. That was already rethrown as runtime exception and with the almost  message, i think it's redundant.
> > 2. It's a utility class.
> > 
> > What do you think?
> 
> 1. If runtime exception happened in a thread and is not catched by upper, it may lose the error log.
> 2. Your new modification is ok.

oh yes, i missed this, how about throw runtime exception on the method signature ?

**Comment by SkyeBeFreeman** [comment]
> > > > @cheese8
> > > > 
> > > > 1. Why do you want to remove the LOG output in `JacksonUtils`?
> > > > 2. You should use `AssertJ` to implement Junit test.
> > > 
> > > 
> > > @SkyeBeFreeman
> > > 
> > > 1. That was already rethrown as runtime exception and with the almost  message, i think it's redundant.
> > > 2. It's a utility class.
> > > 
> > > What do you think?
> > 
> > 
> > 
> > 1. If runtime exception happened in a thread and is not catched by upper, it may lose the error log.
> > 2. Your new modification is ok.
> 
> oh yes, i missed this, how about throw runtime exception on the method signature ?

It is no need to catch `RuntimeException`, even if you write in the method signature.

**Comment by cheese8** [comment]
yeah, ok, JacksonUtils  reverted.
