### ISSUE TITLE
后续有没有开发分布式事务组件的计划？

### ISSUE THREAD

**Issue by coderzcr** [Tencent/spring-cloud-tencent#377]
目前阿里seata不支持tencent的配置中心和注册中心，不知后续是否有计划

**Comment by ranchowang** [comment]
腾讯内部的分布式事务组件还没有开源时间表

seata支持polaris作为注册配置中心，可以考虑从两个方向推进：
1. 和seata社区探讨支持polaris的可行性
2. polaris兼容eureka等其他注册配置中心的协议接入：
https://github.com/polarismesh/polaris/tree/main/apiserver

**Comment by misselvexu** [comment]
Follow the PR of Seata community, 

[Seata-PR # support tencent polaris discovery](https://github.com/seata/seata/pull/4894)
