### ISSUE TITLE
Hoxton版Zuul支持网关路由

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#384]
**What is the feature you want to add?**

在Hoxton版Zuul实现网关路由逻辑。

**Why do you want to add this feature?**

在Zuul的使用可以支持北极星路由功能。

**How to implement this feature?**

参考SCG中 `com.tencent.cloud.polaris.router.scg.PolarisLoadBalancerClientFilter` 的实现。而Zuul最终生效的路由应该在 `com.tencent.cloud.polaris.router.PolarisLoadBalancerCompositeRule#choose` 这个方法。

**Additional context**

No.

**Comment by DerekYRC** [comment]
@SkyeBeFreeman 我理解，可以在PreDecorationFilter之前增加一个ZuulFilter过滤器，该过滤器执行路由逻辑选择服务实例，然后将路由结果放进请求上下文RequestContext。

**Comment by DerekYRC** [comment]
@SkyeBeFreeman 我理解，可以在PreDecorationFilter之前增加一个ZuulFilter过滤器，该过滤器执行路由逻辑选择服务实例，然后将路由结果放进请求上下文RequestContext。

不知道理解对不对？

**Comment by SkyeBeFreeman** [comment]
> @SkyeBeFreeman 我理解，可以在PreDecorationFilter之前增加一个ZuulFilter过滤器，该过滤器执行路由逻辑选择服务实例，然后将路由结果放进请求上下文RequestContext。
> 
> 不知道理解对不对？

这种方法确实可以实现，不过如果能按照原生的Rule来实现更好。普通微服务是将标签信息放在`com.tencent.cloud.polaris.router.PolarisLoadBalancerCompositeRule#choose`这个方法的入参`key`中，而Zuul目前没有将相关路由标签数据放在`choose`方法的入参，因此找到方法填入这个参数，即可完成Zuul的服务路由实现。

**Comment by qinxiongzhou** [comment]
认领下
