### ISSUE TITLE
配置中心支持Spring Cloud新配置方式

### ISSUE THREAD

**Issue by lingxiao-wu** [Tencent/spring-cloud-tencent#389]
**What is the feature you want to add?**
https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#config-first-bootstrap

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/51630311/177165300-838ed428-e862-40db-b7e8-1b1a72d4332b.png">
Spring cloud 2.4后续版本默认关闭了bootstrap功能，并且为配置中心提供了新的配置方式

**Why do you want to add this feature?**

**How to implement this feature?**
我还在研究配置中心相关代码，期待后续可以一起开发该功能
**Additional context**

**Comment by SkyeBeFreeman** [comment]
我最近也注意到配置中心这一块的新特性，欢迎您参与开源贡献。您可以直接在issue里给出您的方案或想法，并提交PR👏近期会先发布`1.6.0`版本，所以这一块您可以先开发，后续在`1.7.0`版本发布。

**Comment by lingxiao-wu** [comment]
> 我最近也注意到配置中心这一块的新特性，欢迎您参与开源贡献。您可以直接在issue里给出您的方案或想法，并提交PR👏近期会先发布`1.6.0`版本，所以这一块您可以先开发，后续在`1.7.0`版本发布。

我调研了一下，其实支持这个比较关键的是要实现`ConfigDataLocationResolver` `ConfigDataResource` `ConfigDataLoader`三个接口，`ConfigDataLocationResolver`可以将import：xxx后面的配置包装成`ConfigDataResource`,`ConfigDataLoader`会根据`ConfigDataResource`中的配置从配置中心拉取配置，并适配为`ConfigData`。
在实现的过程中发现的问题是在之前的版本SPT过于依赖Bootstrap容器，如果剔除掉Bootstrap容器支持，将直接影响`polarisContext`的加载，并且`ConfigDataLocationResolver` `ConfigDataResource` `ConfigDataLoader`的加载是通过`ConfigDataEnvironmentPostProcessor`,在此时Spring 容器还没有构建，`Environment`也还没有构建完成，所以支持这种配置首先要解决如何不依赖Bootstrap加载`polarisContext`，因为从目前来看，只有成功构建`polarisContext`，才能构建出拉取配置文件的`ConfigFileService`

**Comment by liqi19950722** [comment]
> > 我最近也注意到配置中心这一块的新特性，欢迎您参与开源贡献。您可以直接在issue里给出您的方案或想法，并提交PR👏近期会先发布`1.6.0`版本，所以这一块您可以先开发，后续在`1.7.0`版本发布。
> 
> 我调研了一下，其实支持这个比较关键的是要实现`ConfigDataLocationResolver` `ConfigDataResource` `ConfigDataLoader`三个接口，`ConfigDataLocationResolver`可以将import：xxx后面的配置包装成`ConfigDataResource`,`ConfigDataLoader`会根据`ConfigDataResource`中的配置从配置中心拉取配置，并适配为`ConfigData`。 在实现的过程中发现的问题是在之前的版本SPT过于依赖Bootstrap容器，如果剔除掉Bootstrap容器支持，将直接影响`polarisContext`的加载，并且`ConfigDataLocationResolver` `ConfigDataResource` `ConfigDataLoader`的加载是通过`ConfigDataEnvironmentPostProcessor`,在此时Spring 容器还没有构建，`Environment`也还没有构建完成，所以支持这种配置首先要解决如何不依赖Bootstrap加载`polarisContext`，因为从目前来看，只有成功构建`polarisContext`，才能构建出拉取配置文件的`ConfigFileService`

需要springboot 2.4.5以上
可以用
`org.springframework.boot.BootstrapRegistryInitializer` 提前往`org.springframework.boot.ConfigurableBootstrapContext` 中注册`PolarisConfigModifier` `PolarisContextProperties` 再利用`InstanceSupplier`延时构建`SDKContext`，最后`ConfigDataLoader`中获取`SDKContext`

`spring.factories`
```
org.springframework.boot.BootstrapRegistryInitializer=
\xxx类
```

**Comment by lingxiao-wu** [comment]
> > > 我最近也注意到配置中心这一块的新特性，欢迎您参与开源贡献。您可以直接在issue里给出您的方案或想法，并提交PR👏近期会先发布`1.6.0`版本，所以这一块您可以先开发，后续在`1.7.0`版本发布。
> > 
> > 
> > 我调研了一下，其实支持这个比较关键的是要实现`ConfigDataLocationResolver` `ConfigDataResource` `ConfigDataLoader`三个接口，`ConfigDataLocationResolver`可以将import：xxx后面的配置包装成`ConfigDataResource`,`ConfigDataLoader`会根据`ConfigDataResource`中的配置从配置中心拉取配置，并适配为`ConfigData`。 在实现的过程中发现的问题是在之前的版本SPT过于依赖Bootstrap容器，如果剔除掉Bootstrap容器支持，将直接影响`polarisContext`的加载，并且`ConfigDataLocationResolver` `ConfigDataResource` `ConfigDataLoader`的加载是通过`ConfigDataEnvironmentPostProcessor`,在此时Spring 容器还没有构建，`Environment`也还没有构建完成，所以支持这种配置首先要解决如何不依赖Bootstrap加载`polarisContext`，因为从目前来看，只有成功构建`polarisContext`，才能构建出拉取配置文件的`ConfigFileService`
> 
> 需要springboot 2.4.5以上 可以用 `org.springframework.boot.BootstrapRegistryInitializer` 提前往`org.springframework.boot.ConfigurableBootstrapContext` 中注册`PolarisConfigModifier` `PolarisContextProperties` 再利用`InstanceSupplier`延时构建`SDKContext`，最后`ConfigDataLoader`中获取`SDKContext`
> 
> `spring.factories`
> 
> ```
> org.springframework.boot.BootstrapRegistryInitializer=
> \xxx类
> ```
> 
> `PolarisConfigModifier` 这个的子类不是那么好构建的，有很多 这段代码能不能挪到 具体的`PolarisConfigModifier`被创建之后再执行 `modifier.modify(configuration);`
> 
> ```java
> Collection<PolarisConfigModifier> modifiers = modifierList;
> modifiers = modifiers.stream()
> 		.sorted(Comparator.comparingInt(PolarisConfigModifier::getOrder))
> 		.collect(Collectors.toList());
> if (!CollectionUtils.isEmpty(modifiers)) {
> 	for (PolarisConfigModifier modifier : modifiers) {
> 		modifier.modify(configuration);
> 	}
> }
> ```

其实不需要这样做，在实现ConfigDataLocationResolver后，我们可以直接通过`resolverContext.getBootstrapContext();`获取到`ConfigurableBootstrapContext`,然后注册相关Bean，最后在`ConfigDataLoader` 获取。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51630311/178510396-29269f2f-4a60-4704-88c2-d2acb0f81943.png">

现在我有个粗暴的思路，就是在`ConfigDataLocationResolver` 中提供硬编码先创建出一个早期暴露的SDKContext，拉取完在销毁它，在Spring Boot上下文启动时在重新注册一个SDKContext到容器。但是这样写后调用`Polaris` 会报如下错
```java
com.tencent.polaris.api.exception.RetriableException: ERR-1007(NETWORK_ERROR), [Config] failed to watch config file, cause: UNIMPLEMENTED: unknown service v1.PolarisConfigGRPC
	at com.tencent.polaris.plugins.configuration.connector.polaris.PolarisConfigFileConnector.watchConfigFiles(PolarisConfigFileConnector.java:109) ~[polaris-configuration-connector-1.7.0-20220704.110551-4.jar:na]
	at com.tencent.polaris.configuration.client.internal.DefaultConfigFileLongPollingService.doLongPolling(DefaultConfigFileLongPollingService.java:120) [polaris-configuration-client-1.7.0-20220704.110551-4.jar:na]
	at com.tencent.polaris.configuration.client.internal.DefaultConfigFileLongPollingService.lambda$startLongPollingTask$0(DefaultConfigFileLongPollingService.java:104) [polaris-configuration-client-1.7.0-20220704.110551-4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_211]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_211]
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service v1.PolarisConfigGRPC
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.33.0.jar:1.33.0]
	at com.tencent.polaris.client.pb.PolarisConfigGRPCGrpc$PolarisConfigGRPCBlockingStub.watchConfigFiles(PolarisConfigGRPCGrpc.java:234) ~[polaris-protobuf-1.7.0-20220704.110551-4.jar:na]
	at com.tencent.polaris.plugins.configuration.connector.polaris.PolarisConfigFileConnector.watchConfigFiles(PolarisConfigFileConnector.java:101) ~[polaris-configuration-connector-1.7.0-20220704.110551-4.jar:na]
	... 8 common frames omitted
```

目前还不知道如何解决，SDKContext在启动阶段构建确实不太好实现

**Comment by liqi19950722** [comment]
> 其实不需要这样做，在实现ConfigDataLocationResolver后，我们可以直接通过`resolverContext.getBootstrapContext();`获取到`ConfigurableBootstrapContext`,然后注册相关Bean，最后在`ConfigDataLoader` 获取。 <img alt="image" width="1440" src="https://user-images.githubusercontent.com/51630311/178510396-29269f2f-4a60-4704-88c2-d2acb0f81943.png">
> 
> 现在我有个粗暴的思路，就是在`ConfigDataLocationResolver` 中提供硬编码先创建出一个早期暴露的SDKContext，拉取完在销毁它，在Spring Boot上下文启动时在重新注册一个SDKContext到容器。但是这样写后调用`Polaris` 会报如下错
> 
> ```java
> com.tencent.polaris.api.exception.RetriableException: ERR-1007(NETWORK_ERROR), [Config] failed to watch config file, cause: UNIMPLEMENTED: unknown service v1.PolarisConfigGRPC
> 	at com.tencent.polaris.plugins.configuration.connector.polaris.PolarisConfigFileConnector.watchConfigFiles(PolarisConfigFileConnector.java:109) ~[polaris-configuration-connector-1.7.0-20220704.110551-4.jar:na]
> 	at com.tencent.polaris.configuration.client.internal.DefaultConfigFileLongPollingService.doLongPolling(DefaultConfigFileLongPollingService.java:120) [polaris-configuration-client-1.7.0-20220704.110551-4.jar:na]
> 	at com.tencent.polaris.configuration.client.internal.DefaultConfigFileLongPollingService.lambda$startLongPollingTask$0(DefaultConfigFileLongPollingService.java:104) [polaris-configuration-client-1.7.0-20220704.110551-4.jar:na]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_211]
> 	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_211]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_211]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_211]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_211]
> 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_211]
> Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service v1.PolarisConfigGRPC
> 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.33.0.jar:1.33.0]
> 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.33.0.jar:1.33.0]
> 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.33.0.jar:1.33.0]
> 	at com.tencent.polaris.client.pb.PolarisConfigGRPCGrpc$PolarisConfigGRPCBlockingStub.watchConfigFiles(PolarisConfigGRPCGrpc.java:234) ~[polaris-protobuf-1.7.0-20220704.110551-4.jar:na]
> 	at com.tencent.polaris.plugins.configuration.connector.polaris.PolarisConfigFileConnector.watchConfigFiles(PolarisConfigFileConnector.java:101) ~[polaris-configuration-connector-1.7.0-20220704.110551-4.jar:na]
> 	... 8 common frames omitted
> ```
> 
> 目前还不知道如何解决，SDKContext在启动阶段构建确实不太好实现

是不是调用到  spring.cloud.polaris.address=grpc://183.47.111.80:8091

**Comment by lingxiao-wu** [comment]
我基于2021分支开发完合并上游2021代码后maven构建项目有点问题，并且2021分支代码拉下来编译也有问题，大致报错如下，感觉可能是统一依赖管理有点问题
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51630311/179790611-941ef544-53e2-4777-ac59-2d165d0e6271.png">

**Comment by SkyeBeFreeman** [comment]
> 我基于2021分支开发完合并上游2021代码后maven构建项目有点问题，并且2021分支代码拉下来编译也有问题，大致报错如下，感觉可能是统一依赖管理有点问题 <img alt="image" width="1440" src="https://user-images.githubusercontent.com/51630311/179790611-941ef544-53e2-4777-ac59-2d165d0e6271.png">

看起来是没有是用到项目内配置的repository，导致没有拉取到snapshot的polaris-java，可以check一下本地maven配置是否冲突。
