### ISSUE TITLE
没有spi包

### ISSUE THREAD

**Issue by 10veU** [Tencent/spring-cloud-tencent#405]
![image](https://user-images.githubusercontent.com/37033600/177674114-f7dba63e-8ec6-4dd8-bb6e-6eaa105161d9.png)

**Comment by SkyeBeFreeman** [comment]
@10veU This feature is released in version 1.6.0.

**Comment by SkyeBeFreeman** [comment]
> @10veU This feature is released in version 1.6.0.

I will add this notice in the wiki.

**Comment by 10veU** [comment]
默认的日志目录是`/polaris/logs`，这个是在哪里配置或者设置的？如果自定义日志需要注意什么？

**Comment by SkyeBeFreeman** [comment]
> 默认的日志目录是`/polaris/logs`，这个是在哪里配置或者设置的？如果自定义日志需要注意什么？

可以在启动参数添加`-Dpolaris.log.home=${the_path_you_want}`即可自定义日志目录，详细设计可以查阅[polaris-logging](https://github.com/polarismesh/polaris-java/tree/main/polaris-common/polaris-logging)。
