### ISSUE TITLE
PolarisDiscoveryProperties的registerEnabled字段上的@Value的占位符名称为register，名称不一致

### ISSUE THREAD

**Issue by DerekYRC** [Tencent/spring-cloud-tencent#412]
**Describe the bug**
PolarisDiscoveryProperties的registerEnabled字段上的@Value的占位符名称为register，名称不一致

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
名称应该保持一直，可以兼容修改@Value注解的占位符为
```
 @Value("${spring.cloud.polaris.discovery.register-enabled:${spring.cloud.polaris.discovery.register:#{true}}}")
```

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
这个不算bug吧，就是需要通过配置 `spring.cloud.polaris.discovery.register` 来设置这个属性，不过想在代码内的属性名来标明这个属性的功能。

**Comment by DerekYRC** [comment]
两个问题：

一、@ConfigurationProperties注解和@Value注解组合使用的方式是多余的。@Value注解在AutowiredAnnotationBeanPostProcessor#postProcessProperties方法中被处理，@ConfigurationProperties注解在ConfigurationPropertiesBindingPostProcessor#postProcessBeforeInitialization方法中处理，所以会被处理两次。

二、PolarisDiscoveryProperties#registerEnabled字段名称与其注解@Value中的占位符名称不一致，且@Value注解被处理的时间先于@ConfigurationProperties被处理的时间，存在属性值被覆盖的问题。比如同时配置了```spring.cloud.polaris.discovery.register = true``` 和```spring.cloud.polaris.discovery.register-enabled = false``` ，PolarisDiscoveryProperties#registerEnabled字段值为false。

**Comment by SkyeBeFreeman** [comment]
> 两个问题：
> 
> 一、@ConfigurationProperties注解和@value注解组合使用的方式是多余的。@value注解在AutowiredAnnotationBeanPostProcessor#postProcessProperties方法中被处理，@ConfigurationProperties注解在ConfigurationPropertiesBindingPostProcessor#postProcessBeforeInitialization方法中处理，所以会被处理两次。
> 
> 二、PolarisDiscoveryProperties#registerEnabled字段名称与其注解@value中的占位符名称不一致，且@value注解被处理的时间先于@ConfigurationProperties被处理的时间，存在属性值被覆盖的问题。比如同时配置了`spring.cloud.polaris.discovery.register = true` 和`spring.cloud.polaris.discovery.register-enabled = false` ，PolarisDiscoveryProperties#registerEnabled字段值为false。

这里存在需要优化的地方，看你是否有意愿提个PR来帮助完善一下？

**Comment by DerekYRC** [comment]
> > 两个问题：
> > 一、@ConfigurationProperties注解和@value注解组合使用的方式是多余的。@value注解在AutowiredAnnotationBeanPostProcessor#postProcessProperties方法中被处理，@ConfigurationProperties注解在ConfigurationPropertiesBindingPostProcessor#postProcessBeforeInitialization方法中处理，所以会被处理两次。
> > 二、PolarisDiscoveryProperties#registerEnabled字段名称与其注解@value中的占位符名称不一致，且@value注解被处理的时间先于@ConfigurationProperties被处理的时间，存在属性值被覆盖的问题。比如同时配置了`spring.cloud.polaris.discovery.register = true` 和`spring.cloud.polaris.discovery.register-enabled = false` ，PolarisDiscoveryProperties#registerEnabled字段值为false。
> 
> 这里存在需要优化的地方，看你是否有意愿提个PR来帮助完善一下？



> > 两个问题：
> > 一、@ConfigurationProperties注解和@value注解组合使用的方式是多余的。@value注解在AutowiredAnnotationBeanPostProcessor#postProcessProperties方法中被处理，@ConfigurationProperties注解在ConfigurationPropertiesBindingPostProcessor#postProcessBeforeInitialization方法中处理，所以会被处理两次。
> > 二、PolarisDiscoveryProperties#registerEnabled字段名称与其注解@value中的占位符名称不一致，且@value注解被处理的时间先于@ConfigurationProperties被处理的时间，存在属性值被覆盖的问题。比如同时配置了`spring.cloud.polaris.discovery.register = true` 和`spring.cloud.polaris.discovery.register-enabled = false` ，PolarisDiscoveryProperties#registerEnabled字段值为false。
> 
> 这里存在需要优化的地方，看你是否有意愿提个PR来帮助完善一下？

可以的。我建议：

一、移除所有被@ConfigurationProperties修饰的类的字段上的@Value注解
二、考虑到兼容性，保留PolarisDiscoveryProperties#registerEnabled字段上的@Value注解，改为```@Value("${spring.cloud.polaris.discovery.register:${spring.cloud.polaris.discovery.register-enable:#{true}}}")```

请问你意见如何？

**Comment by DerekYRC** [comment]
> > > > 两个问题：
> > > > 一、@ConfigurationProperties注解和@value注解组合使用的方式是多余的。@value注解在AutowiredAnnotationBeanPostProcessor#postProcessProperties方法中被处理，@ConfigurationProperties注解在ConfigurationPropertiesBindingPostProcessor#postProcessBeforeInitialization方法中处理，所以会被处理两次。
> > > > 二、PolarisDiscoveryProperties#registerEnabled字段名称与其注解@value中的占位符名称不一致，且@value注解被处理的时间先于@ConfigurationProperties被处理的时间，存在属性值被覆盖的问题。比如同时配置了`spring.cloud.polaris.discovery.register = true` 和`spring.cloud.polaris.discovery.register-enabled = false` ，PolarisDiscoveryProperties#registerEnabled字段值为false。
> > > 
> > > 
> > > 这里存在需要优化的地方，看你是否有意愿提个PR来帮助完善一下？
> > 
> > 
> > > > 两个问题：
> > > > 一、@ConfigurationProperties注解和@value注解组合使用的方式是多余的。@value注解在AutowiredAnnotationBeanPostProcessor#postProcessProperties方法中被处理，@ConfigurationProperties注解在ConfigurationPropertiesBindingPostProcessor#postProcessBeforeInitialization方法中处理，所以会被处理两次。
> > > > 二、PolarisDiscoveryProperties#registerEnabled字段名称与其注解@value中的占位符名称不一致，且@value注解被处理的时间先于@ConfigurationProperties被处理的时间，存在属性值被覆盖的问题。比如同时配置了`spring.cloud.polaris.discovery.register = true` 和`spring.cloud.polaris.discovery.register-enabled = false` ，PolarisDiscoveryProperties#registerEnabled字段值为false。
> > > 
> > > 
> > > 这里存在需要优化的地方，看你是否有意愿提个PR来帮助完善一下？
> > 
> > 
> > 可以的。我建议：
> > 一、移除所有被@ConfigurationProperties修饰的类的字段上的@value注解 二、考虑到兼容性，保留PolarisDiscoveryProperties#registerEnabled字段上的@value注解，改为`@Value("${spring.cloud.polaris.discovery.register:${spring.cloud.polaris.discovery.register-enabled:#{true}}}")`
> > 请问你意见如何？
> 
> 可以的，不过唯一要求的是，不修改原有的开放对外的配置方式，也就是说老版本和新版本都使用同样的字段来完成配置。

当然，开源框架的兼容性至关重要。有空提个PR。
