### ISSUE TITLE
metadata-transfer模块，为RestTemplate添加拦截器EncodeTransferMedataRestTemplateInterceptor代码重复冗余

### ISSUE THREAD

**Issue by DerekYRC** [Tencent/spring-cloud-tencent#431]
MetadataTransferRestTemplateConfig#encodeTransferMetadataRestTemplatePostProcessor方法：

```java
@Bean
BeanPostProcessor encodeTransferMetadataRestTemplatePostProcessor(
		EncodeTransferMedataRestTemplateInterceptor encodeTransferMedataRestTemplateInterceptor) {
	// Coping with multiple bean injection scenarios
	Map<String, RestTemplate> beans = this.context.getBeansOfType(RestTemplate.class);
	// If the restTemplate has been created when the
	// MetadataRestTemplatePostProcessor Bean
	// is initialized, then manually set the interceptor.
	if (!CollectionUtils.isEmpty(beans)) {
		for (RestTemplate restTemplate : beans.values()) {
			List<ClientHttpRequestInterceptor> interceptors = restTemplate.getInterceptors();
			// Avoid setting interceptor repeatedly.
			if (!interceptors.contains(encodeTransferMedataRestTemplateInterceptor)) {
				interceptors.add(encodeTransferMedataRestTemplateInterceptor);
				restTemplate.setInterceptors(interceptors);
			}
		}
	}
	return new EncodeTransferMetadataRestTemplatePostProcessor(encodeTransferMedataRestTemplateInterceptor);
}
```

EncodeTransferMetadataRestTemplatePostProcessor#postProcessAfterInitialization方法：

```java
@Override
public Object postProcessAfterInitialization(Object bean, String beanName) {
	if (bean instanceof RestTemplate) {
		RestTemplate restTemplate = (RestTemplate) bean;
		List<ClientHttpRequestInterceptor> interceptors = restTemplate.getInterceptors();
		// Avoid setting interceptor repeatedly.
		if (!interceptors.contains(encodeTransferMedataRestTemplateInterceptor)) {
			interceptors.add(this.encodeTransferMedataRestTemplateInterceptor);
			restTemplate.setInterceptors(interceptors);
		}
	}
	return bean;
}
```

MetadataTransferRestTemplateConfig#encodeTransferMetadataRestTemplatePostProcessor方法和EncodeTransferMetadataRestTemplatePostProcessor#postProcessAfterInitialization方法中为RestTemplate增加拦截器的代码重复冗余了。

看注释大概意思是考虑到RestTemplate先于EncodeTransferMetadataRestTemplatePostProcessor实例化，所以需要在MetadataTransferRestTemplateConfig#encodeTransferMetadataRestTemplatePostProcessor方法中设置拦截器。

我理解BeanPostProcessor实例化的顺序仅次于BeanFactoryPostProcessor，会在RestTemplate实例化之前实例化，所以如上的考虑是不是多余的？

可以删除MetadataTransferRestTemplateConfig#encodeTransferMetadataRestTemplatePostProcessor方法中给RestTemplate添加拦截器的代码。更优的做法可以参照LoadBalancerAutoConfiguration中为RestTemplate添加LoadBalancerInterceptor拦截器的做法，在配置类中注入被LoadBalanced注解修饰的RestTemplate，然后为其添加拦截器。

**Comment by SkyeBeFreeman** [comment]
可以先删去冗余代码。这个metadata传递应该补强依赖loadbalancer，所以不一定要给被LoadBalanced注解修饰的RestTemplate才添加拦截器？

**Comment by DerekYRC** [comment]
> 参照LoadBalancerAutoConfiguration中为RestTemplate添加LoadBalancerInterceptor拦截器的做法，在配置类中注入被LoadBalanced注解修饰的RestTemplate，然后为其添加拦截器。

我想参照LoadBalancerAutoConfiguration中为RestTemplate添加LoadBalancerInterceptor拦截器的做法，在配置类中注入所有RestTemplate，然后为其添加EncodeTransferMedataRestTemplateInterceptor拦截器，OK吗？

**Comment by SkyeBeFreeman** [comment]
> > 参照LoadBalancerAutoConfiguration中为RestTemplate添加LoadBalancerInterceptor拦截器的做法，在配置类中注入被LoadBalanced注解修饰的RestTemplate，然后为其添加拦截器。
> 
> 我想参照LoadBalancerAutoConfiguration中为RestTemplate添加LoadBalancerInterceptor拦截器的做法，在配置类中注入所有RestTemplate，然后为其添加EncodeTransferMedataRestTemplateInterceptor拦截器，OK吗？

可以的👏
