### ISSUE TITLE
How to configure blue-green calls of internal services

### ISSUE THREAD

**Issue by XW512** [Tencent/spring-cloud-tencent#438]
如果我有两个服务，A服务与B服务，B服务有blue环境和green环境，A服务通过feign或者restTemplate内部应用名调用，服务路由那边应该怎么配置能动态的切换由A服务调用B服务的blue环境，切换到A服务调用B服务的green，并且能够自由切换

**Comment by SkyeBeFreeman** [comment]
可以在B服务所在的环境通过环境变量配置标签，参考这个[文档](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Metadata-Transfer-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E8%AF%BB%E5%8F%96)，然后在A服务通过北极星控制台添加路由规则即可。

**Comment by XW512** [comment]
> 可以在B服务所在的环境通过环境变量配置标签，参考这个[文档](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Metadata-Transfer-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E8%AF%BB%E5%8F%96)，然后在A服务通过北极星控制台添加路由规则即可。



> 可以在B服务所在的环境通过环境变量配置标签，参考这个[文档](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Metadata-Transfer-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E8%AF%BB%E5%8F%96)，然后在A服务通过北极星控制台添加路由规则即可。

好的，感谢感谢，我还有一个疑问，可以有对应的接口或者SPI来修改主调端对被调端的标签的值吗？因为在实际使用过程中，可能会切换B的版本并保证A服务调用的也是切换版本之后的B服务

**Comment by lepdou** [comment]
> > 可以在B服务所在的环境通过环境变量配置标签，参考这个[文档](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Metadata-Transfer-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E8%AF%BB%E5%8F%96)，然后在A服务通过北极星控制台添加路由规则即可。
> 
> 好的，感谢感谢，我还有一个疑问，可以有对应的接口或者SPI来修改主调端对被调端的标签的值吗？因为在实际使用过程中，可能会切换B的版本并保证A服务调用的也是切换版本之后的B服务

切换 B 的版本，应该伴随着应用的重启把？如果需要重启的话，可以每次版本变更的时候，改变版本号。这样还是静态的标签。

----
如果真正做到动态标签，会很复杂。就像你说的，通过暴露接口动态修改标签，那需要圈一批机器，一台一台调用，另外修改之后是不是还要持久化变更值，否则重启又失效了。管理上会非常复杂，而且容易搞出问题。

所以标签的话，基本上都是静态的，跟部署时候的状态绑定，比如环境变量、启动参数等。这样就简单，好管理，不容易出问题

**Comment by XW512** [comment]
> > > 可以在B服务所在的环境通过环境变量配置标签，参考这个[文档](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Metadata-Transfer-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E8%AF%BB%E5%8F%96)，然后在A服务通过北极星控制台添加路由规则即可。
> > 
> > 
> > 好的，感谢感谢，我还有一个疑问，可以有对应的接口或者SPI来修改主调端对被调端的标签的值吗？因为在实际使用过程中，可能会切换B的版本并保证A服务调用的也是切换版本之后的B服务
> 
> 切换 B 的版本，应该伴随着应用的重启把？如果需要重启的话，可以每次版本变更的时候，改变版本号，这样还是静态的标签。
> 
> 如果真正做到动态标签，会很复杂。就像你说的，通过暴露接口动态修改标签，那需要圈一批机器，一台一台调用，另外修改之后是不是还要持久化变更值，否则重启又失效了。管理上会非常复杂，而且容易搞出问题。
> 
> 所以标签的话，基本上都是静态的，跟部署时候的状态绑定，比如环境变量、启动参数等。这样就简单，好管理，不容易出问题

感谢你的回复，我想的方案是通过通知机制或者订阅的方式，每个节点监听，然后如果被调端发生了版本切换，那么就修改这个被调端的版本，应用启动的时候，会先去拉取被调端的版本，我们一般是有两个版本，一个blue，一个green，轮流发版本，如果灰度的版本验证没问题之后，就会切换版本，所以我想再切换版本的时候，调用接口或者SPI来修改被调端的标签信息，这样的话，就可以改变被调端的版本了

**Comment by SkyeBeFreeman** [comment]
蓝绿发布相关使用可以关注下个版本的Spring Cloud Tencent（1.8.0），会针对这一场景进行更细致的探索。
