### ISSUE TITLE
router模块基于ribbon的负载均衡接口IRule做扩展的做法，破坏了ribbon为每个服务自定义负责均衡规则的使用方式

### ISSUE THREAD

**Issue by DerekYRC** [Tencent/spring-cloud-tencent#445]
简单讲下原理。```RibbonClientConfigurationRegistrar```配置类将```@RibbonClients```注解修饰的配置类包装为```RibbonClientSpecification```，然后```SpringClientFactory```（继承自NamedContextFactory）根据```RibbonClientSpecification```和ribbon默认配置类```RibbonClientConfiguration```为每个服务创建一个子应用上下文```AnnotationConfigApplicationContext```，来隔离不同服务的ribbon核心API配置（包含```ServerList```、```IPing```、```IRule```、```ServerListUpdater```、```ILoadBalancer```等接口）。

可以通过以下两种方式自定义每个服务的负载均衡规则:
方式一:
```java
@Configuration
@RibbonClients(
        value = {
                @RibbonClient(name = "服务名称", configuration = ClientConfiguration.class)
        }
)
public class RibbonConfiguration {
}

@Configuration
public class ClientConfiguration {

    @Bean
    public IRule rule() {
        return new RandomRule();
    }

}
```

方式二:
配置文件中指定如下配置（原理见RibbonClientConfiguration#ribbonRule前三行代码）：
```properties
服务名称.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RandomRule
```

router模块的实现类PolarisLoadBalancerCompositeRule基于ribbon的负载均衡接口IRule做扩展，破坏了ribbon为每个服务自定义负责均衡规则的使用方式，只能通过配置```spring.cloud.polaris.loadbalancer.strategy```指定全局的负载均衡规则。

保留spring-cloud-netflix-ribbon原本的使用方式、兼容扩展是不是好一点？

**Comment by DerekYRC** [comment]
成本过高是指开发成本吗？

具体是哪个版本的```spring-cloud-commons```抛弃ribbon？

是不是后续的路由功能不是基于ribbon做扩展？既然路由功能模块router是基于ribbon实现，是不是兼容ribbon本身的使用方式更好一点？

**Comment by DerekYRC** [comment]
后续的路由功能会基于```spring-cloud-loadbalance```开发吗？

**Comment by SkyeBeFreeman** [comment]
> 后续的路由功能会基于`spring-cloud-loadbalance`开发吗？

是的，后续会考虑将主分支切换到更新版本的 Spring Cloud 。

**Comment by DerekYRC** [comment]
好的，期待后面参与一起开发。如果需要支持服务级别的自定义路由规则我就提个PR，不需要支持的话我就关闭issue。

**Comment by SkyeBeFreeman** [comment]
> 好的，期待后面参与一起开发。如果需要支持服务级别的自定义路由规则我就提个PR，不需要支持的话我就关闭issue。

目前使用router的时候确实只会指定所有ribbon的负载均衡方式而没有为每个ribbon客户端指定不同的负载均衡算法。那么支持服务级别的自定义路由规则你有什么想法呢？可以在这个issue里面讨论下，后面再提个PR，我们放在 1.8.0 milestone~

**Comment by DerekYRC** [comment]
造成这个问题的原因是显式地在```RibbonConfiguration```实例化了```PolarisLoadBalancerCompositeRule```，所以```SpringClientFactory```为每个服务创建的子应用上下文```AnnotationConfigApplicationContext```只能选择```PolarisLoadBalancerCompositeRule```作为```IRule```的实现。

我想到的一个解决方法是不要显式实例化```PolarisLoadBalancerCompositeRule```，可以在```BeanPostProcessor```的```postProcessBeforeInitialization```阶段使用```PolarisLoadBalancerCompositeRule```包装指定的```IRule```。

兼容现在的使用方式，优先使用```spring.cloud.polaris.loadbalancer.strategy```配置的负载均衡规则。
