### ISSUE TITLE
请问使用spring-cloud-starter-tencent-metadata-transfer在链路中传递元数据，支持线程切换的情况吗？

### ISSUE THREAD

**Issue by zzl86** [Tencent/spring-cloud-tencent#448]
使用spring-cloud-starter-tencent-metadata-transfer在链路中传递元数据，支持线程切换的情况吗？

**Comment by SkyeBeFreeman** [comment]
@zzl86 是复用线程池的线程切换，还是直接新建线程的线程切换呢？新建线程目前已经支持，复用线程池将在1.7.0版本发布后支持。

**Comment by misselvexu** [comment]
Reference: https://github.com/Tencent/spring-cloud-tencent/issues/372

**Comment by misselvexu** [comment]
The scenario of passing `ThreadLocal` values in the case of using thread pools and other execution components that will pool multiplex threads can be solved using existing three-party open source solutions directly.
