### ISSUE TITLE
加入jpa无法启动

### ISSUE THREAD

**Issue by lianlianyi** [Tencent/spring-cloud-tencent#494]
**Describe the bug**
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
  </dependency>

![image](https://user-images.githubusercontent.com/1701810/183021722-0d9025df-3949-436c-9ddf-b1a0ce719d3a.png)

**Comment by SkyeBeFreeman** [comment]
这个问题添加如下依赖即可：

```xml
<dependency>
    <groupId>net.bytebuddy</groupId>
    <artifactId>byte-buddy</artifactId>
    <scope>compile</scope>
</dependency>
```

问题产生的原因是spring-cloud-tencent-dependencies将byte-buddy的scope设置为test，导致编译的时候没有添加依赖。如果你是自己单独创建项目而不是直接修改spring cloud tencent的demo，也不会有这个问题。

**Comment by weihubeats** [comment]
Change the byte-buddy scope to the default compile, right?

**Comment by SkyeBeFreeman** [comment]
> Change the byte-buddy scope to the default compile, right?

@weihubeats Maybe all dependencies set in `<dependencyManagement>` of `spring-cloud-tencent-dependencies` should not be defined as "test" or others? Just remove the `<scope>` label?

**Comment by weihubeats** [comment]
Yes, just delete the scope tag, the default is compile, mock related dependencies keep the scope as test. Would it be better?

**Comment by SkyeBeFreeman** [comment]
> Yes, just delete the scope tag, the default is compile, mock related dependencies keep the scope as test. Would it be better?

Sounds good.
