### ISSUE TITLE
wiki文档拼写错误

### ISSUE THREAD

**Issue by DerekYRC** [Tencent/spring-cloud-tencent#508]
PropertySourceLoader修改为PropertySourceLocator
https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Config-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
![image](https://user-images.githubusercontent.com/44155264/184642958-ca31e71e-82b1-425d-840a-63f3ffc00c6e.png)

**Comment by misselvexu** [comment]
Okay,  Already fixed .
