### ISSUE TITLE
支持polaris发布的配置文件下载到微服务的某个路径下

### ISSUE THREAD

**Issue by XW512** [Tencent/spring-cloud-tencent#513]
现在polaris中发布的配置文件是加载到内存的，能否支持下载到微服务的某个路径下，这样更方便去查看配置文件的内容是否下发成功

**Comment by chuntaojun** [comment]
这个issue将转移到 polarismesh/polaris 仓库中跟进处理

**Comment by XW512** [comment]
> 这个issue将转移到 polarismesh/polaris 仓库中跟进处理

这个应该是spring-cloud-tencnet这个框架支持就可以了吧，不需要polaris进行处理？因为拉取配置是spring-cloud-tencent，而不是polaris

**Comment by SkyeBeFreeman** [comment]
> > 这个issue将转移到 polarismesh/polaris 仓库中跟进处理
> 
> 这个应该是spring-cloud-tencnet这个框架支持就可以了吧，不需要polaris进行处理？因为拉取配置是spring-cloud-tencent，而不是polaris

spring-cloud-tencent 利用 polaris-java 与 polaris 交互，然后将 polaris-java 获取到的配置以一个简单的形式提供给用户使用，而不是直接从 polaris 拉取配置。

**Comment by XW512** [comment]
> > > 这个issue将转移到 polarismesh/polaris 仓库中跟进处理
> > 
> > 
> > 这个应该是spring-cloud-tencnet这个框架支持就可以了吧，不需要polaris进行处理？因为拉取配置是spring-cloud-tencent，而不是polaris
> 
> spring-cloud-tencent 利用 polaris-java 与 polaris 交互，然后将 polaris-java 获取到的配置以一个简单的形式提供给用户使用，而不是直接从 polaris 拉取配置。

噢噢，明白了
