### ISSUE TITLE
Feign调用结果上报支持请求标签上报

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#514]
**What is the feature you want to add?**

在`spring-cloud-tencent-rpc-enhancement`模块中的上报调用结果工具中，添加请求标签字段的上报。

**Why do you want to add this feature?**

可观测性页面可以使用请求标签筛选。

**How to implement this feature?**

**Additional context**

开发前需要讨论实现思路。

**Comment by chuntaojun** [comment]
> 

是这样子的

**Comment by SkyeBeFreeman** [comment]
@pandaapo RestTemplate 和 Feign 的做法应该不同，你这边是想实现 RestTemplate 的方式是吧？

**Comment by SkyeBeFreeman** [comment]
噢噢我是想问是想实现 Feign 的方式，写错😂

**Comment by chuntaojun** [comment]
> 上报的请求标签有没有格式要求？我目前的格式是json字符串，形如`{"a":"b","c":"d"}`。

具体代码贴一下？

**Comment by SkyeBeFreeman** [comment]
> 上报的请求标签有没有格式要求？我目前的格式是json字符串，形如`{"a":"b","c":"d"}`。

形如 `a:b|c:d` 的字符串。

**Comment by SkyeBeFreeman** [comment]
> 对于RestTemplate的实现方式：在`PolarisLoadBalancerInterceptor#intercept()`的逻辑中，构建`PolarisRouterContext`的时候解析了标签并保存其中，所以可以从中取出标签，放到返回的`ClientHttpResponse`的header中。然后在`EnhancedRestTemplateReporter#handleError(, , ClientHttpResponse)`中，从`ClientHttpResponse`的header中取出标签，构建`ServiceCallResult`。 这思路正确吗？

大体思路是可以的，只是RestTemplate的数据上报最近在重构，可以等重构完再继续完成这一块的实现。

**Comment by SkyeBeFreeman** [comment]
> 对于RestTemplate的实现方式：在`PolarisLoadBalancerInterceptor#intercept()`的逻辑中，构建`PolarisRouterContext`的时候解析了标签并保存其中，所以可以从中取出标签，放到返回的`ClientHttpResponse`的header中。然后在`EnhancedRestTemplateReporter#handleError(, , ClientHttpResponse)`中，从`ClientHttpResponse`的header中取出标签，构建`ServiceCallResult`。 这思路正确吗？

RestTemplate 已经重构完成，看下最近有空参与这一块的开发不？

**Comment by SkyeBeFreeman** [comment]
转移到 #579
