### ISSUE TITLE
服务注册必须添加spring-boot-starter-web包才生效

### ISSUE THREAD

**Issue by beiming-tuling** [Tencent/spring-cloud-tencent#537]
**Describe the bug**
服务注册必须添加spring-boot-starter-web包才生效

**To Reproduce**
![image](https://user-images.githubusercontent.com/81206614/186693068-42cad978-b0ac-4d8b-a1dd-c83fdc93d04f.png)
![image](https://user-images.githubusercontent.com/81206614/186693100-423c1427-2ac1-416c-b5e1-32a349c9ee13.png)
![image](https://user-images.githubusercontent.com/81206614/186693237-59d0fd6c-e63d-4ff7-9dbc-9a1e3e72d163.png)
![image](https://user-images.githubusercontent.com/81206614/186693331-99f6b0af-d77f-44f5-9c60-460516a7b446.png)
![image](https://user-images.githubusercontent.com/81206614/186693455-a44ea92b-345b-4a69-bcef-4989470139e9.png)

**Expected behavior**
它应该不依赖spring-boot-starter-web进行服务注册与服务发现

**Environment**
- Version: [1.7.0-Hoxton.SR12，Java8]
- OS: [e.g. Windows10]

**Additional context**
我改完之后提交PR

**Comment by DerekYRC** [comment]
@beiming-tuling 服务发现可以不依赖spring-boot-starter-web，服务注册为什么不依赖spring-boot-starter-web呢？服务注册不依赖spring-boot-starter-web那监听端口是？

**Comment by beiming-tuling** [comment]
@DerekYRC 如果我的rpc框架不是feign和resttemplate，而是grpc和dubbo等等。那么我用tomcat的意义是什么呢？

**Comment by beiming-tuling** [comment]
@DerekYRC 我就没有必要引入spring-boot-starter-web这个包了对吧。

**Comment by DerekYRC** [comment]
> @DerekYRC 如果我的rpc框架不是feign和resttemplate，而是grpc和dubbo等等。那么我用tomcat的意义是什么呢？

Get

**Comment by chuntaojun** [comment]
目前 spring cloud 的服务注册，是基于 spring cloud 本身提供的 web 服务的，您这里说的 如果是 grpc 或者 dubbo 的话，应该在 grpc-server & dubbo 本身完成服务注册动作，因为 spring cloud 对您的业务来说只是一个容器而已，服务的提供者是 grpc & dubbo

**Comment by beiming-tuling** [comment]
不能把服务提供者框定在tomcat对不对，如果我没有提供，你可以阻止我进行服务发现，但是你不能阻止我进行服务注册

**Comment by beiming-tuling** [comment]
@chuntaojun

**Comment by chuntaojun** [comment]
如果是 grpc 或者 dubbo 的话，应该在 grpc-server & dubbo 本身完成服务注册动作

**Comment by SkyeBeFreeman** [comment]
在 Spring Cloud 框架实现中，服务注册的行为可以由 `WebServerInitializedEvent` 事件触发的。如果没有引入 `spring-boot-starter-web` 包，则没有这个事件来触发服务注册。其他的服务提供的实现也需要给出相应的注册触发行为。
