### ISSUE TITLE
SCT中 heartbeat-interval 的单位设计是毫秒，但是JAVA-SDK中TTL的单位是秒

### ISSUE THREAD

**Issue by chuntaojun** [Tencent/spring-cloud-tencent#557]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
Will fix in the next version.
