### ISSUE TITLE
监听InstancePreRegisteredEvent无法修改PolarisRegistration相关信息, 如修改metadata相关信息

### ISSUE THREAD

**Issue by galaxy-sea** [Tencent/spring-cloud-tencent#584]
**Describe the bug**
监听InstancePreRegisteredEvent无法修改PolarisRegistration相关信息, 如修改metadata相关信息,

目前PolarisRegistration.metadata字段的map实现类使用的是UnmodifiableMap, PolarisRegistration.host字段被final修饰, 导致无法利用InstancePreRegisteredEvent进行一系列的骚操作

**To Reproduce**
Steps to reproduce the behavior.
```java
public class RegistryConfiguration {
    @Bean
    public InstancePreRegisteredEventListener<Registration> startMetadata() {
        return registration -> {
            Map<String, String> metadata = registration.getMetadata();
            // 项目启动pid
            metadata.put("PID", System.getProperties().getProperty("PID"));
            // 项的启动时间
            metadata.put("startTime", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
        };
    }
}
```

**Expected behavior**
PolarisRegistration.metadata字段和PolarisRegistration.host 的扩张性应该交给开发者, Spring Cloud Commons中多处的设计使用Event进行扩展, Spring Cloud Tencent不应该把这些扩展功能给关闭了

**Comment by SkyeBeFreeman** [comment]
Use English PR title.
