### ISSUE TITLE
Access link "[使用polaris-java]" won't open

### ISSUE THREAD

**Issue by bolinli** [Tencent/spring-cloud-tencent#60]
[使用polaris-java](https://github.com/polarismesh/website/blob/main/docs/zh/doc/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/%E4%BD%BF%E7%94%A8polaris-java.md)
404Not Found

**Comment by SkyeBeFreeman** [comment]
Thx for reporting bug.
