### ISSUE TITLE
feign接口采用url方式调用报错，如图所示

### ISSUE THREAD

**Issue by xiaoyao1999hn** [Tencent/spring-cloud-tencent#616]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/25003047/192533652-65d4270a-c669-4620-93c0-6e6f22c30e16.png">
<img width="1293" alt="企业微信截图_86c5eb22-33d9-4abf-9755-4a886e112776" src="https://user-images.githubusercontent.com/25003047/192534543-1099e228-0d61-46a8-a37d-99a44d04d99b.png">
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/25003047/192535920-984b5ad3-c79c-44b1-8157-d47314057f58.png">

如图所示，如果feign接口采用url的方式去调用，port会为-1，会导致Validator.validateHostPort校验通不过

**Comment by lepdou** [comment]
Fix #623

**Comment by pandaapo** [comment]
> Fix #623

可能我哪里理解有问题。之前我看截图中的堆栈信息，觉得这不应该是polaris-java中的bug吗？

**Comment by lepdou** [comment]
> > Fix #623
> 
> 可能我哪里理解有问题。之前我看截图中的堆栈信息，觉得这不应该是polaris-java中的bug吗？

这个原因是 sct 上报调用结果到 polaris-java 里的时候，port 端口号 -1 导致的。feign  url 硬负载的场景下，可能就是没有端口，所以没取到端口。
