### ISSUE TITLE
SCT支持对Http代理服务进行负载均衡

### ISSUE THREAD

**Issue by davionchen** [Tencent/spring-cloud-tencent#632]
**What is the feature you want to add?**
SCT 外调地址重写,支持对Http代理服务器进行负载均衡。

**Why do you want to add this feature?**
为什么要对 Http代理服务器进行负载均衡，目的是在北极星进行统一流量控制。 而且应用层控制流量，能够处理更多的故障切换场景。

SCT典型的使用场景 内网系统之间的调用，默认情况下，根据Instance的IpPort构造URL地址。

但是在金融业务场景中，会遇到内网调用外网的情况。外网服务提供HttpUrl。内网的前置服务，利用ECN区的Http代理服务访问外网服务。考虑可用性，Http代理服务会部署多台。前置服务根据实际情况动态切换Http代理服务。

前置服务 | <--polaris/http-->Http代理服务1| <--VPN/专线---> 外网服务
前置服务 | <--polaris/http-->Http代理服务2| <--VPN/专线---> 外网服务

为了复用北极星和SCT的服务治理能力。需要SCT支持url重写，并利用ApacheHttpCleint的Router机制，获取代理地址。
**How to implement this feature?**
- 在北极星注册 代理服务
![image](https://user-images.githubusercontent.com/2884774/194793565-2890ce94-14d9-413f-a8f0-feb5495a76f3.png)

- 实现sct url插件，进行重写，预期返回自定义的url

- 重写httpClient的DefaultRoutePlanner，从北极星获取代理地址。

**Additional context**

**Comment by pandaapo** [comment]
没太明白实现方案中的代理服务的作用？是在该服务中应用url重写插件和DefaultProxyRoutePlanner吗，然后内网服务来调该代理服务访问外网？

**Comment by lepdou** [comment]
@pandaapo 翻译成 SCT 的语言是这样子：
1. 北极星上的服务地址，并不是服务端自动注册上去的，而且人工在管控台配置的IP地址。这个IP 地址是 RestTemplate 的代理地址，并不是实际调用的目标地址
2. 在 RestTemplate 实际发生调用时，把代理地址替换成一个实际外调访问的域名（所以用于外调外网第三方接口用的，不是内部服务调用），并且把代理地址设置到 ApacheHttpCleint 里。

------------
**目的**
目的是想复用 SCT + 北极星这套服务治理能力，比如服务路由、熔断等。

------------
**实现**
这个实现的话有点难度，估计要把 RestTemplate 里面的一些口子给暴露成 SPI，让用户可以 修改目标地址之类的。

**Comment by davionchen** [comment]
> 

feign呢？

**Comment by andrewshan** [comment]
内网访问外网的服务，框架本身怎么知道我是从内网服务访问外网服务呢？

**Comment by davionchen** [comment]
讨论结果：

1、前置服务 通过北极星 可寻址到代理服务的IpPort。
2、考虑通过httpclient 重写URL(待确认)。
3、通过feign的request header，传递IpPort。上报时，再从request header取出来，作为updateServiceCallResult的上报参数。

**Comment by pandaapo** [comment]
> 讨论结果：
> 
> 1、前置服务 通过北极星 可寻址到代理服务的IpPort。
> 2、考虑通过httpclient 重写URL(待确认)。 
> 3、通过feign的request header，传递IpPort。上报时，再从request header取出来，作为updateServiceCallResult的上报参数。

类似疑问：框架本身怎么知道此次访问的是需要重写的代理服务？

**Comment by davionchen** [comment]
已调整

**Comment by davionchen** [comment]
> 讨论结果：
> 
> 1、前置服务 通过北极星 可寻址到代理服务的IpPort。 2、考虑通过httpclient 重写URL(待确认)。 3、通过feign的request header，传递IpPort。上报时，再从request header取出来，作为updateServiceCallResult的上报参数。

步骤2的验证结果：
利用DefaultRoutePlanner返回代理服务器地址，并通过反射机制调目标地址，调整后的目标地址为外网服务的HOST。
优点：不影响Fegin和Polaris的数据，只在ApacheHttpClient层进行修改。
缺点：引入反射机制，升级框架时，需小心。

**Comment by andrewshan** [comment]
> > 讨论结果：
> > 1、前置服务 通过北极星 可寻址到代理服务的IpPort。 2、考虑通过httpclient 重写URL(待确认)。 3、通过feign的request header，传递IpPort。上报时，再从request header取出来，作为updateServiceCallResult的上报参数。
> 
> 步骤2的验证结果： 利用DefaultRoutePlanner返回代理服务器地址，并通过反射机制调目标地址，调整后的目标地址为外网服务的HOST。 优点：不影响Fegin和Polaris的数据，只在ApacheHttpClient层进行修改。 缺点：引入反射机制，升级框架时，需小心。

这个目标地址调整没有GET和SET方法是吧？针对哪个类的哪个成员进行反射设置？

**Comment by davionchen** [comment]
> 

方法原型：
```java
 protected HttpHost determineProxy(HttpHost target, HttpRequest httpRequest, HttpContext context) throws HttpException {}
```
HttpHost是不可变的，无修改入口。只能通过反射机制修改target对象的hostname、lcHostname、port、schemeName。
