### ISSUE TITLE
router模块实现全链路灰度使用问题

### ISSUE THREAD

**Issue by qnnn** [Tencent/spring-cloud-tencent#654]
使用各版本全链路灰度demo "polaris-router-grayrelease-example" 均无法实现
1. 关于规则设置，demo中只对"gateway"服务设置主调规则，观察到标签通过请求头透传了
请问在"gateway"上的主调规则会透传吗，还是说所有的节点都需要配置这些规则

**Comment by chuntaojun** [comment]
> 

是按照example中的命令创建的路由规则吗

**Comment by qnnn** [comment]
2. 关于环境标识透传，第一跳的节点拥有环境env=green，它将自身的环境标识env=green放在请求头中，它是怎么确定第二跳还是env=green的节点的呢。（demo中没有为链路上的节点设置规则）。
请问是不是得在链路上的每个节点都设置（env=green->env=green .....）的规则，环境标识的透传是将第一跳的节点的环境标识覆盖掉它此次调用时整条链路的环境标识吗，（如env=green的下一跳节点不存在env=green，它路由到env=blue的节点，并透传其环境标识覆盖掉env=blue的节点，确保在下一跳时继续走env=green->env=green）

**Comment by qnnn** [comment]
> 

https://github.com/Tencent/spring-cloud-tencent/blob/2021.0/spring-cloud-tencent-examples/polaris-router-grayrelease-example/README-zh.md   根据该demo

**Comment by qnnn** [comment]
> > 
> 
> 是按照example中的命令创建的路由规则吗

根据该demo https://github.com/Tencent/spring-cloud-tencent/issues/654#issuecomment-1283646390

**Comment by qnnn** [comment]
> > 
> 
> 是按照example中的命令创建的路由规则吗

根据该demo做的  https://github.com/Tencent/spring-cloud-tencent/blob/2021.0/spring-cloud-tencent-examples/polaris-router-grayrelease-example/README-zh.md

**Comment by qnnn** [comment]
3. 关于polaris规则类型。看了前几天新发的v1.12.0版本的polaris，自定义路由有许多变化，以往的主调规则跟被调规则被统一了，目前v1.12.0版本的polaris的规则，每个服务节点在sdk侧会拉取该命名空间下所有自定义路由规则去判断吗

**Comment by lepdou** [comment]
可以直接跑一下这个demo
https://github.com/Tencent/spring-cloud-tencent/tree/2021.0/spring-cloud-tencent-examples/polaris-router-featureenv-example
