### ISSUE TITLE
support multi register and discovery both to nacos and polaris 

### ISSUE THREAD

**Issue by andrewshan** [Tencent/spring-cloud-tencent#658]
**What is the feature you want to add?**
support nacos and polaris discovery and register, similar to this feature: https://github.com/Tencent/spring-cloud-tencent/wiki/Multi-registration-and-multi-discovery

**Why do you want to add this feature?**
a mass percent of developers in spring cloud using nacos as registry, they want to transfer to polaris governance smoothly.

**How to implement this feature?**
1. make polaris-java support nacos
2. transfer the nacos configuration into polaris-java configuration to active nacos registry

**Additional context**

**Comment by lingxiao-wu** [comment]
这个任务我可以试试，polaris-java支持nacos目前基于哪个分支开发啊？

**Comment by chuntaojun** [comment]
> 这个任务我可以试试，polaris-java支持nacos目前基于哪个分支开发啊？

社区已经有相关的 PR 在处理了，SCT 这里应该是后续需要升级对应的 polaris-java 依赖以及整理相关使用文档

**Comment by andrewshan** [comment]
### 关于NACOS-GROUP的处理

SDK：

- 服务名：group__service（北极星） = group, service（nacos）
- 服务名：service（北极星） = DEFAULT_GROUP, service（nacos）

SCT：

SCT从nacos的配置（spring.cloud.nacos.discovery.group）中读取GROUP：

- 假如GROUP为空或者为DEFAULT：传入服务名与现有逻辑一致，不拼接
- 假如GROUP为其他，则传入服务名为group__service

### 关于NACOS-CLUSTER的处理

SDK：

Java SDK从实例metadata中获取internal-nacos-cluster的值，假如存在，则作为实例的CLUSTER注册

SCT：

SCT从nacos配置（spring.cloud.nacos.discovery.cluster-name）中读取集群名：

- 假如集群名为空，则不填入
- 假如不为空，则设置为internal-nacos-cluster的metadata的值。

**Comment by SkyeBeFreeman** [comment]
> 这个任务我可以试试，polaris-java支持nacos目前基于哪个分支开发啊？

@lingxiao-wu [1.10.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/tencent/polaris/polaris-dependencies/1.10.0-SNAPSHOT/)

**Comment by lingxiao-wu** [comment]
> > 这个任务我可以试试，polaris-java支持nacos目前基于哪个分支开发啊？
> 
> @lingxiao-wu [1.10.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/tencent/polaris/polaris-dependencies/1.10.0-SNAPSHOT/)

好的，我拉取完研究一下

**Comment by lingxiao-wu** [comment]
> ### 关于NACOS-GROUP的处理
> SDK：
> 
> * 服务名：group__service（北极星） = group, service（nacos）
> * 服务名：service（北极星） = DEFAULT_GROUP, service（nacos）
> 
> SCT：
> 
> SCT从nacos的配置（spring.cloud.nacos.discovery.group）中读取GROUP：
> 
> * 假如GROUP为空或者为DEFAULT：传入服务名与现有逻辑一致，不拼接
> * 假如GROUP为其他，则传入服务名为group__service
> 
> ### 关于NACOS-CLUSTER的处理
> SDK：
> 
> Java SDK从实例metadata中获取internal-nacos-cluster的值，假如存在，则作为实例的CLUSTER注册
> 
> SCT：
> 
> SCT从nacos配置（spring.cloud.nacos.discovery.cluster-name）中读取集群名：
> 
> * 假如集群名为空，则不填入
> * 假如不为空，则设置为internal-nacos-cluster的metadata的值。

我按照规则拼接完发现sdk没有将group和service拆开，nacos依旧注册到了DEFAULT_GROUP
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51630311/199500835-b36d1193-465b-4ade-bd4e-293a94883702.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51630311/199500951-802f87e5-b542-4d97-9776-09ebdd04584b.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51630311/199503102-0d52a442-4df1-48fa-b4b2-86a456c38cb0.png">

这是符合预期的吗

**Comment by chuntaojun** [comment]
> > ### 关于NACOS-GROUP的处理
> > SDK：
> > 
> > * 服务名：group__service（北极星） = group, service（nacos）
> > * 服务名：service（北极星） = DEFAULT_GROUP, service（nacos）
> > 
> > SCT：
> > SCT从nacos的配置（spring.cloud.nacos.discovery.group）中读取GROUP：
> > 
> > * 假如GROUP为空或者为DEFAULT：传入服务名与现有逻辑一致，不拼接
> > * 假如GROUP为其他，则传入服务名为group__service
> > 
> > ### 关于NACOS-CLUSTER的处理
> > SDK：
> > Java SDK从实例metadata中获取internal-nacos-cluster的值，假如存在，则作为实例的CLUSTER注册
> > SCT：
> > SCT从nacos配置（spring.cloud.nacos.discovery.cluster-name）中读取集群名：
> > 
> > * 假如集群名为空，则不填入
> > * 假如不为空，则设置为internal-nacos-cluster的metadata的值。
> 
> 我按照规则拼接完发现sdk没有将group和service拆开，nacos依旧注册到了DEFAULT_GROUP <img alt="image" width="1440" src="https://user-images.githubusercontent.com/51630311/199500835-b36d1193-465b-4ade-bd4e-293a94883702.png"> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/51630311/199500951-802f87e5-b542-4d97-9776-09ebdd04584b.png">
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/51630311/199503102-0d52a442-4df1-48fa-b4b2-86a456c38cb0.png">
> 
> 这是符合预期的吗

这个我们先提交改下 polaris-java

**Comment by lingxiao-wu** [comment]
sdk 在shutdownhook中清理nacos注册信息时会出现npe，这是报错的堆栈信息
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51630311/199507648-0159c76f-2106-4985-9a97-d311e4e4054f.png">

**Comment by chuntaojun** [comment]
> sdk 在shutdownhook中清理nacos注册信息时会出现npe，这是报错的堆栈信息 <img alt="image" width="1440" src="https://user-images.githubusercontent.com/51630311/199507648-0159c76f-2106-4985-9a97-d311e4e4054f.png">

我今天修复下，重新发一个 SNAPSHOT

**Comment by chuntaojun** [comment]
@lingxiao-wu 新的 SNAPSHOT 以及发到 maven 仓库了，可以看看先支持下 2021 ？
