### ISSUE TITLE
关于 router模块实现全链路灰度的学习

### ISSUE THREAD

**Issue by gotoworld** [Tencent/spring-cloud-tencent#659]
cloud tencent 在东西向支持基于请求头标签特征的动态路由。是否 腾讯团队修改了微服务之间调用时负载和路由的策略实现，新增了基于默认的标签路由策略。

1、请问新增的标签路由策略对应的类是哪个，谢谢
2、是否有相关的分享文档

**Comment by lepdou** [comment]
@gotoworld 

> 修改了微服务之间调用时负载和路由的策略实现

是的。主要包含两部分实现：

1. 扩展服务调用框架（RestTemplate、Feign）的负载均衡Interceptor，使其能够传递路由上下文信息（标签）到后面具体的负载均衡器
2. 扩展 Ribbon、Spring LoadBalancer ，使其能够根据路由上下文实现动态路由。

文档&代码

1. 文档 https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Router-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
2. 代码主要在 router 模块里，可以仔细看一下。路由是 SCT 最复杂的模块，看起来估计会有点绕

**Comment by gotoworld** [comment]
@lepdou 非常感谢，很有帮助
