### ISSUE TITLE
heartbeat thread cannot be started when register again

### ISSUE THREAD

**Issue by michaelwangwangwang** [Tencent/spring-cloud-tencent#67]
When I manually call spring's registration and deregistration interface (actually, the registration and deregistration methods of Polaris will be called), there is no problem with the deregistration, but when I call the registration interface again, the service can be registered normally, but the heartbeat thread fails to ope
<img width="1650" alt="wecom-temp-7931ab6bec41889548e442e0be16f6f8" src="https://user-images.githubusercontent.com/69467855/160517859-32f62c2a-b18b-4858-b664-fbaff3d76fcc.png">
n

**Comment by lepdou** [comment]
Fixed
