### ISSUE TITLE
Spring Cloud Tencent 的服务注册到北极星，使用 polaris-java的registerInstance 方法

### ISSUE THREAD

**Issue by chuntaojun** [Tencent/spring-cloud-tencent#673]
**What is the feature you want to add?**

- 将原本的 register 方法替换为 registerInstance 方法

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by DerekYRC** [comment]
我来吧

**Comment by DerekYRC** [comment]
@chuntaojun ```ProviderAPI#registerInstance```方法中会开启心跳检测的周期任务，改用该方法后是不是需要废弃是否启用心跳检测的开关```PolarisDiscoveryProperties#heartbeatEnabled```?

**Comment by chuntaojun** [comment]
> @chuntaojun `ProviderAPI#registerInstance`方法中会开启心跳检测的周期任务，改用该方法后是不是需要废弃是否启用心跳检测的开关`PolarisDiscoveryProperties#heartbeatEnabled`?

是的，设置废弃吧，已经不生效了

**Comment by chuntaojun** [comment]
不过我记得 sct 这里允许用户先自己探测，然后再决定是否做心跳上报，这个要看看兼容问题

**Comment by DerekYRC** [comment]
> 不过我记得 sct 这里允许用户先自己探测，然后再决定是否做心跳上报，这个要看看兼容问题

@chuntaojun registerInstance方法合并了注册和心跳上报逻辑，如果要考虑兼容问题允许用户探测再决定是否上报心跳，能不能修改registerInstance方法增加一个callback参数，注册逻辑执行成功后执行callback，callback执行成功再执行心跳上报逻辑？

或者有没有其他更好的建议？

**Comment by chuntaojun** [comment]
> > 不过我记得 sct 这里允许用户先自己探测，然后再决定是否做心跳上报，这个要看看兼容问题
> 
> @chuntaojun registerInstance方法合并了注册和心跳上报逻辑，如果要考虑兼容问题允许用户探测再决定是否上报心跳，能不能修改registerInstance方法增加一个callback参数，注册逻辑执行成功后执行callback，callback执行成功再执行心跳上报逻辑？
> 
> 或者有没有其他更好的建议？

先在 sct 做兼容吧，如果用户配置了自己的探测逻辑，那就转为老的接口调用，不然就全部转到新的 registerInstance

**Comment by DerekYRC** [comment]
好的，总结下：
- 废弃是否启用心跳上报开关```PolarisDiscoveryProperties#heartbeatEnabled```
- 如果用户配置健康检查url```PolarisDiscoveryProperties#healthCheckUrl```，走老逻辑；否则使用新的```registerInstance```方法
