### ISSUE TITLE
增加接口级别的熔断功能

### ISSUE THREAD

**Issue by michaelwangwangwang** [Tencent/spring-cloud-tencent#678]
当服务某一接口连续返回请求超时等失败，我们希望此时框架能够自动熔断该接口，快速返回失败，避免流量持续打到有问题的接口中，造成资源阻塞，但服务的其它接口可以正常被访问、正常工作，也就是接口级别的熔断

**Comment by DerekYRC** [comment]
不是已经支持接口级别的限流功能了吗？

**Comment by andrewshan** [comment]
Java SDK已经支持了接口级限流相关的能力，计划会扩展Spring Cloud的circuitbreaker接口，在resillent4j和springretry基础上，对接上北极星的接口级限流功能，实现针对任务方法调用的接口及服务的限流：https://spring.io/projects/spring-cloud-circuitbreaker
