### ISSUE TITLE
【需求认领】使用 maven-shade-plugin 插件打包 spring-cloud-starter-tencent-all

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#680]
目前 `spring-cloud-starter-tencent-all` 的引入方式需要手动填写 `pom` ，可以使用 `maven-shade-plugin` 打包以支持 `jar` 方式引入，同时可以重命名包括但不仅限于 grpc、protobuf、guava 等依赖，以防止引入 `spring-cloud-starter-tencent-all` 带来的依赖冲突。

**Comment by weihubeats** [comment]
I will finish it
