### ISSUE TITLE
【需求认领】配置中心反射模式下，支持删除配置文件、配置项

### ISSUE THREAD

**Issue by lepdou** [Tencent/spring-cloud-tencent#681]
# 现象
Spring Cloud 原生通过刷新 Context 和 Bean 的方式支持属性动态刷新，这种方式的缺点是影响面太大，需要重建所有的 bean。
SCT 优化了刷新属性的逻辑：

1. 通过反射调用的方式刷新 `@Value` 的属性
2. 对于 `@ConfigurationProperties` 配置类 bean，则通过 rebind 的方式，只 rebind 跟变更的配置项相关的 bean，而不是全量的bean

并在 1.7.0 版本之后，作为默认的刷新方式。

但是优化之后的方式 `@ConfigurationProperties` 不支持删除配置项。以 demo 为例：

**配置 person** 
![image](https://user-images.githubusercontent.com/4991116/199152765-78ca59e7-c138-41ca-94ac-79468add41ce.png)

**代码里调用**
![image](https://user-images.githubusercontent.com/4991116/199152811-e28640cc-f091-4473-a8c6-4247e8183ff5.png)

删除 age 属性，或者删除整个配置文件

![image](https://user-images.githubusercontent.com/4991116/199152945-62e88b9e-83a7-463c-a144-2213c29727f9.png)

删除配置之后，代码里读取的还是删除之前的值。
![image](https://user-images.githubusercontent.com/4991116/199152811-e28640cc-f091-4473-a8c6-4247e8183ff5.png)

刷新 Context 的方式则不存在这个问题，因为是完全重新构建 Bean。

# 原因

reflect 模式下，通过以下Spring Cloud 原生的方式，实现  `@ConfigurationProperties` 配置类 bean 刷新。

详细流程如下：

**1. 发布配置变更事件**

```
# PolarisRefreshAffectedContextRefresher#refreshConfigurationProperties()

context.publishEvent(new EnvironmentChangeEvent(context, changeKeys));
```

**2. rebind 影响的 bean**

```
# AffectedConfigurationPropertiesRebinder#onApplicationEvent

private void rebindAffectedBeans(EnvironmentChangeEvent event) {
		Set<String> changedKeys = event.getKeys();

		if (CollectionUtils.isEmpty(changedKeys)) {
			return;
		}

		propertiesBeans.forEach((name, bean) -> {
			changedKeys.forEach(key -> {
				String propertiesPrefix = Objects.requireNonNull(AnnotationUtils.getValue(bean.getAnnotation()))
						.toString();
				if (key.startsWith(propertiesPrefix)) {
					rebind(name);
				}
			});
		});
	}
```
跟进 rebind 逻辑发现，问题出在以下这个地方：

![image](https://user-images.githubusercontent.com/4991116/199154175-2573ea85-3395-4f77-a1ea-41871420a339.png)

从而导致删除的 key 没有更新。

# 解决方案

需要解决一个核心问题，就是删除情况下，如何知道 `@ConfigurationProperties` 属性的默认的值？`@Value` 可以通过 annotation 里解析出来，但是 `@ConfigurationProperties` 的属性，可能是代码里设置的，比如 age 属性：

```

@Component
@ConfigurationProperties(prefix = "teacher")
public class Person {

	private String name;

	private int age = 800;

}
```

想到的一种方案，在 AffectedConfigurationPropertiesRebinder 扫描 `@ConfigurationProperties` bean 的时候，解析一下 bean，取到属性默认值，然后记下来。在删除key的时候，拿到原始的默认值，然后用 update的方式更新？

**Comment by dongyinuo** [comment]
认领一下

**Comment by dongyinuo** [comment]
实现方案
1. 声明一个注解 比如 @RevertDefaultValue 用来表明 @ConfigurationProperties bean 支持删除属性 恢复默认值。后面若 spring 本身支持 删除恢复默认值， @RevertDefaultValue 此注即可失效
2. AffectedConfigurationPropertiesRebinder @ConfigurationProperties bean 存储其每个字都默认值
3. com.tencent.cloud.polaris.config.adapter.AffectedConfigurationPropertiesRebinder#rebindAffectedBeans 中 rebind 后，当为删除动作时，通过反射 设置 bean 的默认属性

**Comment by lepdou** [comment]
@dongyinuo
@RevertDefaultValue 是打在 bean 上面还是属性上面？我理解最好是不要额外加自定义的注解？所有的bean都默认支持可以删除属性，这样对用户来说：
1. 使用成本低，不需要额外的注解。而且绝大部分情况下，用户写@ConfigurationProperties时，并不会考虑删除属性的场景
2. 延续用户使用spring boot 的习惯

**Comment by dongyinuo** [comment]
@lepdou 
是的，大致设想是 @RevertDefaultValue 写在 bean 上支持，删除属性，恢复默认值。考虑点主要是 @ConfigurationProperties 利用spring 重新构建 bean 填充属性， 考虑到 1. 不修改 springboot 源码 2. 当 spring 支持对象属性不存在时， 重新构建bean 时，用其默认字段。到时只用 @RevertDefaultValue 作废，逐步移除相关代码即可

**Comment by dongyinuo** [comment]
我先 按照不需要 @RevertDefaultValue 实现一版
