### ISSUE TITLE
【需求认领】提升 spring-cloud-starter-tencent-polaris-router 模块的单元测试覆盖率

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#682]
- 目标提升到80%以上

<img width="744" alt="image" src="https://user-images.githubusercontent.com/24446200/199155995-aa884e60-f8d9-4a0b-b9ed-a0c1b9e6cbeb.png">

- 如何获取单侧覆盖率：
1. 项目根目录下运行`mvn test`
2. 项目根目录下用浏览器打开`target/site/jacoco/index.html`即可查看单侧覆盖率，点进去即可查看详细覆盖情况以作出补充

- 额外提供

需要额外提供更新后的单测覆盖率截图到 PR 下方

**Comment by dongyinuo** [comment]
认领一下
