### ISSUE TITLE
【需求认领】提升 spring-cloud-tencent-gateway-plugin 模块的单元测试覆盖率

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#683]
- 目标提升到80%以上

<img width="752" alt="image" src="https://user-images.githubusercontent.com/24446200/199162123-df7bb42d-e152-4bcd-b116-ae51aceb76fc.png">

- 如何获取单侧覆盖率：
1. 项目根目录下运行`mvn test`
2. 项目根目录下用浏览器打开`target/site/jacoco/index.html`即可查看单侧覆盖率，点进去即可查看详细覆盖情况以作出补充

- 额外提供

需要额外提供更新后的单测覆盖率截图到 PR 下方

**Comment by DerekYRC** [comment]
我来吧，估计下周才有开发时间。

**Comment by DerekYRC** [comment]
@SkyeBeFreeman  分支覆盖率也要达到80%吗？

![image](https://user-images.githubusercontent.com/44155264/199772149-ff6c6a50-b065-49c4-8d73-c38a4f229302.png)

**Comment by SkyeBeFreeman** [comment]
> @SkyeBeFreeman 分支覆盖率也要达到80%吗？
> 
> ![image](https://user-images.githubusercontent.com/44155264/199772149-ff6c6a50-b065-49c4-8d73-c38a4f229302.png)

尽量都达到80%
