### ISSUE TITLE
remove deprecated method

### ISSUE THREAD

**Issue by weihubeats** [Tencent/spring-cloud-tencent#696]
**What is the feature you want to add?**
remove deprecated method
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/42484192/199914568-da986f71-9095-405c-b7ee-14ce64efeda0.png">

**Why do you want to add this feature?**
remove deprecated method
**How to implement this feature?**
remove deprecated method
**Additional context**

**Comment by dongyinuo** [comment]
这个有人认领了吗？

**Comment by SkyeBeFreeman** [comment]
> 这个有人认领了吗？

weihubeats已经做了提交
