### ISSUE TITLE
希望spring cloud tencent能尽早的适配springboot2.7.5

### ISSUE THREAD

**Issue by opcooc** [Tencent/spring-cloud-tencent#700]
https://github.com/polarismesh/polaris/issues/781#issue-1434392105

**Comment by SkyeBeFreeman** [comment]
可以使用 Spring Cloud Tencent 1.8.1-2021.0.3 版本

**Comment by opcooc** [comment]
> 可以使用 春云腾讯 1.8.1-2021.0.3 版本

好的 我试试 谢了
