### ISSUE TITLE
什么时候适配springboot2.7.x

### ISSUE THREAD

**Issue by luchaoyi9251** [Tencent/spring-cloud-tencent#709]
新项目使用的springboot2.7.x，发现似乎目前支持到springboot2.6.x

**Comment by SkyeBeFreeman** [comment]
我们这边验证一下，使用 `1.8.1-2021.0.3`

**Comment by SkyeBeFreeman** [comment]
这里看了下是支持的，版本文档也已更新，可以对比一下自己的 Spring Boot 版本。[Spring Cloud Tencent 版本管理](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-%E7%89%88%E6%9C%AC%E7%AE%A1%E7%90%86)

**Comment by herodotus-ecosystem** [comment]
适配 2.7 不是什么问题。 适配 3.0 才是难点。还有10天发布。

**Comment by SkyeBeFreeman** [comment]
> 适配 2.7 不是什么问题。 适配 3.0 才是难点。还有10天发布。

适配 3.0 已在进行中，可以查看 2022 分支。欢迎参与开源共建🚀

**Comment by lepdou** [comment]
目前已经初步完成 Spring Cloud 2022 版本适配。适配 Spring 6.0，Spring boot 3.0 ，有兴趣的同学可以用 2022.0 分支体验一下

**Comment by herodotus-ecosystem** [comment]
大佬们，Spring Cloud 2022 版本适配，适配差不多，能不能先发个 M 版，或者 RC版。自己的微服务框架，原先用的 ali 系（更新太慢），打算先改动到 tencent，能跑起来之后，慢慢了解熟悉。熟悉之后再来参与个贡献。

**Comment by lepdou** [comment]
> 大佬们，Spring Cloud 2022 版本适配，适配差不多，能不能先发个 M 版，或者 RC版。自己的微服务框架，原先用的 ali 系（更新太慢），打算先改动到 tencent，能跑起来之后，慢慢了解熟悉。熟悉之后再来参与个贡献。

@herodotus-cloud 
 没问题。我们内部跑个自动化回归一下之后，下周发个M版本之类的，到时候通知你

**Comment by herodotus-ecosystem** [comment]
> > 大佬们，Spring Cloud 2022 版本适配，适配差不多，能不能先发个 M 版，或者 RC版。自己的微服务框架，原先用的 ali 系（更新太慢），打算先改动到 tencent，能跑起来之后，慢慢了解熟悉。熟悉之后再来参与个贡献。
> 
> @herodotus-cloud 没问题。我们内部跑个自动化回归一下之后，下周发个M版本之类的，到时候通知你

效率真高！那我也提前学习学习 spring cloud tencent。
