### ISSUE TITLE
【需求认领】 2020/2021 版本 RestTemplate 支持 spring-retry 熔断能力

### ISSUE THREAD

**Issue by lepdou** [Tencent/spring-cloud-tencent#712]
# 背景

spring-retry 是广泛使用的重试和熔断框架。在以下场景压测的时候发现，Hoxton 版本基本能做到无错误请求，但是 2020/2021 小部分请求会失败。

- 压测场景：A 调 B，B有两个实例 B1，B2。压测过程中，kill B1。

## 原因

Hoxton 版本默认用的 Netflix ribbon 负载均衡器，内置了熔断的能力，核心代码逻辑如下：

1. 重试核心入口：
![image](https://user-images.githubusercontent.com/4991116/200725964-a5750d15-319b-47b5-a8c7-59f11660b0c7.png)

2. Ribbon 处理异常
![image](https://user-images.githubusercontent.com/4991116/200727923-fcbbd666-fd81-43a9-910a-ca3899581a04.png)

![image](https://user-images.githubusercontent.com/4991116/200728131-589a47c5-0e00-41c3-adb9-61aeb2f94375.png)

3. 负载均衡时，过滤被熔断的实例
![image](https://user-images.githubusercontent.com/4991116/200728366-235a6dcd-d53c-4c69-8752-b89968b0114c.png)

![image](https://user-images.githubusercontent.com/4991116/200728879-dc7fbc31-5c01-459e-a655-c5b337a88fe2.png)

通过 ribbon 内置的熔断机制，能够在一次请求内部重试阶段就剔除掉有问题的实例。SCT 的熔断则只能上报一次完整调用的结果，从而触发熔断，灵敏度不如 ribbon 内置的熔断。

2020/2021 版本使用的是 Spring Cloud Loadbalancer，简单看了一下，并不支持 ribbon 这样的熔断能力。

# 需求目标

参考 ribbon 的实现，在 SCT 里实现简化版 ribbon 的熔断能力？

简单想了一下主要有两个核心点：

1. 实现一个 LoadBalancedRetryPolicy ，参考 RibbonLoadBalancedRetryPolicy
2. 在 PolarisLoadBalancer 里实现过滤掉被熔断的实例

可以通过 SCT 项目里的 router example 测试。

# 其它
或者 2020/2021 已经有类似的实现了？我没发现(⊙o⊙)…

**Comment by dongyinuo** [comment]
需要的话，我可以认领，不过需要 下周才能介入

**Comment by SkyeBeFreeman** [comment]
> 需要的话，我可以认领，不过需要 下周才能介入

可以的，不过这里建议先调研和复现一下，看看为啥会小部分请求会失败，然后抛出来讨论一下

**Comment by lepdou** [comment]
@dongyinuo 

可以的哈，时间上不急的~ 感谢

**Comment by lepdou** [comment]
发现在 RetryAwareServiceInstanceListSupplier 实现里，重试的时候，会过滤掉上一次选中的节点，通过这种方式避免了重试的时候重复选中有问题节点。

![image](https://user-images.githubusercontent.com/4991116/206666546-ecfafc66-c3c0-4a3e-9506-b91971456d0d.png)
