### ISSUE TITLE
📣 开放讨论📣 Spring Cloud 2022 它来了，你关注吗？

### ISSUE THREAD

**Issue by lepdou** [Tencent/spring-cloud-tencent#735]
# 导语
`Spring Framework 6.0` 已于近期正式发布 GA 版本，按照原定计划，`Spring Boot 3.0` 也将会在 `11月24日` 正式 GA。紧接着 `Spring Cloud 2022` 也将会跟进发布，至此：

````
- Java 17
- Spring Framework 6.0
- Spring Boot 3.0
- Spring Cloud 2022
````

将会成为下一代主流的 Java 技术栈。

# 纯文明开放技术讨论

您有任何关于 Spring 相关的想法，都可以直接在 Issue 下留言回复讨论。

- 有人觉得 Spring 给 Java 提供了强大的支持，有人则觉得Java 本身不重，但是有了 Spring 这套技术栈，变的非常臃肿，导致学习门槛变高，使用门槛变高。Spring 的孰是孰非您觉得呢？

- 现如今是云原生时代，Go 等语言更加贴近云原生。Java 已是廉颇老矣？

- 如今互联网行业寒冬，会不会同时降低企业主、技术人员对于新技术的学习热情？“不折腾了，能用即可，懒得升级”

- ... ...

---

# Introduction
`Spring Framework 6.0` has officially released the GA version recently. According to the original plan, `Spring Boot 3.0` will also be officially GA on `November 24`. Immediately afterwards `Spring Cloud 2022` will also be released, so far:

````
- Java 17
- Spring Framework 6.0
- Spring Boot 3.0
- Spring Cloud 2022
````

It will become the next generation mainstream Java technology stack.

# Pure Civilization Open Technology Discussion

If you have any ideas about Spring, you can leave a message directly under the Issue to reply to the discussion.

- Some people think that Spring provides strong support for Java, while others think that Java itself is not important, but with Spring's technology stack, it becomes very bloated, which leads to higher learning threshold and higher usage threshold. What do you think is the pros and cons of Spring?

- Now is the era of cloud native, and languages ​​such as Go are closer to cloud native. Java is quite old?

- Will the current cold winter of the Internet industry reduce the enthusiasm of business owners and technicians for learning new technologies? "Don't worry about it, just use it, don't bother to upgrade"

-...

**Comment by lepdou** [comment]
📣 欢迎大家加入讨论~

**Comment by DerekYRC** [comment]
Java别跑太快，等一等灵魂，我还在用Java8

**Comment by lepdou** [comment]
> Java别跑太快，等一等灵魂，我还在用Java8

@DerekYRC 重新开了一个 issue，这个issue 显示历史标题更改记录，有点乱(⊙o⊙)…

**Comment by lepdou** [comment]
这个我先关了
