### ISSUE TITLE
📣 开放讨论📣 Spring Cloud 2022 它来了，你关注吗？

### ISSUE THREAD

**Issue by lepdou** [Tencent/spring-cloud-tencent#736]
# 导语
`Spring Framework 6.0` 已于近期正式发布 GA 版本，按照原定计划，`Spring Boot 3.0` 也将会在 `11月24日` 正式 GA。紧接着 `Spring Cloud 2022` 也将会跟进发布，至此：

````
- Java 17
- Spring Framework 6.0
- Spring Boot 3.0
- Spring Cloud 2022
````

将会成为下一代主流的 Java 技术栈。Spring Cloud Tencent 适配 Spring Cloud 2022 第一个版本（1.8.1-2022.0.0-RC2）已发布。

# 纯文明开放技术讨论

您有任何关于 Spring 相关的想法，都可以直接在 Issue 下留言回复讨论。

- 有人觉得 Spring 给 Java 提供了强大的支持，有人则觉得Java 本身不重，但是有了 Spring 这套技术栈，变的非常臃肿，导致学习门槛变高，使用门槛变高。Spring 的孰是孰非您觉得呢？

- 现如今是云原生时代，Go 等语言更加贴近云原生。Java 已是廉颇老矣？

- 如今互联网行业寒冬，会不会同时降低企业主、技术人员对于新技术的学习热情？“不折腾了，能用即可，懒得升级”

- ... ...

---

# Introduction
`Spring Framework 6.0` has officially released the GA version recently. According to the original plan, `Spring Boot 3.0` will also be officially GA on `November 24`. Immediately afterwards `Spring Cloud 2022` will also be released, so far:

````
- Java 17
- Spring Framework 6.0
- Spring Boot 3.0
- Spring Cloud 2022
````

It will become the next generation mainstream Java technology stack. The work of Spring Cloud Tencent to adapt Spring Cloud 2022 is in progress, see the [2022.0 branch](https://github.com/Tencent/spring-cloud-tencent/tree/2022.0).

# Pure Civilization Open Technology Discussion

If you have any ideas about Spring, you can leave a message directly under the Issue to reply to the discussion.

- Some people think that Spring provides strong support for Java, while others think that Java itself is not important, but with Spring's technology stack, it becomes very bloated, which leads to higher learning threshold and higher usage threshold. What do you think is the pros and cons of Spring?

- Now is the era of cloud native, and languages ​​such as Go are closer to cloud native. Java is quite old?

- Will the current cold winter of the Internet industry reduce the enthusiasm of business owners and technicians for learning new technologies? "Don't worry about it, just use it, don't bother to upgrade"

-...

**Comment by lepdou** [comment]
📣 欢迎大家畅所欲言，加入讨论~

**Comment by ghost** [comment]
你发任你发，我用Java8

**Comment by DerekYRC** [comment]
哪位小伙伴能准备给出云原生的定义吗？

**Comment by wenyu7980** [comment]
spring层面：Spring native会是未来吗？
java层面：虚拟线程是未来，响应式编程能否一战？

**Comment by youtaqiu** [comment]
基于graalvm的spring native,看起来解决了内存占用高,启动速度慢的问题,但是兼容性是一个大问题,同时编译打包的速度应该会慢很多.不过大方向应该没错.

**Comment by lepdou** [comment]
> 哪位小伙伴能准备给出云原生的定义吗？

哈哈，我感觉云原生这个概念被妖魔化了。这年头不搭上“云原生”，技术就是落后的。各种云原生，比如云原生中间件、云原生数据库。。。

**Comment by lxcecho** [comment]
有些企业压根用不上云原生，感觉这玩意儿被魔化了...

**Comment by lepdou** [comment]
> 有些企业压根用不上云原生，感觉这玩意儿被魔化了...

感觉大部分人简单定义“跑在 k8s 上，就是云原生”？

**Comment by SkyeBeFreeman** [comment]
> 哪位小伙伴能准备给出云原生的定义吗？

个人拙见，抛砖引玉哈~

- 狭义上，云原生是 CNCF 基金会下的开源项目。
- 广义上，云原生是一个，计算资源可灵活分配和调度、应用服务可观测可弹性伸缩、DevOps可便捷操作，的软件系统。

**Comment by magestacks** [comment]
> 哪位小伙伴能准备给出云原生的定义吗？

宽泛来说，这个算是容易明白的。

![wecom-temp-209993-b6e383c33af1925e5d8e696dfab8d416](https://user-images.githubusercontent.com/77398366/203502530-93ade7f7-496d-4e58-b754-96918ad896f5.jpg)

**Comment by 77321660** [comment]
2021升级到2022，已有的工程修改量有多大？

**Comment by lepdou** [comment]
> 2021升级到2022，已有的工程修改量有多大？

SCT 我改造了一把，还好。主要就是 javax 的改改

**Comment by lwl8023** [comment]
all in native

**Comment by misselvexu** [comment]
Mark

**Comment by weihubeats** [comment]
云原生: 用go都是云原生(手动狗头)

**Comment by herodotus-ecosystem** [comment]
> > 有些企业压根用不上云原生，感觉这玩意儿被魔化了...
> 
> 感觉大部分人简单定义“跑在 k8s 上，就是云原生”？

### 升级 spring cloud 2022 大多数问题都不大。我总结下来就几类问题：

1. 更换 JDK 17 后，少部分第三方依赖包版本选择和控制问题
2. javax 等包名变更 jakarta 问题（就是体力活加上强迫症），不改也行。
3. 新依赖包过时代码替换。大多数没问题，就怕遇到像 spring security 6 用法的变化。
4. starter 自动配置注册格式不同导致的，大多数第三方依赖都倒在这里
5. 最怕的就是核心机制的变化，比如说反射。好像一些反射在 JDK 17 会有问题。
6. 最大的问题就是基础设置组件升级不同步或者缓慢问题，比如说 spring cloud alibaba。这可能会导致更换组件，修改配置等。(还是 spring cloud tencent 响应快，我正打算换过来试试)
7. 如果还要考虑向下的兼容性，怕就难了。

**Comment by herodotus-cloud** [comment]
> > > 有些企业压根用不上云原生，感觉这玩意儿被魔化了...
> > 
> > 
> > 感觉大部分人简单定义“跑在 k8s 上，就是云原生”？
> 
> ### 升级 spring cloud 2022 大多数问题都不大。我总结下来就几类问题：
> 1. 更换 JDK 17 后，少部分第三方依赖包版本选择和控制问题
> 2. javax 等包名变更 jakarta 问题（就是体力活加上强迫症）。
> 3. 新依赖包过时代码替换。大多数没问题，就怕遇到像 spring security 6 用法的变化。
> 4. starter 自动配置注册格式不同导致的，大多数第三方依赖都倒在这里
> 5. 最怕的就是核心机制的变化，比如说反射。好像一些反射在 JDK 17 会有问题。
> 6. 最大的问题就是基础设置组件升级不同步或者缓慢问题，比如说 spring cloud alibaba。这可能会导致更换组件，修改配置等。(还是 spring cloud tencent 响应快，我正打算换过来试试)
> 7. 如果还要考虑向下的兼容性，怕就难了。

**Comment by youtaqiu** [comment]
目前想使用SCT快照版,应该如何配置呢?

**Comment by SkyeBeFreeman** [comment]
> 目前想使用SCT快照版,应该如何配置呢?

@youtaqiu 可以参考这个[pom.xml](https://github.com/Tencent/spring-cloud-tencent/blob/2022.0/pom.xml)底部的 `<repositories>` 和 `<pluginRepositories>` 配置拉取快照版的Maven仓库，即可引入类似`1.8.1-2022.0.0-SNAPSHOT`的快照版SCT。

**Comment by youtaqiu** [comment]
> > 目标之前想使用SCT快照版，应该如何配置呢？
> 
> @youtaqiu可以参考这个[pom.xml](https://github.com/Tencent/spring-cloud-tencent/blob/2022.0/pom.xml)底部的`<repositories>`和`<pluginRepositories>`配置拉取快照版的Maven库，即可引入类似`1.8.1-2022.0.0-SNAPSHOT`的快照版SCT。

 @SkyeBeFreeman 谢谢.这种的我知道.关心的是有无类似spring公开的快照仓库.没有的话只能自己构建了.

**Comment by SkyeBeFreeman** [comment]
> > > 目标之前想使用SCT快照版，应该如何配置呢？
> > 
> > 
> > @youtaqiu可以参考这个[pom.xml](https://github.com/Tencent/spring-cloud-tencent/blob/2022.0/pom.xml)底部的`<repositories>`和`<pluginRepositories>`配置拉取快照版的Maven库，即可引入类似`1.8.1-2022.0.0-SNAPSHOT`的快照版SCT。
> 
> @SkyeBeFreeman 谢谢.这种的我知道.关心的是有无类似spring公开的快照仓库.没有的话只能自己构建了.

SCT快照版上传到 https://oss.sonatype.org/content/repositories/snapshots/ 这个中央仓库，可供拉取，详见：https://oss.sonatype.org/content/repositories/snapshots/com/tencent/cloud/

**Comment by SkyeBeFreeman** [comment]
Pre release of Spring Cloud Tencent v1.8.1 supporting Spring Cloud 2022.0.0-RC2 is here [1.8.1-2022.0.0-RC2](https://github.com/Tencent/spring-cloud-tencent/releases/tag/1.8.1-2022.0.0-RC2).

**Comment by herodotus-ecosystem** [comment]
> Pre release of Spring Cloud Tencent v1.8.1 supporting Spring Cloud 2022.0.0-RC2 is here [1.8.1-2022.0.0-RC2](https://github.com/Tencent/spring-cloud-tencent/releases/tag/1.8.1-2022.0.0-RC2).

感谢！正在试着用 spring cloud tencent 做改造了。

**Comment by lepdou** [comment]
@herodotus-cloud 
1.8.1-2022.0.0-RC2 已经发布正式版到中央仓库啦~

**Comment by Loongphy** [comment]
Javax 替换成 Jakarta也不算体力活，IDEA提供了相应的工具
https://www.jetbrains.com/idea/guide/tutorials/migrating-javax-jakarta/use-migration-tool/

**Comment by lfift** [comment]
可以从nacos平滑迁移吗

**Comment by chuntaojun** [comment]
> 可以从nacos平滑迁移吗

可以参考这个文档：https://polarismesh.cn/docs/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/%E5%AD%98%E9%87%8F%E6%9C%8D%E5%8A%A1%E8%BF%81%E7%A7%BB/nacos/

**Comment by zhengchalei** [comment]
啥时候能支持一下 Native Build
毕竟 SpringBoot3.0 主要就是做的这个

**Comment by lepdou** [comment]
> 啥时候能支持一下 Native Build 毕竟 SpringBoot3.0 主要就是做的这个

我们研究一下哈。之前没了解过这一块
