### ISSUE TITLE
polaris服务已经停掉，consumer还能调用到provider

### ISSUE THREAD

**Issue by tian-qingzhao** [Tencent/spring-cloud-tencent#742]
polaris服务端已经停掉了，客户端的服务调用者还能正常调用到服务提供者，且服务调用者通过springcloud服务发现往下跟踪，发现还能正常返回所有的实例，即使我把服务提供者的某一个实例下线掉，也能正常返回。请问有开关可以设置只获取健康的实例吗？
![image](https://user-images.githubusercontent.com/57293296/203988722-223846a7-b537-4c8e-b93d-a60e5c8009fe.png)

**Comment by SkyeBeFreeman** [comment]
由于polaris服务端下线，SCT便使用本地文件存储的服务实例信息进行调用（polaris/backup/文件夹下存放本地缓存）。由于polaris服务端下线，因此无法判定被调服务实例是否正常运行。如果想不调用到不可用实例，可以尝试使用熔断模块（`spring-cloud-starter-tencent-polaris-circuitbreaker`）。

**Comment by tian-qingzhao** [comment]
> 由于polaris服务端下线，SCT便使用本地文件存储的服务实例信息进行调用（polaris/backup/文件夹下存放本地缓存）。由于polaris服务端下线，因此无法判定被调服务实例是否正常运行。如果想不调用到不可用实例，可以尝试使用熔断模块（`spring-cloud-starter-tencent-polaris-circuitbreaker`）。

还需要引入其他模块，这样子看起来可能不是很友好吧，希望后续的功能可以支持吧。

**Comment by lepdou** [comment]
@tian-qingzhao 
当北极星服务端挂掉了，还能正常服务调用，这个是符合预期的基础容灾机制。试想如果注册中心挂了，所有服务调用失败了，那问题更大了。所有公司的注册中心都是这么设计的。

当北极星服务端挂掉的这段时间，服务提供者下线的事件，调用者肯定感知不到，这也是符合预期的。

理论上，当北极星服务端挂了，应该紧急处理故障：
1. 此时应该封锁paas 平台，不允许服务上下线
2. 紧急立马恢复北极星服务端

服务调用端引入熔断是锦上添花的操作，并不是作为容灾处理的常规手段。

**Comment by tian-qingzhao** [comment]
嗯嗯，一开始是我理解错了，非常感谢解答。

**Comment by tian-qingzhao** [comment]
嗯嗯，一开始是我理解错了，非常感谢解答。
