### ISSUE TITLE
服务中增加 circuitbreaker 依赖之后，无法正常启动

### ISSUE THREAD

**Issue by herodotus-ecosystem** [Tencent/spring-cloud-tencent#760]
## 环境

- Spring Boot 3.0.0
- Spring Cloud 2022.0.0-RC2
- Spring Cloud 1.8.1-2022.0.0-RC2

## 问题

目前个人项目正在做与 Spring Cloud Tencent 的整合。服务发现、服务注册、配置中心均已整合完成，并运行正常。

后打算加入服务熔断、限流等功能，所以按照 Github文档说明，在服务中增加了相关了依赖。再次启动服务之后，服务报错。

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method circuitBreakerConfigModifier in com.tencent.cloud.polaris.circuitbreaker.config.PolarisCircuitBreakerAutoConfiguration required a bean of type 'com.tencent.cloud.rpc.enhancement.config.RpcEnhancementReporterProperties' that could not be found.


Action:

Consider defining a bean of type 'com.tencent.cloud.rpc.enhancement.config.RpcEnhancementReporterProperties' in your configuration.

```

查阅代码后发现，在服务配置中增加，下面配置，服务即可正常运行。

```
spring:
  cloud:
    polaris:
     ......
      enabled: true
```

但是这样明显与相关代码的逻辑是违背的

```
@Configuration(proxyBeanMethods = false)
@ConditionalOnPolarisEnabled
@ConditionalOnProperty(value = "spring.cloud.tencent.rpc-enhancement.enabled", havingValue = "true", matchIfMissing = true)
@EnableConfigurationProperties(RpcEnhancementReporterProperties.class)
@AutoConfigureAfter(PolarisContextAutoConfiguration.class)
public class RpcEnhancementAutoConfiguration {
```

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.METHOD })
@ConditionalOnProperty(value = "spring.cloud.polaris.enabled", matchIfMissing = true)
public @interface ConditionalOnPolarisEnabled {

}
```

**Comment by SkyeBeFreeman** [comment]
@herodotus-cloud 请问你这里的配置，是在applicationl.yml里面还是bootstrap.yml里面配置的？

**Comment by herodotus-ecosystem** [comment]
> @herodotus-cloud 请问你这里的配置，是在applicationl.yml里面还是bootstrap.yml里面配置的？

是在 bootstrap.yml 里面配置的。

不过确实 matchIfMissing 这个参数很容易让人迷惑，所以我个人更倾向与自己写condition，清晰明了还可以输出日志方便调试。

```
public class TencentSmsEnabledCondition implements Condition {

    private static final Logger log = LoggerFactory.getLogger(TencentSmsEnabledCondition.class);

    @SuppressWarnings("NullableProblems")
    @Override
    public boolean matches(ConditionContext conditionContext, AnnotatedTypeMetadata metadata) {
        boolean result = PropertyResolver.getBoolean(conditionContext, SmsConstants.ITEM_TENCENT_ENABLED);
        log.debug("[Herodotus] |- Condition [Tencent Sms Enabled] value is [{}]", result);
        return result;
    }
}

```

**Comment by SkyeBeFreeman** [comment]
使用bootstrap.yml时的自动化配置在另一个类处理，参见`com.tencent.cloud.rpc.enhancement.config.RpcEnhancementBootstrapConfiguration`。

**Comment by herodotus-ecosystem** [comment]
> RpcEnhancementBootstrapConfiguration

嗯嗯，看到了。可能是我不了解细节，看着逻辑有点重复和混乱。

1. RpcEnhancementBootstrapConfiguration 中，条件是必须配置 `spring.cloud.polaris.enabled` 才能开启 `RpcEnhancementAutoConfiguration` 相关配置

> 这里用的是：@ConditionalOnProperty("spring.cloud.polaris.enabled")

```
@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty("spring.cloud.polaris.enabled")
@Import(RpcEnhancementAutoConfiguration.class)
public class RpcEnhancementBootstrapConfiguration {
}
```

2. 而在其它引用到 `RpcEnhancementAutoConfiguration` 的地方，包括`RpcEnhancementAutoConfiguration` 本身，其中使用的条件都是 `@ConditionalOnPolarisEnabled`，就是只要不手动指定 `spring.cloud.polaris.enabled` 的值为 false，都是开启注入状态。

> 这些地方用的是：@ConditionalOnPolarisEnabled。实际对应的是：@ConditionalOnProperty(value = "spring.cloud.polaris.enabled", matchIfMissing = true)

现在看到的几个地方

 `PolarisCircuitBreakerAutoConfiguration ` 引用到了 `RpcEnhancementAutoConfiguration`，包括 注解 `@ConditionalOnPolarisCircuitBreakerEnabled` 和 `RpcEnhancementAutoConfiguration` 内部，使用的条件都是 `@ConditionalOnPolarisEnabled`

```
// 1. PolarisCircuitBreakerAutoConfiguration 
@Configuration(proxyBeanMethods = false)
**@ConditionalOnPolarisCircuitBreakerEnabled**
@AutoConfigureAfter(RpcEnhancementAutoConfiguration.class)
public class PolarisCircuitBreakerAutoConfiguration {
```
```
// 2. ConditionalOnPolarisCircuitBreakerEnabled 
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
**@ConditionalOnPolarisEnabled**
@ConditionalOnProperty(name = "spring.cloud.polaris.circuitbreaker.enabled", matchIfMissing = true)
public @interface ConditionalOnPolarisCircuitBreakerEnabled {
}

```

```
// 3. RpcEnhancementAutoConfiguration 
@Configuration(proxyBeanMethods = false)
**@ConditionalOnPolarisEnabled**
@ConditionalOnProperty(value = "spring.cloud.tencent.rpc-enhancement.enabled", havingValue = "true", matchIfMissing = true)
@EnableConfigurationProperties(RpcEnhancementReporterProperties.class)
@AutoConfigureAfter(PolarisContextAutoConfiguration.class)
public class RpcEnhancementAutoConfiguration {
```

**Comment by SkyeBeFreeman** [comment]
这里是因为`BootstrapConfiguration`和`AutoConfiguration`的生效阶段不同导致的，需要区分两种方式的生效触发。

**Comment by herodotus-ecosystem** [comment]
可能确实是我功夫不到家，还是没有太理解。

是不是可以这样理解：

- 如果使用的“**不是**” bootstrap.yml，那么即使不配置任何信息，也会自动注入。因此也不会出现找不到 RpcEnhancementReporterProperties 情况。
- 如果使用的“**是**” bootstrap.yml，那么必须要手动配置 `spring.cloud.polaris.enabled`，开启相关注入。否则就会出现找不到 RpcEnhancementReporterProperties 情况。

我再好好消化消化，谢谢你耐心的回复。

**Comment by SkyeBeFreeman** [comment]
可以这样理解。

可以了解一下bootstrap.yml和application.yml在应用运行生命周期中的生效阶段有何不同。另外，在spring boot 2.7.0版本开始，spring cloud应用已经默认不使用bootstrap.yml作为配置文件读取了。

**Comment by herodotus-ecosystem** [comment]
> 可以这样理解。
> 
> 可以了解一下bootstrap.yml和application.yml在应用运行生命周期中的生效阶段有何不同。另外，在spring boot 2.7.0版本开始，spring cloud应用已经默认不使用bootstrap.yml作为配置文件读取了。

感谢指导！
