### ISSUE TITLE
服务A调用方法修改polaris某个配置信息，服务B监听到配置变化修改配置---这种方式是否有支持

### ISSUE THREAD

**Issue by opcooc** [Tencent/spring-cloud-tencent#761]
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by SkyeBeFreeman** [comment]
这里的配置具体是指polaris本身的系统配置，还是业务自身的配置？方便给出一个场景来描述需要这个功能的目的吗？目前SCT的标签传递支持传递到下游服务并让下游服务读取，但没有在内存中持久保存这个标签，而是线程级别的使用。

**Comment by lepdou** [comment]
@opcooc 指的是通过 sdk 修改配置中心的配置文件?

**Comment by opcooc** [comment]
> 这里的配置具体是指polaris本身的系统配置，还是业务自身的配置？方便给出一个场景来描述需要这个功能的目的吗？目前SCT的标签传递支持传递到下游服务并让下游服务读取，但没有在内存中持久保存这个标签，而是线程级别的使用。
1.业务配置(路由信息)
2.我这边是网关(spring cloud gateway)路由信息是存储在数据库，服务启动的时候读取一份，系统管理页面修改后通过消息队列通知所有网关再刷新下，想着如果集成spring-cloud-tencent的话是不是可以系统管理页面修改后直接保存到polaris里面并且省去了消息通知这一步直接动态刷新

**Comment by opcooc** [comment]
> 1.业务配置(路由信息)
> 2.我这边是网关(spring cloud gateway)路由信息是存储在数据库，服务启动的时候读取一份，系统管理页面修改后通过消息队列通知所有网关再刷新下，想着如果集成spring-cloud-tencent的话是不是可以系统管理页面修改后直接保存到polaris里面并且省去了消息通知这一步直接动态刷新

1.业务配置(路由信息)
2.我这边是网关(spring cloud gateway)路由信息是存储在数据库，服务启动的时候读取一份，系统管理页面修改后通过消息队列通知所有网关再刷新下，想着如果集成spring-cloud-tencent的话是不是可以系统管理页面修改后直接保存到polaris里面并且省去了消息通知这一步直接动态刷新

**Comment by opcooc** [comment]
> @opcooc 指的是通过 sdk 修改配置中心的配置文件?

恩恩 对

**Comment by lepdou** [comment]
> > 1.业务配置(路由信息)
> > 2.我这边是网关(spring cloud gateway)路由信息是存储在数据库，服务启动的时候读取一份，系统管理页面修改后通过消息队列通知所有网关再刷新下，想着如果集成spring-cloud-tencent的话是不是可以系统管理页面修改后直接保存到polaris里面并且省去了消息通知这一步直接动态刷新
> 
> 1.业务配置(路由信息) 2.我这边是网关(spring cloud gateway)路由信息是存储在数据库，服务启动的时候读取一份，系统管理页面修改后通过消息队列通知所有网关再刷新下，想着如果集成spring-cloud-tencent的话是不是可以系统管理页面修改后直接保存到polaris里面并且省去了消息通知这一步直接动态刷新

把路由配置放到北极星配置中心上是可以的，无缝对接。

**Comment by lepdou** [comment]
@opcooc 
https://polarismesh.cn/docs/%E5%8F%82%E8%80%83%E6%96%87%E6%A1%A3/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3/open_api/ 

可以参考一下这个文档，通过 openapi 可以修改并发布配置。

**Comment by opcooc** [comment]
> @opcooc https://polarismesh.cn/docs/%E5%8F%82%E8%80%83%E6%96%87%E6%A1%A3/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3/open_api/
> 
> 可以参考一下这个文档，通过 openapi 可以修改并发布配置。

好的 我瞅瞅学习学习
