### ISSUE TITLE
什么时候RPC的调用能增加dubbo 3.0 的接入

### ISSUE THREAD

**Issue by wolfewf** [Tencent/spring-cloud-tencent#781]
【需求认领】什么时候RPC的调用能增加dubbo 3.0 的接入

**Comment by lepdou** [comment]
@wolfewf 你指的 rpc 调用增加 dubbo 3.0 能详细说明一下不？

比如是用 feign的 client 去调用 dubbo 的服务端？具体的应用场景？

**Comment by JavaLionLi** [comment]
> @wolfewf 你指的 rpc 调用增加 dubbo 3.0 能详细说明一下不？
> 
> 比如是用 feign的 client 去调用 dubbo 的服务端？具体的应用场景？

框架用的springcloudalibaba 架构 rpc用dubbo替换的feign 全局使用dubbo3.0 所以在不改变dubbo3.0的情况下 想把sca改成sct 就这样的场景

**Comment by JavaLionLi** [comment]
看了北极星的文档 dubbo需要手动编写代码注册服务到北极星 而且不支持dubbo3.0 不知道什么时候可以支持一下

**Comment by SkyeBeFreeman** [comment]
dubbo 3.0 的北极星支持已完成，项目地址：https://github.com/polarismesh/dubbo-java-polaris 。
