### ISSUE TITLE
监控数据上报 为什么还要手动输入节点的host呢

### ISSUE THREAD

**Issue by dnlixiaoxin** [Tencent/spring-cloud-tencent#788]
spring.cloud.polaris.stat.enabled	监控数据采集开关
spring.cloud.polaris.stat.host	    Prometheus拉取客户端的IP地址
spring.cloud.polaris.stat.port	    Prometheus拉取客户端的端口号
spring.cloud.polaris.stat.path      Prometheus拉取客户端的请求路径

这个应该用服务的注册数据来拉取监控数据汇总完了展示吧，这个设计的目的在哪里呢

**Comment by SkyeBeFreeman** [comment]
不是必填的，允许自定义。

**Comment by SkyeBeFreeman** [comment]
https://github.com/Tencent/spring-cloud-tencent/wiki/RPC%E5%A2%9E%E5%BC%BA#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0

**Comment by dnlixiaoxin** [comment]
@SkyeBeFreeman 我按照上报wiki里的描述，可以实现限流功能，但是没有监控数据的上报，看上去我的配置有问题，请指教一下
 
spring: 
cloud:
    polaris:
      namespace: default # \u914D\u7F6E\u6CE8\u518C\u547D\u540D\u7A7A\u95F4
      address: grpc://127.0.0.1:8091
      discovery:
        enabled: true
      stat:
        enabled: true
        port: 38082

**Comment by dnlixiaoxin** [comment]
使用的是spring-cloud-tencent-startrt-all 依赖

**Comment by dnlixiaoxin** [comment]
我要使用的是拉取的模式，防止线上被push挂了，但是现在看上去是必须要配置节点的host，看上去是相悖的

**Comment by SkyeBeFreeman** [comment]
北极星用的是集群版还是单机版呢？然后看一下日志（polaris/logs/polaris.log），有无这样的日志。

```
2022-12-30 19:38:12.277 INFO [polaris-prometheus-http-2:c.t.p.p.s.p.h.HttpMetricHandler] Metrics is pulled by prometheus
```

**Comment by SkyeBeFreeman** [comment]
@chuntaojun cc

**Comment by dnlixiaoxin** [comment]
没有这个日志 是不是我的配置有问题

**Comment by dnlixiaoxin** [comment]
这个是我的配置
  cloud:
    polaris:
      namespace: default 
      address: grpc://127.0.0.1:8091
      discovery:
        enabled: true
      stat:
        enabled: true
        port: 38082

**Comment by dnlixiaoxin** [comment]
> 的
使用的是单机版本的 先在本地跑通

**Comment by dnlixiaoxin** [comment]
> 北极星用的是集群版还是单机版呢？然后看一下日志（polaris/logs/polaris.log），有无这样的日志。
> 
> ```
> 2022-12-30 19:38:12.277 INFO [polaris-prometheus-http-2:c.t.p.p.s.p.h.HttpMetricHandler] Metrics is pulled by prometheus
> ```
使用的是单机版本的 先在本地跑通

**Comment by chuntaojun** [comment]
原来机器有prometheus 吗

**Comment by dnlixiaoxin** [comment]
没有 我发现好像用1.13.4最新版本的polaris 提示安装prometheus失败 我装一个低版本的试试

**Comment by dnlixiaoxin** [comment]
@chuntaojun 就是polaris单机版本的一个bug 我给他们提一个pr 但是安装好了之后还是没有上报 我的配置如上

**Comment by chuntaojun** [comment]
1、我直接安装的 1.13.4 没有出现你这个问题
2、看下你的 prometheus 这个页面：http://127.0.0.1:9090/targets，是否有出现对应的 target，prometheus已经配置了 polaris 的 http_sd 发现

**Comment by chuntaojun** [comment]
![Screenshot 2022-12-31 at 12 40 01](https://user-images.githubusercontent.com/23445172/210125095-ed242188-bf39-4dc7-bed3-80884bfc365f.png)

**Comment by dnlixiaoxin** [comment]
@chuntaojun 我刚买了一个腾讯云的服务器，安装了一下单机polaris，看上去是有的，我在我本地启动一个服务，没有需要上报的节点数据，是配置还是端口没开放呢
<img width="1730" alt="image" src="https://user-images.githubusercontent.com/32609939/210125602-b0bd09c9-9d48-4e24-9350-351d09c49350.png">

**Comment by chuntaojun** [comment]
可用 1.13.5 的版本，修复了单机版本安装 prometheus 失败的问题

**Comment by chuntaojun** [comment]
> @chuntaojun 我刚买了一个腾讯云的服务器，安装了一下单机polaris，看上去是有的，我在我本地启动一个服务，没有需要上报的节点数据，是配置还是端口没开放呢 <img alt="image" width="1730" src="https://user-images.githubusercontent.com/32609939/210125602-b0bd09c9-9d48-4e24-9350-351d09c49350.png">

curl http://localhost:9000/prometheus/v1/clients

看下这个有返回没有

**Comment by dnlixiaoxin** [comment]
> > @chuntaojun 我刚买了一个腾讯云的服务器，安装了一下单机polaris，看上去是有的，我在我本地启动一个服务，没有需要上报的节点数据，是配置还是端口没开放呢 <img alt="image" width="1730" src="https://user-images.githubusercontent.com/32609939/210125602-b0bd09c9-9d48-4e24-9350-351d09c49350.png">
> 
> curl http://localhost:9000/prometheus/v1/clients
> 
> 看下这个有返回没有

没有返回
<img width="597" alt="image" src="https://user-images.githubusercontent.com/32609939/210131897-6d9690f4-c8ad-4e50-8ef5-6ac2a50192dd.png">
如下是我的项目配置
<img width="384" alt="image" src="https://user-images.githubusercontent.com/32609939/210131917-b5e6a708-81cb-470d-87aa-a6bbad221331.png">

pom配置如下：
<img width="614" alt="image" src="https://user-images.githubusercontent.com/32609939/210131954-de1257b8-806f-4d67-8c0b-841648251e8d.png">
版本如下：
springboot:2.6.9
spring-cloud-starter-tencent-all: 1.8.1-2021.0.3
spring-cloud-starter-bootstrap：3.1.3

我把测试的服务部署到腾讯云服务上也不可以

**Comment by chuntaojun** [comment]
你把你本地的 polaris java 日志打包发出来下，正常这样子配置是会有的

**Comment by dnlixiaoxin** [comment]
> 你把你本地的 polaris java 日志打包发出来下，正常这样子配置是会有的
[polaris.zip](https://github.com/Tencent/spring-cloud-tencent/files/10330954/polaris.zip)

**Comment by chuntaojun** [comment]
调整下 polaris-java 的日志级别为 debug，

OGGER.debug("Report prometheus http server metadata success, response:{}", reportClientResponse);

看下有没有这个例子打印

**Comment by chuntaojun** [comment]
设置自定义的 polaris-java sdk 日志配置文件读取：

启动命名添加参数 -Dpolaris.logging.config=xxx

参考的日志配置文件

https://github.com/polarismesh/polaris-java/tree/main/polaris-common/polaris-logging/src/main/resources

**Comment by chuntaojun** [comment]
可以先试一下 demo，看下是否能够正常让 prometheus 从北极星服务端拿到 targets 数据

https://github.com/Tencent/spring-cloud-tencent/tree/2021.0/spring-cloud-tencent-examples/polaris-discovery-example

**Comment by dnlixiaoxin** [comment]
> polaris.logging.config

demo项目可以获取到，虽然是down状态
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/32609939/210231845-46cc46db-4144-422d-aaa6-13410746b938.png">

**Comment by chuntaojun** [comment]
demo 持续运行，然后还是 shutdown 状态？

**Comment by dnlixiaoxin** [comment]
> demo 持续运行，然后还是 shutdown 状态？

对 但是应该是网络原因 一个polaris在腾讯云 服务在本地

**Comment by dnlixiaoxin** [comment]
> 设置自定义的 polaris-java sdk 日志配置文件读取：
> 
> 启动命名添加参数 -Dpolaris.logging.config=xxx
> 
> 参考的日志配置文件
> 
> https://github.com/polarismesh/polaris-java/tree/main/polaris-common/polaris-logging/src/main/resources

我用的是springcloud-tencent 有其他的方法调debug级别么

**Comment by dnlixiaoxin** [comment]
> 
[polaris.zip](https://github.com/Tencent/spring-cloud-tencent/files/10331713/polaris.zip)
没有这个日志

**Comment by dnlixiaoxin** [comment]
> 设置自定义的 polaris-java sdk 日志配置文件读取：
> 
> 启动命名添加参数 -Dpolaris.logging.config=xxx
> 
> 参考的日志配置文件
> 
> https://github.com/polarismesh/polaris-java/tree/main/polaris-common/polaris-logging/src/main/resources

我详细对比了一下配置，找到问题了，必须配置到bootstrap.yml文件里，而且必须配置上spring.cloud.polaris.enabled=true 才可以，和wiki上有出入

**Comment by dnlixiaoxin** [comment]
> demo 持续运行，然后还是 shutdown 状态？
可以拿到targets了 但是监控数据还是不展示
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/32609939/210239322-9402e552-9a6e-4694-95e9-b2eb29a36ea3.png">

**Comment by dnlixiaoxin** [comment]
@chuntaojun 这个是bug么，还需要我提供什么方便你定位么

**Comment by chuntaojun** [comment]
prometheus和你的sct应用网络是双向可通的吗？

**Comment by chuntaojun** [comment]
我刚刚测试了下 sct 的 polaris-discovery-example，没有发现这个问题

我是直接在我的电脑上安装北极星单机版 & 启动 sct 应用的

**Comment by chuntaojun** [comment]
<img width="1712" alt="Screenshot 2023-01-03 at 22 03 17" src="https://user-images.githubusercontent.com/23445172/210372501-ff2485c2-74d1-4927-9c0f-7b5a5fd402d2.png">

**Comment by dnlixiaoxin** [comment]
> prometheus和你的sct应用网络是双向可通的吗？

双向可通，我把服务和prometheus部署到同一台腾讯云上

**Comment by chuntaojun** [comment]
你可以直接 curl 下 target 的 url，先触发 sct demo 的调用多次，然后 curl 下 target 的 url，看下 metrics 数据，是否有
<img width="446" alt="Screenshot 2023-01-03 at 22 04 52" src="https://user-images.githubusercontent.com/23445172/210372733-ee508fe6-cd4a-4693-bdc2-42ec3c2972eb.png">

**Comment by dnlixiaoxin** [comment]
> 你可以直接 curl 下 target 的 url，先触发 sct demo 的调用多次，然后 curl 下 target 的 url，看下 metrics 数据，是否有 <img alt="Screenshot 2023-01-03 at 22 04 52" width="446" src="https://user-images.githubusercontent.com/23445172/210372733-ee508fe6-cd4a-4693-bdc2-42ec3c2972eb.png">

两次的target都是demo的请求路径么

**Comment by chuntaojun** [comment]
<img width="560" alt="Screenshot 2023-01-03 at 22 24 50" src="https://user-images.githubusercontent.com/23445172/210376309-3e3eb71c-9ac8-4155-8fda-af5b732e2ac6.png">

这个

**Comment by chuntaojun** [comment]
直接从目标节点看下 metrics 数据

**Comment by dnlixiaoxin** [comment]
> 直接从目标节点看下 metrics 数据
目标节点看metrics数据 是指什么

**Comment by dnlixiaoxin** [comment]
重装了腾讯云服务器，重新安装了最新版本的polaris，打包了最新的demo服务到腾讯云上，还是看不到数据，算了，不搞了

**Comment by dnlixiaoxin** [comment]
关闭了

**Comment by chuntaojun** [comment]
这个问题我们处理下，确实存在bug，但是还在找原因

**Comment by chuntaojun** [comment]
@dnlixiaoxin 问题已确定，手动依赖 polaris 下，把polaris的依赖调整为 1.10.1 即可

**Comment by chuntaojun** [comment]
<dependency>
				<artifactId>polaris-dependencies</artifactId>
				<groupId>com.tencent.polaris</groupId>
				<version>${polaris.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

应该在你的项目里面把这个调整为 1.10.1 即可

**Comment by dnlixiaoxin** [comment]
> ```
> 		<dependency>
> 			<artifactId>polaris-dependencies</artifactId>
> 			<groupId>com.tencent.polaris</groupId>
> 			<version>${polaris.version}</version>
> 			<type>pom</type>
> 			<scope>import</scope>
> 		</dependency>
> ```
> 
> 应该在你的项目里面把这个调整为 1.10.1 即可

麻烦springcloud-tencent 2021更新完后 再call我一下 谢谢

**Comment by dnlixiaoxin** [comment]
@chuntaojun 好像还是不行，polaris server使用的是1.13.5 
项目配置如下
<img width="696" alt="image" src="https://user-images.githubusercontent.com/32609939/210694135-3ba78550-8986-4488-ba1e-2fd456bdfc42.png">

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/32609939/210694194-ef6a0924-5260-4747-91da-fda379d5bc8c.png">

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/32609939/210694464-bbc4c314-a5cf-44d0-9a16-5280ad657b5e.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32609939/210694700-0fae8def-0dde-4dbb-987a-efddf75ac2d1.png">
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/32609939/210694787-a408e4cd-d412-486c-8e22-2533febcd283.png">


看上去数据确实被采集了 看日志是被prometheus pull了 但是看上去prometheus上没数据 没收集到

**Comment by dnlixiaoxin** [comment]
还是有问题

监控面板 一会能看到一会看不到

**Comment by chuntaojun** [comment]
> 可以了 忽略

采集到了是吧？

**Comment by dnlixiaoxin** [comment]
> > 可以了 忽略
> 
> 采集到了是吧？

采集到了 但是面板一会能看到一会看不到
