### ISSUE TITLE
配置中心功能，直接指定key即可，可以增加定制el或者注解，而不用手动的指定配置文件，这样用户体验会提升很多

### ISSUE THREAD

**Issue by dnlixiaoxin** [Tencent/spring-cloud-tencent#789]
**What is the feature you want to add?**
配置中心功能，直接指定key即可，可以增加定制el或者注解，而不用手动的指定配置文件，支持非文件方式，而是key的方式，这样用户体验会提升很多

**Why do you want to add this feature?**
现在的设计不是很好

**How to implement this feature?**
通过自定义注解或el让用户来指定配置的key
例如
@PolarisValue("aaaaa")

**Additional context**

**Comment by lepdou** [comment]
这里有个核心问题：如果以 key 的方式，那么客户端怎么知道从北极星服务端拉取哪些配置文件呢？

另外，spring 的配置模型里，都是以配置文件的形式注入到容器里。使用的时候，可以通过 @Value 的方式注入key。所以，我理解这个地方还好？符合spring的配置模型。

@PolarisValue("aaaaa") 这种方式，sct定义了一个自定义的注解。这种设计其实也不太好，因为在spring 生态里，尽量都适配 spring 的编程界面。这样应用就不用跟具体的实现绑定了，也不用多学习一套编程api。都沿用 spring 定义的规范。这也是spring 最大的价值所在。

**Comment by dnlixiaoxin** [comment]
对的 close了

**Comment by SkyeBeFreeman** [comment]
@dnlixiaoxin 这些配置文件是自动注入的，无需手动指定，可以把key-value放在这里面。参考文档：https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Config-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#2-%E6%B3%A8%E5%85%A5%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by dnlixiaoxin** [comment]
> @dnlixiaoxin 这些配置文件是自动注入的，无需手动指定，可以把key-value放在这里面。参考文档：https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Config-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#2-%E6%B3%A8%E5%85%A5%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

我的想法是全部放倒上述的文件里，随着业务的扩展，逐渐就不能维护了，而额外的写文件，还需要手动的指定文件名称，如果可以以自定义注解 支持json的解析与反解析 自动生成对象等 是不是就很好用了呢 或者用PolariConig.getKey("")是不是也行？

**Comment by SkyeBeFreeman** [comment]
配置的原始数据如何维护呢？你这里只说了一种加载配置的方式，而这条链路可能需要从SDK到后端服务的配合。

**Comment by dnlixiaoxin** [comment]
> 配置的原始数据如何维护呢？你这里只说了一种加载配置的方式，而这条链路可能需要从SDK到后端服务的配合。

原始数据指的什么？ 如果指的polaris服务端怎么配置可以有目录a.b.c 以这种方式指定key，用户创建key的时候，可以指定类型 List 还是什么方式，这样也方便我们反序列化，而且方便用户根据业务来制定目录。
如果说的是数据怎么写，就只支持json即可
如果说的是初始化，直接根据key去取数据，完了初始化到本地，这个就非常简单了吧

**Comment by SkyeBeFreeman** [comment]
那可以理解为，还是指定了文件名，只不过不需要在bootstrap.yml或者application.yml里面指定，而是在代码里面直接用注解的方式指定，例如原本配置k=v在application.yml里面，可以改成用application.k=v的方式获取？

**Comment by dnlixiaoxin** [comment]
> 那可以理解为，还是指定了文件名，只不过不需要在bootstrap.yml或者application.yml里面指定，而是在代码里面直接用注解的方式指定，例如原本配置k=v在application.yml里面，可以改成用application.k=v的方式获取？

你说的这个并不是一个核心的问题，核心的点如下：
1.通过目录管理来区分业务，但是现在好像也可以创建目录
2.避免application.yml或者其他的默认的注入配置的未来不可避免的膨胀与不可维护问题
3.使用代码的方式来解放我们来手动写配置文件的路径，我已经脑补到未来有几百个文件需要写到bootstrap.yml或者application.yml里面
4.通过目录方式，可以来单一维护我自己关注的配置并且可以支持我直接的反序列化，避免我误操作引起的其他的配置问题，例如加开关 我直接搜索到我的配置 由0 改为 1确定发布
5.而且我认为spring的application只是一个配置文件，是spring为了整合配置的地方，说他来代表一个配置中心过于勉强了，配置中心应该具有灵活与通用性，配置中心大于配置文件
6.还有辛苦尽快解决一下监控的问题，我都搞了一周了，昨天搞到12点都没搞定，心态直接崩了。

**Comment by chuntaojun** [comment]
6.还有辛苦尽快解决一下监控的问题，我都搞了一周了，昨天搞到12点都没搞定，心态直接崩了。
----

这个已经在 polaris-java 1.10.x 开始修复了，您提的另外一个 issue 我回复了，你可以按照这个解决下

**Comment by SkyeBeFreeman** [comment]
@dnlixiaoxin 目前配置中心已有目录的方式进行管理，你的问题应该是需要指定文件名才能引入相关配置文件，而想有一种能够不用指定文件名的方式引入配置吧？前面用application.yml只是举例，也可以换成任意一个配置文件，比如app/custom.properties这样一个目录文件，里面有一个配置k=v，原本是需要在application.yml里面指定app/custom.properties才能引入k=v这个配置，你的想法是能有一个代码直接引入的方式，比如`@Value("app.custom.k")`的方式来获取v，我的理解没错吧？

**Comment by dnlixiaoxin** [comment]
> 

太棒了 我今天下班后试一下

**Comment by dnlixiaoxin** [comment]
> @dnlixiaoxin 目前配置中心已有目录的方式进行管理，你的问题应该是需要指定文件名才能引入相关配置文件，而想有一种能够不用指定文件名的方式引入配置吧？前面用application.yml只是举例，也可以换成任意一个配置文件，比如app/custom.properties这样一个目录文件，里面有一个配置k=v，原本是需要在application.yml里面指定app/custom.properties才能引入k=v这个配置，你的想法是能有一个代码直接引入的方式，比如`@Value("app.custom.k")`的方式来获取v，我的理解没错吧？

结果是一样的，但是文件的方式是不好进行一个对象的维护，按照我所说的方式进行维护，会更好的切割不同配置而且可以pretty下，这样人机交互会更好,而且为啥一定是要和文件强绑定，就只是为了match spring的配置文件么

**Comment by chuntaojun** [comment]
> 

北极星的配置中心是文件级别的设计，的先知道要从北极星拉取哪些配置文件，然后才能把这些配置文件解析为 key-value 的形式

**Comment by dnlixiaoxin** [comment]
如我上面所述，是可以获取到的，而且我看apollo、nacos这些开源的以及我经过的几家公司自研的这些配置中心，好像都是key的设计？

**Comment by chuntaojun** [comment]
nacos 是文件级别的，你说的 @NacosValue，也是需要先知道引入哪些nacos的 dataId，才能使用 @NacosValue 注入

**Comment by dnlixiaoxin** [comment]
公司A: 通过类似Polaris.getKey("")的方式，当用户调用的时候，才会去获取，完了server即时通知与client长轮询拉取
公司B:与A差不太多，但是是通过注解的方式去解决
这两种使用方式对使用者友好太多，当然我是站在使用者角度看这个问题，你们还要考虑目前的架构，你们决策吧
