### ISSUE TITLE
OpenFeign调用出现 Load balancer does not contain an instance for the service

### ISSUE THREAD

**Issue by lhzsdnu** [Tencent/spring-cloud-tencent#790]
环境
    Spring Boot 2.7.7、Spring Cloud 2021.0.5、Spring Cloud  Tencent 1.8.1-2021.0.3

问题
    使用OpenFeign调用，通过接口调用正常，通过@Test调用报错Load balancer does not contain an instance for the service
    如果先使用RestTemplate调用，本地生成缓存后，再使用OpenFeign通过@Test调用正常

**Comment by SkyeBeFreeman** [comment]
方便贴一下代码吗？

**Comment by lhzsdnu** [comment]
![image](https://user-images.githubusercontent.com/20517550/210352236-c015550e-6f2f-4ad9-a2d2-f98ccd8a82b0.png)

**Comment by lhzsdnu** [comment]
![image](https://user-images.githubusercontent.com/20517550/210352454-282ea9c2-ff96-4dd3-a9f7-dd5569d78402.png)

**Comment by SkyeBeFreeman** [comment]
@lhzsdnu 我这边尝试是正常的，在

**Comment by SkyeBeFreeman** [comment]
@lhzsdnu 我这边尝试是正常的，在`polaris-discovery-example`项目内运行如下单测代码：

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = DiscoveryCallerService.class)
public class DiscoveryCalleeServiceTest {

	@Autowired
	private DiscoveryCalleeService discoveryCalleeService;

	@Test
	public void testFeign() {
		int val = discoveryCalleeService.sum(1, 2);
		System.out.println(val);
		assertThat(val).isEqualTo(3);
	}
}
```
