### ISSUE TITLE
About spring cloud 2020.x.x support

### ISSUE THREAD

**Issue by RaphielAinsworth** [Tencent/spring-cloud-tencent#8]
have any plans or when to release SpringCloud 2020.x.x version support ?

**Comment by andrewshan** [comment]
we plan to release in 2022 early, will you interest to contribute this feature?

**Comment by chuntaojun** [comment]
At present, we have realized the initial docking of spring cloud 2020.x, the code is already in the corresponding branch, and it is still being tested. If you are interested, can we invite you to join us?

**Comment by SkyeBeFreeman** [comment]
@RaphielAinsworth  Spring Cloud Tencent for 2020.0.5 will release in this week.
