### ISSUE TITLE
【分享】polaris在使用grpc连接注册中心时，总是报超时问题的一个解决场景

### ISSUE THREAD

**Issue by qianxiao1314** [Tencent/spring-cloud-tencent#806]
在springboot（2.7.1版本）项目里，引入北极星依赖如下 
 
            <dependency>
                <groupId>com.tencent.cloud</groupId>
                <artifactId>spring-cloud-tencent-dependencies</artifactId>
                <version>1.8.1-2021.0.3</version>
                <type>pom</type>
                <scope>import</scope>
          </dependency>
出现以下问题
![073e179b3a21c6b1f30b2578bfec299](https://user-images.githubusercontent.com/37626376/211501187-c9454f70-cdcb-40ae-8541-f77a98ec465d.png)
解决方式参考：https://stackoverflow.com/questions/59880287/nosuchmethodexception-and-noclassdeffounderror-in-grpc-protobuf-java
最终我的pom依赖为：

  
            <dependency>
                <groupId>com.tencent.cloud</groupId>
                <artifactId>spring-cloud-tencent-dependencies</artifactId>
                <version>1.8.1-2021.0.3</version>
                <type>pom</type>
                <scope>import</scope>
          </dependency>
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>3.11.0</version>
            </dependency>

**Comment by SkyeBeFreeman** [comment]
@qianxiao1314 可以提到polaris-java项目下统一更新依赖版本，https://github.com/polarismesh/polaris-java/issues

**Comment by chuntaojun** [comment]
> @qianxiao1314 可以提到polaris-java项目下统一更新依赖版本，https://github.com/polarismesh/polaris-java/issues

这不是依赖更新的问题，是用户的grpc依赖和polaris-java依赖冲突的问题
