### ISSUE TITLE
查看，新增，修改等配件文件步骤太复杂，UI布局体验不好，希望能优化下

### ISSUE THREAD

**Issue by jaimyjie** [Tencent/spring-cloud-tencent#807]
查看，新增，修改等配件文件步骤太复杂，UI布局体验不好，希望能优化下。
尽量每个任务操作能在1-2级页面或步骤处理完，UI布局直观点。可以借鉴下友商的系统。

**Comment by SkyeBeFreeman** [comment]
针对北极星服务端的建议提到这里，https://github.com/polarismesh/polaris/issues
