### ISSUE TITLE
【需求认领】优化ServiceRuleManager获取规则的逻辑

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#822]
**What is the feature you want to add?**

将`ServiceRuleManager`中`getServiceRateLimitRule`和`getServiceRouterRule`两个方法中获取服务规则（限流规则、路由规则）的实现逻辑进行优化，去掉`BaseFlow.syncGetResources`这类偏底层的调用，改为使用`ConsumerAPI.getServiceRule`的实现。

**Why do you want to add this feature?**

原有的方式没有对入参进行校验，有代码运行异常的风险。

**How to implement this feature?**

**Additional context**

无。

**Comment by DoubleLuXu** [comment]
这个 安排我来试试
