### ISSUE TITLE
集成circuitbreaker插件启动报错

### ISSUE THREAD

**Issue by youtaqiu** [Tencent/spring-cloud-tencent#829]
## 环境
Spring Boot 3.0.2
Spring Cloud 2022.0.1
Spring Cloud 1.8.5-2022.0.1
## 问题
引入熔断组件后，项目启动报错
2023-02-10 11:45:03,737 ERROR 69317 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

Description:

Parameter 0 of method circuitBreakerConfigModifier in com.tencent.cloud.polaris.circuitbreaker.config.PolarisCircuitBreakerAutoConfiguration required a bean of type 'com.tencent.cloud.rpc.enhancement.config.RpcEnhancementReporterProperties' that could not be found.

Action:

Consider defining a bean of type 'com.tencent.cloud.rpc.enhancement.config.RpcEnhancementReporterProperties' in your configuration.

**Comment by SkyeBeFreeman** [comment]
Will fix in 1.9.0.

**Comment by youtaqiu** [comment]
> Will fix in 1.9.0.

That's great.

**Comment by SkyeBeFreeman** [comment]
Use new version of 1.9.0-2022.0.1.
