### ISSUE TITLE
根据boot是2.5x版本，引入对应的polaris，报下面的错，maven是阿里云的源

### ISSUE THREAD

**Issue by WindSearcher** [Tencent/spring-cloud-tencent#833]
Unresolved dependency: 'com.tencent.cloud:spring-cloud-starter-tencent-polaris-config:pom:1.9.0-2020.0.5'

**Comment by SkyeBeFreeman** [comment]
中央仓库已有该pom，https://repo1.maven.org/maven2/com/tencent/cloud/spring-cloud-starter-tencent-polaris-config/1.9.0-2020.0.5/spring-cloud-starter-tencent-polaris-config-1.9.0-2020.0.5.pom

可以尝试切换maven源或者强制更新等方式重试一下。
