### ISSUE TITLE
【需求认领】支持北极星负载均衡

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#843]
添加配置读取北极星负载均衡配置，包括`LOAD_BALANCE_WEIGHTED_RANDOM`和`LOAD_BALANCE_RING_HASH`

**Comment by DoubleLuXu** [comment]
我理解下这个需求看下：
现在sct负载的策略是 polarisWeighted，要做的是添加配置 对应北极星中的负载配置LOAD_BALANCE_WEIGHTED_RANDOM和LOAD_BALANCE_RING_HASH，然后要做的事情是：
1，PolarisLoadBalancerClientConfiguration 中原来的bean ReactorLoadBalancer<ServiceInstance>添加一个polarisRingHash，
2，替换掉PolarisLoadBalancer中的RouterAPI 使用北极星的LoadBalancer做负载

是这样吗？

**Comment by DoubleLuXu** [comment]
@SkyeBeFreeman

**Comment by SkyeBeFreeman** [comment]
@DoubleLuXu 感谢关注！这里要做的事情，我再稍微补充一下：
1. 无需替换原有的RouterAPI使用方式，只是需要拓展负载均衡规则的设置。
2. 允许开发者通过bean的方式，实现提供好的SPI，来提供Hash key。这个hash key将使用在hash负载均衡：
```java
ProcessLoadBalanceRequest request = new ProcessLoadBalanceRequest();
request.setDstInstances(convertToPolarisServiceInstances(serviceInstances));
request.setLbPolicy(LoadBalanceConfig.LOAD_BALANCE_RING_HASH);
Criteria criteria = new Criteria();
criteria.setHashKey(hashKeyProvider());
request.setCriteria(criteria);
```
