### ISSUE TITLE
多注册与多发现中Nacos配置标题写成了Consul

### ISSUE THREAD

**Issue by sky-0914** [Tencent/spring-cloud-tencent#848]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/25810110/218966557-293de23e-e15a-419e-8267-e7d4d3f08202.png">
文档地址：https://github.com/Tencent/spring-cloud-tencent/wiki/Multi-registration-and-multi-discovery

**Comment by SkyeBeFreeman** [comment]
Fixed.

Thx for reporting.
