### ISSUE TITLE
【需求认领】希望服务注册时能增加自定义端口配置

### ISSUE THREAD

**Issue by zev-223** [Tencent/spring-cloud-tencent#849]
生产环境的网络环境往往会比较复杂，服务的ip和端口经常会被映射，目前stc是支持ip自定义配置的，希望能端口也能自定义配置。

**Comment by andrewshan** [comment]
可以给一个实际的场景么？

**Comment by andrewshan** [comment]
主要是内外网端口映射的场景？spring cloud tencent监听的是内网端口，实际暴露的是外网端口？

**Comment by zev-223** [comment]
> 主要是内外网端口映射的场景？spring cloud tencent监听的是内网端口，实际暴露的是外网端口？

嗯，是的，我们服务器能暴露的端口都被限制了，如果单台服务器部署多个微服务，就需要通过代理的方式来实现同一个端口访问不同的服务，这样的话注册到北极星的实例是无法健康访问，目前是通过在北极星控制台手动添加服务实例来解决的。
