### ISSUE TITLE
灰度发布功能中透传标识获取不到header信息

### ISSUE THREAD

**Issue by lidinglin** [Tencent/spring-cloud-tencent#850]
**Describe the bug**
使用灰度发布功能的时候，在前置网关上添加的header(gray=true)在进行透传标识的时候为空，经检查发现com.tencent.cloud.polaris.router.feign.RouterLabelFeignInterceptor 在
com.tencent.cloud.metadata.core.EncodeTransferMedataFeignInterceptor 之前被执行，导致一开始获取不到header信息。

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: 1.9.0-2022.0.1
- OS: CentOS7

**Additional context**

尝试修改com.tencent.cloud.common.constant.MetadataConstant.OrderConstant中
METADATA_2_HEADER_INTERCEPTOR_ORDER = -1 可以通过验证。

**Comment by SkyeBeFreeman** [comment]
`RouterLabelFeignInterceptor`是用于服务路由前设置路由上下文的拦截器，需要在服务路由之前执行。`EncodeTransferMedataFeignInterceptor`是Feign向下游服务传递metadata的拦截器，需要在最后执行。从上游获取metadata信息的部分在`DecodeTransferMetadataServletFilter`和`DecodeTransferMetadataReactiveFilter`。

**Comment by lidinglin** [comment]
> `RouterLabelFeignInterceptor`是用于服务路由前设置路由上下文的拦截器，需要在服务路由之前执行。`EncodeTransferMedataFeignInterceptor`是Feign向下游服务传递metadata的拦截器，需要在最后执行。从上游获取metadata信息的部分在`DecodeTransferMetadataServletFilter`和`DecodeTransferMetadataReactiveFilter`。

RouterLabelFeignInterceptor 先执行的话，请求头里面的信息还没有被透传，导致FeignExpressionLabelUtils.resolve(requestTemplate, labelKeys) 获取到的透传标签值为空，后续不能正常匹配路由规则。是不是要先将header信息放到请求头里面来？

**Comment by SkyeBeFreeman** [comment]
> > `RouterLabelFeignInterceptor`是用于服务路由前设置路由上下文的拦截器，需要在服务路由之前执行。`EncodeTransferMedataFeignInterceptor`是Feign向下游服务传递metadata的拦截器，需要在最后执行。从上游获取metadata信息的部分在`DecodeTransferMetadataServletFilter`和`DecodeTransferMetadataReactiveFilter`。
> 
> RouterLabelFeignInterceptor 先执行的话，请求头里面的信息还没有被透传，导致FeignExpressionLabelUtils.resolve(requestTemplate, labelKeys) 获取到的透传标签值为空，后续不能正常匹配路由规则。是不是要先将header信息放到请求头里面来？

首先明确一点，RouterLabelFeignInterceptor中处理的请求头，是上游传递下来的原本的请求头。如果没有定义ExpressionLabelUtils.isExpressionLabel(labelKey)满足的路由规则，确实不会将请求头作为路由规则进行匹配。

而EncodeTransferMedataFeignInterceptor只是向下游传递标签的，和路由的处理没有关联。

或者您可以提供遇到问题的场景，我们一起尝试复现一下。
