### ISSUE TITLE
「需求」有计划支持任务调度吗？

### ISSUE THREAD

**Issue by beiming-org** [Tencent/spring-cloud-tencent#918]
想问问有计划在北极星中添加任务调度的功能吗？

**Comment by chuntaojun** [comment]
任务的调度应该不属于服务治理的一部分，任务调度可以看下业内成熟的组件，直接在 sct 内集成使用

**Comment by beiming-org** [comment]
是的，业内有非常多成熟的产品，如果SCT可以为SCT打造一套全生态、融合的、一站式的微服务解决方案，会有非常强的竞争力。

**Comment by chuntaojun** [comment]
目前java的调度框架应该都有自己的 spring cloud starters，直接用起来就好了，sct 这里感觉没有必要重复造这个轮子

**Comment by chuntaojun** [comment]
但是对于任务调度，可能存在一些灰度策略，这个倒是一个值得一起研究的地方，怎么来针对调度任务做灰度测试
