### ISSUE TITLE
loadbalancer 使用

### ISSUE THREAD

**Issue by lhzsdnu** [Tencent/spring-cloud-tencent#950]
![image](https://user-images.githubusercontent.com/20517550/229803421-d2448132-9b5c-45e8-8d76-99e5213ea71e.png)

代码中负载均衡为什么使用上面那个依赖，不用下面那个依赖呢

![image](https://user-images.githubusercontent.com/20517550/229803203-b4f11a3e-6d84-43b5-bd1c-963a6038e4da.png)

**Comment by SkyeBeFreeman** [comment]
`spring-cloud-starter-loadbalancer` 本身没有包含必要的逻辑，因此使用 `spring-cloud-loadbalancer` 满足需求即可。

参考：https://github.com/spring-cloud/spring-cloud-commons/tree/main/spring-cloud-starter-loadbalancer

**Comment by lhzsdnu** [comment]
![image](https://user-images.githubusercontent.com/20517550/230259061-c2cfa077-cb87-4213-a325-345937637040.png)
spring-cloud-starter-loadbalancer 里面的 spring-boot-starter-cache 有 spring-context-support 依赖

![image](https://user-images.githubusercontent.com/20517550/230259974-46098190-a095-4dac-9180-206b821447db.png)

如果使用 caffeine ，spring-cloud-starter-loadbalancer 不用额外引入 spring-context-support ，感觉更方便些

**Comment by SkyeBeFreeman** [comment]
目前SCT的loadbalancer已使用底层SDK polaris-java的缓存机制，因此无需额外引入缓存组件。
