### ISSUE TITLE
配置中心的刷新方式

### ISSUE THREAD

**Issue by suifeng1314** [Tencent/spring-cloud-tencent#954]
**What is the feature you want to add?**
配置动态的刷新方式
**Why do you want to add this feature?**
要手动修改配置和注解才能实现
**How to implement this feature?**
启动日志进行提示
**Additional context**
![image](https://user-images.githubusercontent.com/29766120/230397134-111cd697-dbe0-4e1f-84fe-44ecc7638e81.png)

**Comment by chuntaojun** [comment]
或者是否可以做一些安全检查，比如发现不是走refresh-context 的方式，但是又引入了 refresh-scope 注解，感觉可以做一些warn警告？

**Comment by SkyeBeFreeman** [comment]
初步优化：
当使用反射的方式时，WARN日志提示无需添加 `@RefreshScope` 注解。

进一步优化：
应用启动时扫描所有包，若存在 `@RefreshScope` 注解，则自动替换为 `refresh_context` 模式并WARN日志提示因为注解的引入导致配置刷新机制的切换。

**Comment by LuckyCaesar** [comment]
> 初步优化： 当使用反射的方式时，WARN日志提示无需添加 `@RefreshScope` 注解。
> 
> 进一步优化： 应用启动时扫描所有包，若存在 `@RefreshScope` 注解，则自动替换为 `refresh_context` 模式并WARN日志提示因为注解的引入导致配置刷新机制的切换。

这个我觉得是不是改成扫描所有的bean比较好？因为只有用户在bean上使用了 `@RefreshScope` 注解，才代表他想要这种刷新方式。如果只是引用的话，也有可能是第三方依赖包中引入的，不一定反馈了用户真实的意图。

**Comment by SkyeBeFreeman** [comment]
> > 初步优化： 当使用反射的方式时，WARN日志提示无需添加 `@RefreshScope` 注解。
> > 进一步优化： 应用启动时扫描所有包，若存在 `@RefreshScope` 注解，则自动替换为 `refresh_context` 模式并WARN日志提示因为注解的引入导致配置刷新机制的切换。
> 
> 这个我觉得是不是改成扫描所有的bean比较好？因为只有用户在bean上使用了 `@RefreshScope` 注解，才代表他想要这种刷新方式。如果只是引用的话，也有可能是第三方依赖包中引入的，不一定反馈了用户真实的意图。

是的，可以只扫描所有的bean。
