### ISSUE TITLE
springcloud gateway集成SCT后如何开启负载均衡重试机制

### ISSUE THREAD

**Issue by beretaa** [Tencent/spring-cloud-tencent#961]
![image](https://user-images.githubusercontent.com/130036897/230915651-434bf4dd-f75a-4fb9-9ff8-fb6e64262c8b.png)
依赖里也加入了spring.retry, 但这样配置不生效,有大佬帮忙解答一下吗

**Comment by beretaa** [comment]
点错了 label 不好意思...

**Comment by SkyeBeFreeman** [comment]
@beretaa 具体不生效的效果是如何呢？

**Comment by beretaa** [comment]
@SkyeBeFreeman 你好,我在测试优雅上下线, 当新容器上线时,旧容器下线, 但总会存在一段窗口期, 即网关的负载均衡列表里既有新实例又有已下线实例, 如果请求打到旧实例上会报connection timeout ,  此时应当尝试请求列表中的其他实例, 但按照以上配置始终无法实现该效果

**Comment by beretaa** [comment]
版本:
SCT: 1.10.3-2020.0.6
Springcloud: 2020.0.6
Springboot : 2.4.13
spring-cloud-gateway: 3.0.8

**Comment by SkyeBeFreeman** [comment]
SCG引入重试机制一般是使用`Retry Filter`，可以参考example中的配置项：https://github.com/Tencent/spring-cloud-tencent/blob/2021.0/spring-cloud-tencent-examples/polaris-gateway-example/gateway-scg-service/src/main/resources/bootstrap.yml#L41

**Comment by beretaa** [comment]
@SkyeBeFreeman 感谢,问题解决
