### ISSUE TITLE
SCT 心跳上报异常终止

### ISSUE THREAD

**Issue by beretaa** [Tencent/spring-cloud-tencent#965]
版本:
SCT:  1.10.3-2020.0.6
Springcloud: 2020.0.6
Springboot : 2.4.13

服务启动一段时间之后, 心跳不上报, 不再打印日志:AsyncHeartbeat]Instance heartbeat success 
但是pod正常

**Comment by SkyeBeFreeman** [comment]
这里可以在`polaris/logs/polaris.log`查看到异常日志不？

**Comment by beretaa** [comment]
没有异常日志, 看起来好像是心跳线程不见了

**Comment by SkyeBeFreeman** [comment]
这里是只在容器环境会稳定复现，还是在本地运行也会复现呢？

**Comment by beretaa** [comment]
@SkyeBeFreeman 服务端会出现,  发现日志里有报GRPC连接错误, 怀疑是节点太多了, 北极星后台撑不住, 扩容了后台节点后观察了几天, 普通服务没有下线情况, 但gateway会有

**Comment by SkyeBeFreeman** [comment]
@beretaa 这边大概是多少节点数呢？我们这边也可以尝试复现下。 @chuntaojun cc

**Comment by beretaa** [comment]
@SkyeBeFreeman 测试节点数在60到90个左右, 随时扩缩容

**Comment by SkyeBeFreeman** [comment]
> @SkyeBeFreeman 测试节点数在60到90个左右, 随时扩缩容

@beretaa 收到。你们这边北极星集群部署的规格如何呢？

**Comment by SkyeBeFreeman** [comment]
@beretaa 方便加一下交流群不？我们拉个小群一起看看这个问题

![image](https://user-images.githubusercontent.com/24446200/232946787-799aa755-c628-4e47-b3e6-969baa7122dc.png)

**Comment by beretaa** [comment]
limits:
  cpu: '3'
  memory: 4Gi
单节点资源是以上配置,  最开始是1个节点在跑, 后来扩容到3个节点就正常

**Comment by chuntaojun** [comment]
服务端会出现, 发现日志里有报GRPC连接错误, 怀疑是节点太多了, 北极星后台撑不住
----

是指在北极星服务端有这个日志？方便把日志放出来我这里看看吗？

**Comment by beretaa** [comment]
@chuntaojun  抱歉我的描述有误, 服务端指的是容器里的应用服务...  这是当时出问题时候的一个日志截图,现在扩容后没有出现该问题

![image](https://user-images.githubusercontent.com/130036897/233248994-8990cacb-b13c-4e24-b6fb-5700f3fdf82e.png)

**Comment by chuntaojun** [comment]
如果还有下列问题的话，可能需要给一下北极星服务端的日志

**Comment by beretaa** [comment]
@chuntaojun 好的谢谢
