### ISSUE TITLE
在对应服务名的group下设置`application.yaml`文件无效

### ISSUE THREAD

**Issue by youtaqiu** [Tencent/spring-cloud-tencent#979]
**Describe the bug**
将默认的application配置文件的格式设置为`yaml`会失效,改为`yml`正常
**Environment**
- SCT Version: [1.11.1-2022.0.1]
- Spring Boot Version [3.0.6]
- Spring Cloud Version [2022.0.2]
- Polaris Version: [1.6.3]
- OS: [e.g. MacOS Ventura 13.3.1]

**Comment by SkyeBeFreeman** [comment]
可以在 `com.tencent.cloud.polaris.config.adapter.PolarisConfigFilePuller#buildInternalApplicationConfigFiles` 方法增加 `application*.yaml` 和 `com.tencent.cloud.polaris.config.adapter.PolarisConfigFilePuller#buildInternalBootstrapConfigFiles` 方法增加 `bootstrap*.yaml` 的默认配置加载，并更新到wiki。

**Comment by SkyeBeFreeman** [comment]
@youtaqiu 是否有兴趣贡献下这一块的代码呢？

**Comment by youtaqiu** [comment]
好的,我已经提交了
