### ISSUE TITLE
Nacos配置自动刷新时,将导致心跳停止

### ISSUE THREAD

**Issue by beretaa** [Tencent/spring-cloud-tencent#984]
配置中心使用Nacos且未关闭自动刷新时, 修改配置文件将触发SCT心跳停止,一些GRPC组件被回收

处理方案...配置 spring.cloud.nacos.config.refresh-enabled=false

**Comment by SkyeBeFreeman** [comment]
应该是配置刷新触发bean重建，进而导致SDKContext没有重新触发心跳，下个版本将修复这个问题。如果使用北极星配置中心，可以使用反射的刷新策略来规避这个问题。
